### ISSUE TITLE
Richiesta di versione .md

### ISSUE THREAD

**Issue by Gix075** [FattiDiCookies/italianPrivacyPolicy#10]
@andreaperugia  potresti committare una versione markdown del file che caricato in modo che sia più facilmente consultabile direttamente da GitHub?

**Comment by andreaperugia** [comment]
Ciao, il problema è che non sono molto pratico con le funzioni di GitHub,
vedo cosa riesco a fare

Il giorno 27 maggio 2015 01:40, Gix075 notifications@github.com ha
scritto:

**Comment by Gix075** [comment]
Ho spostato i file nella cartella bozze/privacy-policy per dare un po' d'ordine al repository.
Ti ho citato nella discussione https://github.com/FattiDiCookies/italianPrivacyPolicy/issues/19 perché un file di privacy lo avevamo già iniziato a stendere e discutere con alcuni del team. 
Sicuramente nella tua versione ci sono cose che possono essere integrate nell'altra. Dagli un'occhiata e proponi quello che credi utile nella discussione che ti ho segnalato. Questa issue sul formato md intanto la chiudo.
