### ISSUE TITLE
Richiesta di approvazione: Google Analytics 

### ISSUE THREAD

**Issue by Gix075** [FattiDiCookies/italianPrivacyPolicy#11]
@iusondemand  @akybaud  @PixedBo @lmbuffetti @andreaperugia @FattiDiCookies/writers @FattiDiCookies/developers @FattiDiCookies/owners @hmtechnology @seosmart @vannaccirere @Saladino79 @LenusMedia @lidialab e tutti gli altri

Posto qui quello che a mio avviso potrebbe essere il testo del servizio Google Analytics. E' importante che ci buttiate un'occhiata un po' tutti in modo da sistemarla nel minor tempo possibile. Dobbiamo sbrigarci!

**Google Analytics (testo generico)**
Il servizio di statistiche **Google Analytics** utilizzato da **[[NOME SITO]]** è un sistema in grado di tracciare il comportamento degli utenti durante la navigazione. 
I cookie rilasciati da questo servizio vengono utilizzati per collezionare informazioni sull’uso del sito nonché generare statistiche dettagliate fruibili dagli amministratori del sito **[[NOME SITO]]** in forma completamente anonima.
Goolge, proprietaria del servizio, utilizzerà tali dati al fine di condividerli con altri servizi da essa forniti e per generare annunci pubblicitari (proposti attraverso i canali AdSense), che siano di gradimento all’utente.
Il sito **[[NOME SITO]]** non profila in prima parte e non ha accordi con Google per profilare in prima parte.

**Google Analytics Anonimo**
Questo sito utilizza il sistema Google Analytics in modalità anonima.
Attraverso questa modalità di utilizzo Google registrerà l’indirizzo IP dell’utente in forma non estesa, garantendo quindi l’anonimato dell’utente. Questa modalità è attiva solo all’interno dei paesi facenti parte della Comunità Europea.

**Link di riferimento**
[http://www.google.com/intl/it_ALL/analytics/learn/privacy.html](http://www.google.com/intl/it_ALL/analytics/learn/privacy.html)
[https://support.google.com/analytics/answer/6004245?hl=it](https://support.google.com/analytics/answer/6004245?hl=it)
[https://developers.google.com/analytics/devguides/collection/analyticsjs/cookie-usage](https://developers.google.com/analytics/devguides/collection/analyticsjs/cookie-usage)

**Comment by Gix075** [comment]
P.S.: Chiudo le issue vecchie di analytics al fine di non fare confusione.

**Comment by hmtechnology** [comment]
Mi sembra valido. Conto di "revisionare" sia questo che sharethis che gli altri non appena mi dedico ai servizi aggiuntivi come da te richiesto per la Privacy;)

**Comment by akybaud** [comment]
Per GA Generico: è pensato per siti che usano anche AdSense? Perché in caso
contrario non farei la citazione a come Google usa i dati, penso che si
rischia di spaventare qualcuno che poi blocchi i cookie solo per quello.

Relativamente alla parte per GA Anonimo. Indicare che l'IP viene registrato
in modo non esteso (che è tecnicamente corretto), è comprensibile per chi
dovesse leggere? (ovviamente non leggerà mai nulla nessuno, ma...). Gli
utenti non sanno nemmeno cosa sono i cookie, figuriamoci se sanno cos'è
l'IP address... Solo un dubbio.

grazie

Il giorno 27 maggio 2015 01:53, Gix075 notifications@github.com ha
scritto:

**Comment by PixedBo** [comment]
Direi OK. Non sono sicurissimo al 100% che i cookie singoli non debbano essere elencati (o almeno, nelle segnalazioni del garante non se ne parla) però ho visto che alcuni li segnano uno ad uno...

Io personalmente sarei per mettere solo il servizio per evitare di cambiare la privacy nel caso in cui analytics cambi i nomi dei cookies

**Comment by Gix075** [comment]
@akybaud questa parte è stata scritta solo per analytics. Per AdSense bisognerà scrivere una parte aggiuntiva. 

Per quello che riguarda l'ip non sono riuscito a trovare un modo più sintetico di spiegare la cosa. Se ci sono idee migliori però sono benvenute.

**Comment by Gix075** [comment]
@PixedBo possiamo pensare anche di elencarli, però io ho pensato proprio come te. Per evitare di doverli aggiornare ad ogni loro update se trovassimo una pagina specifica nella loro documentazione forse sarebbe meglio.

**Comment by PixedBo** [comment]
@Gix075 allora linkiamo questa che sicuramente sarà sempre aggiornata :)

https://developers.google.com/analytics/devguides/collection/analyticsjs/cookie-usage

**Comment by Gix075** [comment]
@PixedBo ho aggiunto il link al testo.

**Comment by akybaud** [comment]
@Gix075 provo a vedere se mi viene in mente qualcosa per il discorso dell'indirizzo Ip..
come avevo detto ho contattato un conoscente che si occupa di segreti industriali, protezione opere dell'ingegno e cose di questo tipo, e gli ho sottoposto tutto quello che era stato prodotto fino a ieri.
Sto aspettando un suo commento.
Pensate che possa essere utile chiedergli anche di partecipare alla stesura?

**Comment by akybaud** [comment]
per il discorso della lista dei cookie anche io sarei d'accordo a non elencarli tutti perché altrimenti vuol dire monitorare costantemente i cambiamenti che i vari player potrebbero fare e modificare l'informativa di conseguenza

**Comment by Gix075** [comment]
@akybaud se il tuo amico "legale" volesse collaborare sarebbe ottimo.

**Comment by akybaud** [comment]
ok, allora glielo propongo. Intanto... sto aspettando la sua risposta alla mia richiesta di "check" su quello che è stato prodotto

**Comment by iusondemand** [comment]
ELENCO COOKIE:
Non trovo la fonte, vado a memoria, avevo letto che non era necessario elencare i singoli cookies.
Mi sembra invece che si debbano elencare tutti i servizi terzi per poter linkare le loro policy.

TESTO PROPOSTO
Mi sembra a posto, non dimentichiamo di inserire i link indicati. Non va bene per chi ha accordi con google per profilare in prima persona. Il mio suggerimento e' di aggiungere: questo sito [ _ |non] profila in prima parte e [ _ |non] ha accordi con google per profilare in prima parte.
Insomma bisognerebbe sempre evidenziare quando "subiamo" la profilazione di google perche' non ne facciamo parte attiva dal caso in cui iniziamo la profilazione dei lettori per proporre nostri prodotti (retargeting)

**Comment by hmtechnology** [comment]
Ovviamente se elenchi i singoli cookie sei ancora più a posto, ma la normativa accetta anche che si raggruppino per categorie (tipo analytics, marketing, etc)

**Comment by Gix075** [comment]
Io direi che per la natura del progetto modulare dovremmo inserire descrizioni di ogni tipo di servizio che rilascia cookie. Per quanto concerne il nome dei singoli cookie farei riferimento alle pagine dei servizi in modo da non dover costantemente aggiornare l'elenco.

@iusondemand inserire la specifica della non profilazione in prima persona mi sembra un'ottima idea. La integro subito. Secondo te il discorso vale per ogni servizio dove c'è certezza o dubbio di profilazione di terze parti?

**Comment by hmtechnology** [comment]
E' difficile avere dubbi su cookie (se terzi o proprietari) ma la specifica che la profilazione è di terzi e non nostra è ottima e ci differenzia anche dalle altre soluzioni commerciali che offrono questi servizi;)

**Comment by Gix075** [comment]
Quindi dici di inserire la dicitura nella descrizione di ogni servizio?

**Comment by hmtechnology** [comment]
Yes, per specificare che non siamo noi a profilare (anche se è ovvio).

**Comment by Gix075** [comment]
Ok allora provvedo ad inserirlo in ogni servizio.

**Comment by vannaccirere** [comment]
In questo momento sto provvedendo a redarre diverse pagine di informativa estesa dei cookie. Al momento, la soluzione che mi trova più cookie possibili è www.webcookies.org. quando dichiaro i cookie riporto il codice rosrgente della loro tabella traducendo le descrizioni da inglese a italiano. Sarebbe bello creare un generatore. A tutti i partecipanti su questa pagina: #WOR è un nuovo gruppo facebook dedicato allo sviluppo collettivo per l'opensource

**Comment by lmbuffetti** [comment]
Scusate se non sono di molto supporto ma in questi giorni sono strapieno di lavoro, comunque appena arriviamo ad una versione definitiva lo traduco in inglese così sarò di aiuto anche io.

**Comment by iusondemand** [comment]
@Gix075  mi dicevi: 
"@iusondemand inserire la specifica della non profilazione in prima persona mi sembra un'ottima idea. La integro subito. Secondo te il discorso vale per ogni servizio dove c'è certezza o dubbio di profilazione di terze parti?"

Si', l'idea e' questa. In teoria ognuno puo' usare servizi terze parti per profilare o non profilare. Il garante vuole che emergano queste situazioni. Aiutiamolo: non profilo ne' da me ne' con il plugin di terze parti. Se aggiungo che metto il codice per anonimizzare, perfetto.

L'unica attenzione e' magari verificare cosa offra il servizio di esterno, perche' sembra che alcuni restituiscano dati utili per la profilazione anche in prima persona. Di questo pero' racconto dicerie e quindi non valutatele come cose serie. E' solo un dubbio e se nessuno ne sa niente, cestinate :)
(io di google analytics mi sono stufato da tempo (di regalargli tutti i dati), quindi non so piu' cosa offre oggi. E ormai uso mie statistiche interne molto semplici ma utili).

**Comment by Gix075** [comment]
Ok, al momento mi sembra di aver integrato tutte le cose segnalate. Per questioni di fretta direi che se entro giovedì sera non arrivano altre richieste di cambiamento darei questo testo per definitivo. Poi alla bisogna ci si rimette mano.

**Comment by Gix075** [comment]
Data la mancanza di tempo **ho dato per buono questo testo** (con le modifiche suggerite) ed ho aggiunto un file nella directory **["docs/md/cookie-policy/services"](https://github.com/FattiDiCookies/italianPrivacyPolicy/tree/master/docs/cookie-policy/md/services). 

Per il momento chiudo l'issue. In caso di cambiamenti da fare è possibile riaprire il ticket.

**Comment by vannaccirere** [comment]
ho inserito il file html

**Comment by hmtechnology** [comment]
#### Google Analytics (generico+anonimizzato)

_Google Analytics_ è uno strumento analitico, [www.google.it/intl/it/analytics/](www.google.it/intl/it/analytics/), che aiuta i proprietari di siti web a misurare le statistiche del sito web. In particolare _Google Analytics_ fornisce indicazioni su come gli utenti interagiscono con i contenuti del sito, con che frequenza gli utenti visitano ciascuna pagina del sito, per quanto tempo si trattengono e con quale frequenza generano una conversione. _Google Analytics_ utilizza principalmente cookie proprietari per generare i rapporti sulle interazioni dei visitatori con i siti web. Questi cookie vengono utilizzati per memorizzare informazioni che non consentono l'identificazione personale degli utenti. Inoltre, utilizzando il metodo di [mascheratura dell'indirizzo IP](https://support.google.com/analytics/answer/2905384?hl=it), le informazioni memorizzate nel cookie vengono ridotte a un numero identificativo casuale. Gli utenti dei siti web che non vogliono che i dati relativi alla loro visita vengano monitorati possono installare il [componente aggiuntivo del browser per la disattivazione di Google Analytics](https://tools.google.com/dlpage/gaoptout). 
[[NOME SITO]] non utilizza il servizio _Google Analytics_ per la profilazione dell'utente in prima parte e non ha accordi con _Google Analytics_ per profilare in prima parte.

#### Link di riferimento
- [Protezione dei dati di Google Analytics](http://www.google.com/intl/it_ALL/analytics/learn/privacy.html)
- [Google Analytics Cookie Usage on Websites](https://developers.google.com/analytics/devguides/collection/analyticsjs/cookie-usage)

**Comment by vannaccirere** [comment]
Direi: ottimo!

**Comment by iusondemand** [comment]
perfetto

**Comment by akybaud** [comment]
a me pare ottimo! 
complimenti ragazzi

**Comment by Gix075** [comment]
Per me è ok!

**Comment by vannaccirere** [comment]
Raga, difronte a tanta competenza mi tolgo il cappello

**Comment by Gix075** [comment]
Chiudo alcune vecchie issue per fare un po' di pulizia e focalizzare sulle nuove. Se serve riaprite.
