### ISSUE TITLE
Servizio ShareThis

### ISSUE THREAD

**Issue by Gix075** [FattiDiCookies/italianPrivacyPolicy#12]
Questo è quello che scrivono loro in risposta sul forum quindi in teoria non sono cookie di profilazione

_We currently use two ShareThis.com cookies to identify users and their sharing behavior. _stid is a random unique identifier not tied to any personally identifiable information (PII), and _uset is set to "true" to indicate when a user has been cookied so that we don't repeat the task in the next 8 hours. _stid is used to associated users with topics of interest, based upon the content they consume and share. In the U.S., we use these data to help advertisers deliver targeted messages to users. We do not use the data outside of the U.S. at this point in time. It's definitely not considered "necessary" by the EU regulatory requirements._

Io però ho preparato questo testo, dategli un'occhiata

**ShareThis**
_ShareThis_ è un sistema rilasciato da [http://www.sharethis.com/](http://www.sharethis.com/) che permette la facile condivisione dei contenuti di questo sito sui principali social networks.
Il servizio _ShareThis_ permette inoltre agli amministratori del sito **[[NOME SITO]]** di consultare statistiche dettagliate sul numero e i contenuti delle condivisioni effettuate dagli utenti. 
Il servizio _ShareThis_ attraverso l'uso dei propri cookie colleziona dati sulla navigazione degli utenti anche al di fuori di questo sito. 
Il sito [[NOME SITO]] non utilizza il servizio _ShareThis_ per la profilazione dell'utente in prima parte e non ha accordi con _ShareThis_ per profilare in prima parte.

**Link di riferimento**
[http://www.sharethis.com/legal/privacy](http://www.sharethis.com/legal/privacy)

**Comment by hmtechnology** [comment]
In teoria da quel che dichiariano mi pare siano proprio cookie di profilazione (di terze parti). 
"It's definitely not considered "necessary" by the EU regulatory requirements." 

significa che non sono cookie tecnici dunque c'è poca scelta su cosa sono; 

inoltre

"_stid is used to associated users with topics of interest, based upon the content they consume and share. In the U.S., we use these data to help advertisers deliver targeted messages to users. " 

signfica che appunto questo cookie è associato al comportamento dell'utente, di quello che condivide, e che viene usato x aiutare gli advertisers a inviare messaggi targetizzati, etc

**Comment by Gix075** [comment]
"It's definitely not considered "necessary" by the EU regulatory requirements."
Credo si riferisse alla domanda che gli veniva posta nel forum sulla necessità di bloccare i cookie di ShareThis.

Il link è questo [http://support.sharethis.com/customer/portal/questions/721127-cookies#sthash.7yBfFtnw.dpbs](http://support.sharethis.com/customer/portal/questions/721127-cookies#sthash.7yBfFtnw.dpbs) ma credo che devi essere registrato per leggerlo.

Però mi rimetto anche all'altrui intepretazione ... almeno non rischiamo.

**Comment by hmtechnology** [comment]
Ah ok, lì può anche essere (ma è una sua ipotesi) ma quanto dice poco prima, dove parla di advertisers, penso sia lampante.

**Comment by PixedBo** [comment]
Tenderei a non fidarmi di chi difende a spada tratta i propri cookies.. non tanto per "malafede" quanto per "troppa semplificazione". Io direi di considerarli profilazione di terze parti a tutti gli effetti e di regolarci di conseguenza, in modo da essere sempre e comunque protetti nel caso della legge italiana (che da quel che ho capito è più restrittiva)

**Comment by Gix075** [comment]
Ok inseriamolo allora fra i cookie di profilazione.

**Comment by hmtechnology** [comment]
sì qnd c'è qualcosa del genere "this cookie is used to associated users with topics of interest, based upon the content they consume and share. In the U.S., we use these data to help advertisers deliver targeted messages to users" è assolutamente senza dubbio cookie di profilazione.

**Comment by Gix075** [comment]
Si si per me è da catalogarsi come profilazione però sulla normativa è scritto chiaramente che se il servizio dichiara di non profilare la responsabilità è tutta del proprietario del cookie e non dell'editore. Comunque per non rischiare noi lo inseriamo nella policy come profilazione.

**Comment by Gix075** [comment]
Ho cambiato un po' il testo e messo in "approvazione richiesta". Datemi i vostri pareri.

**Comment by Gix075** [comment]
Data la mancanza di tempo **ho dato per buono questo testo** (con le modifiche suggerite) ed ho aggiunto un file nella directory **["docs/md/cookie-policy/services"](https://github.com/FattiDiCookies/italianPrivacyPolicy/tree/master/docs/cookie-policy/md/services). 

Per il momento chiudo l'issue. In caso di cambiamenti da fare è possibile riaprire il ticket.
