### ISSUE TITLE
Servizio DISQUS

### ISSUE THREAD

**Issue by Gix075** [FattiDiCookies/italianPrivacyPolicy#13]
Anche in questo caso dalla loro policy (link in fondo) sembra che non profilino, a meno che l'utente non sia loggato nella piattaforma DISQUS, quindi dovrebbe essere classificato come cookie **tecnico**

Testo per la policy

**DISQUS**
Attraverso la piattaforma _DISQUS_ è possibile scrivere commenti personali in calce agli articoli di questo sito (dove permesso). L'uso anonimo della piattaforma non prevede alcun rilascio di cookie di profilazione, ma soltanto cookie di tipo tecnico senza i quali non sarebbe possibile usufruire del servizio di commenti. Il rilascio dei cookie avviene anche se non si commentano articoli. 
Per quanto riguarda la gestione e l'uso dei cookie rilasciati da DISQUS rimandiamo ai link di riferimento del servizio.

**Link di riferimento**
[https://help.disqus.com/customer/portal/articles/466235-use-of-cookies](https://help.disqus.com/customer/portal/articles/466235-use-of-cookies)

**Comment by hmtechnology** [comment]
Mi sembra validissima.

**Comment by Gix075** [comment]
Data la mancanza di tempo **ho dato per buono questo testo** (con le modifiche suggerite) ed ho aggiunto un file nella directory **["docs/md/cookie-policy/services"](https://github.com/FattiDiCookies/italianPrivacyPolicy/tree/master/docs/cookie-policy/md/services). 

Per il momento chiudo l'issue. In caso di cambiamenti da fare è possibile riaprire il ticket.

**Comment by hmtechnology** [comment]
Non sono sicurissimo sia cookie tecnico.

Da un'altra pagina leggo: Cookies Information: Like many websites, when you visit the Service, we may send one or more cookies — a small text file containing a string of alphanumeric characters — to your computer that uniquely identifies your browser and lets Disqus help you log in faster and enhance your navigation through the site. A cookie may also convey information to us about how you use the Service (e.g., the pages you view, the links you click and other actions you take on the Service), and allow us to track your usage of the Service over time. A persistent cookie remains on your hard drive after you close your browser. Persistent cookies may be used by your browser on subsequent visits to the site. Persistent cookies can be removed by following your web browser’s directions. A session cookie is temporary and disappears after you close your browser. You can reset your web browser to refuse all cookies or to indicate when a cookie is being sent. However, some features of the Service may not function properly if the ability to accept cookies is disabled.

https://help.disqus.com/customer/portal/articles/466259-privacy-policy

**Comment by 2autunni** [comment]
scusa @hmtechnology riflettevo sui cookie di terze parti: siamo sicuri di dover / poter indicare quali sono profilanti e quali sono tecnici?
In fondo lo sappiamo solo dalle informative dei servizi, che potrebbero essere fraudolente, incomplete o cambiare nel corso del tempo... 
Inoltre è difficile "da fuori" sapere se un servizio usa un cookie che definisce tecnico per profilare gli utenti e anche il solo sapere che quell'utente è stato sulla nostra pagina web lo aiuta a profilarlo (ma qui siamo più sul versante privacy che cookies )

Ma forse sono ot e di questo dobbiamo discutere nell'altro issue https://github.com/FattiDiCookies/italianPrivacyPolicy/issues/45#issuecomment-107773612

**Comment by hmtechnology** [comment]
Verissimo @2autunni ottima osservazione e ci stavo pensando anch'io. Già è difficile tenere aggiornati i link di riferimento come richiede la normativa perchè essi potrebbero cambiare, figurati sapere se i cookie sono profilanti o tecnici. 

**Come diamine facciamo a sapere se i cookie delle terze parti sono profilanti?Se sono tecnici?Lo saranno sempre nel tempo?**

La verità è che noi non possiamo classificare un cookie come tecnico o profilante, sulla base di cosa? Magari oggi quel servizio non rilascia cookie di profilazione ma solo "tecnici"...e domani ne aggiunge uno che è profilante...mica ci avvisano....c'era chi già lamentava il fatto dell'assurdità di dover segnalare i link di riferimento in fondo ai servizi utilizzati perchè essi potrebbero cambiare nel tempo ed è impossibile tenerli sempre aggiornati....ma questa sui cookie è di fatto, impossibile da tenere sotto controllo.

Disqus, chi può dire con certezza che sia profilante o tecnico? Piwik? Oggi fa statistiche aggregate, se domani introducesse un cookie che fa una, magari anche minimissima, profilazione?

**Comment by 2autunni** [comment]
piwik se è installi la versione OS su un tuo server hai il pieno controllo (puoi anche non fargli settare cookies), se invece usi la versione pro hostata da piwik.pro credo che ugualmente hai la stessa libertà d'azione

**Comment by hmtechnology** [comment]
MMM come possiamo fare:(

**Comment by 2autunni** [comment]
lasciamo stare piwik, scusate se vi ho portato ot, apro altra issue a questo riguardo

**Comment by hmtechnology** [comment]
No no, va benissimo qui e va benissimo piwik!

**Comment by hmtechnology** [comment]
Anche perchè l'indecisione de mettere piwik fra i cookie tecnici o di profilazione o addirittura tra nessuno è simile a Disqus, che sicuramente rilascia cookie ma nn si sa se tecnico o di profilazione

**Comment by hmtechnology** [comment]
uno su FB dice che disqus rilascia cookie di profilazione (doubleclick)

**Comment by iusondemand** [comment]
Vero usa google

**Comment by Gix075** [comment]
Si ma così è una catena infinita, io direi che se loro sul sito dicono di non profilare, a meno che un utente non sia loggato nel loro sistema (mi sembra di aver letto così), che colpa ne abbiamo noi se loro poi si comportano diversamente? Comunque non mi fido molto dei miei pareri legali, quindi mi rimetto a voi.

**Comment by Gix075** [comment]
Chiudo alcune vecchie issue per fare un po' di pulizia e focalizzare sulle nuove. Se serve riaprite.
