### ISSUE TITLE
Condizionale?

### ISSUE THREAD

**Issue by PixedBo** [FattiDiCookies/italianPrivacyPolicy#14]
Potrebbe essere utile utilizzare il condizionale nell'informativa breve e nell'informativa estesa?

Del tipo "questo sito potrebbe fare uso di cookies tecnici e di terze parti"... in modo da poter fare il classico "copia e incolla" di tutta l'informativa su tutti i siti che uno gesteisce senza andare a vedere i servizi usati uno per uno... potrebbe avere senso pratico/legale o meglio evitare?

**Comment by Gix075** [comment]
A livello logico ci sta però non so dal punto di vista legale se va bene. Attendiamo qualche altro parere.

**Comment by LenusMedia** [comment]
Se inserisci il condizionale dai adito alla possibilità che l'utente non
sia informato correttamente ed adeguatamente. Il testo DEVE riportare le
indicazione dei cookie realmente presenti ed essere modificato in maniera
contestuale alle modifiche effettuate sulle pagine.

Puoi includere una dicitura che la policy può subire variazioni senza
preavviso agli utenti i quali sono tenuti a visitarla periodicamente per
rintracciare informazioni aggiornate (...e contattare l'indirizzo /
titolare del trattamento ...).

2015-05-27 12:04 GMT+02:00 Gix075 notifications@github.com:

**Comment by PixedBo** [comment]
Allora facciamo il ragionamento inverso: se scrivo "il sito, a seconda della pagina che stai visitando, rilascia questo questo e questo cookie". Anche se in realtà in alcune pagine (o del tutto) non ne rilascia (per esempio non metto pubblicità su alcune pagine del mio blog).
Può andare bene comunque? Ossia faccio accettare all'utente di ricevere cookie anche se in quel momento (ma magari in futuro si) non vengono rilasciati..
So che è "sporca" come cosa e magari non bellissima a vedersi... ma può andare? Il mio cruccio è scrivere 100 policy diverse per 100 siti diversi...

**Comment by LenusMedia** [comment]
Mi metto nei panni del "Garante", desidero offrire un servizio a tutela del
visitatore e voglio trovare un "inganno" nella tua policy.

Se mi indichi: "il sito utilizza cookies, <cookie policy>" stai informando
l'utente. Dalla normativa si legge:

http://www.garanteprivacy.it/web/guest/home/docweb/-/docweb-display/docweb/3118884

[...] contenente le seguenti indicazioni:

a) che il sito _utilizza cookie di profilazione al fine di inviare messaggi
pubblicitari in linea con le preferenze manifestate dall'utente nell'ambito
della navigazione in rete_;

b) che il sito _consente anche l'invio di cookie "terze parti" (laddove ciò
ovviamente accada)_;

---

Già questo crea l'insufficienza del messaggio di cui sopra.

[...]

c) il link all'informativa estesa, ove vengono fornite indicazioni sull'_uso
dei cookie tecnici e analytics_, _viene data la possibilità di scegliere
quali specifici cookie autorizzare_;

d) l_'indicazione che alla pagina dell'informativa estesa è possibile
negare il consenso all'installazione di qualunque cookie_;

e) l'i_ndicazione che la prosecuzione della navigazione mediante accesso ad
altra area del sito o selezione di un elemento dello stesso_ (ad esempio,
di un'immagine o di un link) _comporta la prestazione del consenso all'uso
dei cookie_.

Continua poi col punto 4.2

_4.2. L'informativa estesa._

L'informativa estesa _deve contenere tutti gli elementi previsti dall'art.
13 del Codice_, _descrivere in maniera specifica e analitica le
caratteristiche e le finalità dei cookie installati dal sito e consentire
all'utente di selezionare/deselezionare i singoli cookie_. Deve essere
raggiungibile mediante un link inserito nell'informativa breve, come pure
attraverso un riferimento su ogni pagina del sito, collocato in calce alla
medesima.

All'interno di tale informativa, deve essere inserito anche il _link
aggiornato alle informative e ai moduli di consenso delle terze parti_ con
le quali l'editore ha stipulato accordi per l'installazione di cookie
tramite il proprio sito. Qualora l'editore abbia contatti indiretti con le
terze parti, dovrà linkare i siti dei soggetti che fanno da intermediari
tra lui e le stesse terze parti. _Non si esclude l'eventualità che tali
collegamenti con le terze parti siano raccolti all'interno di un unico sito
web gestito da un soggetto diverso dall'editore, come nel caso dei
concessionari._

Al fine di mantenere distinta la responsabilità degli editori da quella
delle terze parti in relazione all'informativa resa e al consenso acquisito
per i cookie di queste ultime tramite il proprio sito, si ritiene
necessario che gli editori stessi acquisiscano, già in fase contrattuale, i
suindicati link dalle terze parti (con ciò intendendosi anche gli stessi
concessionari).

Nel medesimo spazio dell'informativa estesa deve essere richiamata la
possibilità per l'utente (alla quale fa riferimento anche l'art. 122, comma
2, del Codice) _di manifestare le proprie opzioni in merito all'uso dei
cookie da parte del sito anche attraverso le impostazioni del browser,
indicando almeno la procedura da eseguire per configurare tali
impostazioni. Qualora, poi, le tecnologie utilizzate dal sito siano
compatibili con la versione del browser utilizzata dall'utente, l'editore
potrà predisporre un collegamento diretto con la sezione del browser
dedicata alle impostazioni stesse_.

Il giorno 27 maggio 2015 12:19, Gianluca Gabella notifications@github.com
ha scritto:

> Allora facciamo il ragionamento inverso: se scrivo "il sito, a seconda
> della pagina che stai visitando, rilascia questo questo e questo cookie".
> Anche se in realtà in alcune pagine (o del tutto) non ne rilascia (per
> esempio non metto pubblicità su alcune pagine del mio blog).
> Può andare bene comunque? Ossia faccio accettare all'utente di ricevere
> cookie anche se in quel momento (ma magari in futuro si) non vengono
> rilasciati..
> So che è "sporca" come cosa e magari non bellissima a vedersi... ma può
> andare? Il mio cruccio è scrivere 100 policy diverse per 100 siti diversi...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FattiDiCookies/italianPrivacyPolicy/issues/14#issuecomment-105854150
> .

## 

Emanuele Pisapia
_Lenus Media_ | proud to communicate.

Desideri lasciare una recensione? Leave a feedback on:
/facebook.com/LenusMedia https://www.facebook.com/LenusMedia

**Comment by hmtechnology** [comment]
Secondo me è perfetta quella esistente, a cui aggiungerei una cosa.

Quella esistente è:
"Questo sito fa uso di cookies (anche di terze parti) per offrirti una migliore esperienza di navigazione. Continuando la navigazione dichiari di accettarne l'uso. Se vuoi saperne di più ti invitiamo a leggere la nostra cookie policy. +Leggi Policy - Accetto"

Io propongo:
"Questo sito fa uso di cookies tecnici. Tramite il sito sono installati cookie di profilazione (esclusivamente di terze parti) per offrirti una migliore esperienza di navigazione in linea con le tue preferenze. Continuando la navigazione dichiari di accettarne l'uso. Se vuoi saperne di più ti invitiamo a leggere la nostra cookie policy. +Leggi Policy - Accetto"

**Comment by iusondemand** [comment]
@hmtechnology devo dire cosa faccio. Non e' detto che lo faccia sempre, ma e' l'informativa breve comune a tutte le pagine. Nell'informativa estesa dovrei spiegare dove lo uso e dove non lo uso, o almeno perche' lo uso che probabilmente assorbe la domanda

**Comment by Gix075** [comment]
Chiudo per vecchiaia della issue, se serve riapriamo.
