### ISSUE TITLE
informativa breve

### ISSUE THREAD

**Issue by iusondemand** [FattiDiCookies/italianPrivacyPolicy#15]
Ho iniziato a lavorare sull'informativa breve.

Vi prego di perdonare il modo in cui ho inviato le mie 4 proposte, non sono ancora abituato a git.

In breve ho previsto:
1. sito senza cookie propri ne' di terzi
2. sito senza cookie propri ma con cookie di terzi
3. sito con cookie tecnici propri e senza cookie di terzi
4. sito con cookie tecnici e di profilazioni propri e con cookie di terzi.

sotto con le proposte :) e' solo una bozza

**Il file in questione è stato spostato [QUI](https://github.com/FattiDiCookies/italianPrivacyPolicy/blob/master/bozze/cookie-policy_breve/cookie-informativa-breve-it.md)**

**Comment by hmtechnology** [comment]
manca la situazione di sito con cookie tecnici propri (ma non di profilazione) e con cookie di terze parti (tecnici e/o di profilazione)

**Comment by Gix075** [comment]
Ad eccezione di quello che ha richiesto @hmtechnology, mi sembra che le altre siano ok e che possano direttamente essere date per buone. 

Aspettiamo comunque la replica di @iusondemand

**Comment by hmtechnology** [comment]
c'è molta confusione qui https://github.com/FattiDiCookies/italianPrivacyPolicy/blob/master/cookie-informativa-breve-it.md

**Comment by hmtechnology** [comment]
Secondo me bisognerebbe distinguere solo questi scenari:
1. Sito senza cookie
2. Sito con cookie tecnici (proprietari e/o terze parti)
3. Sito con cookie tecnici (proprietari e/o terze parti) e cookie di profilazione (proprietari e/o terze parti)

Poi vabbè sito senza cookie tecnici ma con cookie di profilazione, ma rientra nel punto 3 direi

**Comment by Gix075** [comment]
Anche secondo me la questione degli embed potrebbe essere estromessa, però non sono certo della problematica legale. 
Per ora nel tool ho tolto la profilazione in prima persona perché esula dagli scopi di questo progetto. 

Anche per il tool sarebbe meglio semplificare. I tuoi tre casi, con magari l'aggiunta dell'ultimo sarebbero più comodi da gestire. Tanto poi la maggior parte delle persone per andare sul sicuro sceglierà il terzo scenario.

**Comment by 2autunni** [comment]
domanda scema, di quelle che ora mi cacciate ;) , ma i cookie analytics li facciamo rientrare nei tecnici?
@Gix075 in che senso estrometteresti gli embed?

**Comment by Gix075** [comment]
@2autunni perché come diceva @hmtechnology la legge parla di cookie, quindi come arrivano arrivano. Perché si deve specificare che il sito usa embed? Il fatto è che non so se questa cosa rientra però nella legge, altrimenti perché chi ha scritto i testi l'avrebbe inserita?

Il tutto è per semplificare la cosa, anche per gli utenti.

**Comment by hmtechnology** [comment]
Sono pressochè sicuro che non si debba indicare che sono embed, ma solo che sono di terze parti. Poi se è uno <script>, un embed o addirittura un immagine non cambia niente.

**Comment by hmtechnology** [comment]
@iusondemand spero di non offenderti se metto momentaneamente qui il contenuto delle tue informative brevi. Ho rifatto le varie casistiche, tolto il termine embed e aggiunto dei dettagli in questo [documento](https://github.com/FattiDiCookies/italianPrivacyPolicy/blob/master/docs/cookie-policy/md/informativa-breve.md)

###Sito senza cookies e senza embed
Non ci sono cookies, nessuna informativa e' dovuta.

###Sito con soli cookies tecnici
L'informativa deve esserci indicando dati e finalita' del trattamento ma puo' essere messa anche solo nella privacy policy, senza bisogno di banner o informativa estesa (v. faq 13 del garante)

###Sito senza cookies tecnici ma con embed
Il sito non usa cookies propri, ma utilizza embed di terze parti. Nell'informativa estesa sono disponibili i link alle terze parti ove negare i cookies dei terzi che possono profilare se attivati dall'utente sul sito del terzo. Procedendo nella navigazione o cliccando su ok si acconsente all'uso dei cookie.

###Sito con cookies tecnici ma con embed
Il sito usa cookies tecnici ma non profila i propri visitatori, ma utilizza embed di terze parti. Nell'informativa estesa sono disponibili i link alle terze parti ove negare i cookies dei terzi che possono profilare se attivati dall'utente sul sito del terzo. Procedendo nella navigazione o cliccando su ok si acconsente all'uso dei cookie.

###Sito con profilazione in prima parte e/o tramite terze parti
Il sito usa cookies tecnici e di profilazione in prima parte e tramite terze parti, e utilizza anche embed di terze parti. Nell'informativa estesa sono disponibili i nostri cookies e link alle terze parti ove negare i cookies dei terzi che possono profilare se attivati dall'utente sul sito del terzo. Procedendo nella navigazione o cliccando su ok si accetta l'invio dei cookies.

**Comment by iusondemand** [comment]
Ciao, nessuna offesa, anzi ! E' maledettamente stimolante !

Guardo il tuo documento che hai linkato sopra:

1) sito senza cookie ok

2) sito con cookie tecnici: non si applica solo l'art.13 ma anche l'informativa estesa che va linkata in fondo ad ogni pagina. Ok, puo' essere assorbita nella privacy policy. no a quanto messo in parentesi. ergo finale: "Questo sito fa uso esclusivamente di cookie tecnici  per permetterne il corretto funzionamento." che pero' non e' necessario mettere in informativa breve. PRoprio l'informativa breve non e' necessaria, il link in ogni pagina si'.

3) cito e commento in maiuscolo, mi faccio schifo a non sapere usare github meglio :-):

Per i cookie tecnici come sopra (OK), per i cookie di profilazione è richiesto consenso preventivo (indecisione sulle terze parti METTI LA COSA SICURA: QUELLI DI PRIMA PARTE E' RICHIESTO IL CONSENSO PREVENTIVO, IO POI PER QUELLI DI TERZA SONO PER LA SOLA INFORMATIVA ESTESA E RICHIAMO IN QUELLA BREVE) e l'informativa (in forma breve=banner, al momento dell'accesso al sito, e in forma estesa, linkabile dall'informativa breve e da ogni pagina del sito, idealmente nel footer). Solo se i cookie di profilazioni sono proprietari(GIUSTO MA INVECE DI PROPRIETARI  USEREI PRIMA PARTE CHE DISTINGUE BENE DA TERZA PARTE) è necessaria la notifica telematica al Garante

Questo sito fa uso di PROPRI cookie tecnici E DI profilazione E DI terze parti per mostrare contenuti pubblicitari in linea con le tue preferenze. Se vuoi saperne di più ti invitiamo a leggere l'informativa estesa, dove potrai negare il consenso all'installazione DEI cookie (NOTA: IN TEORIA SERVE SOLO PER I PROFILANTI, MA IO FACCIO CANCELLARE ANCHE QUELLI TECNICI)). Cliccando su OK o proseguendo la navigazione (scroll o clic SULLA PAGINA) acconsenti all'uso dei cookie. [OK].

ALTRA NOTA: HO VISTO INFORMATIVE ANCORA PIU' BREVI, MAGARI UN DOMANI SI CAMBIA

4) D'ACCORDO.

scusate ancora l'uso del maiuscolo, ....

**Comment by iusondemand** [comment]
sbaglio o per ogni modifica dei testi legali dovremmo fare:

1) fork
2) modifica testo
3) commit testo indicando le ragioni del cambiamento ?
4) da amministratori il commit sarebbe definitivo o dovremmo autorizzarcelo da qualche altra parte ?

**Comment by iusondemand** [comment]
il testo finale che propongo della terza ipotesi lo metto qui per semplicita' di lettura:

"Questo sito fa uso di cookie tecnici e di  profilazione propri e di terze parti parti per migliorare la navigazione e mostrare contenuti pubblicitari in linea con le tue preferenze. Se vuoi saperne di più ti invitiamo a leggere l'informativa estesa, dove potrai dare e negare il consenso all'installazione dei cookie di profilazione. Cliccando su OK o proseguendo la navigazione (scroll o clic sulla pagina) acconsenti all'uso dei cookie."

**Comment by iusondemand** [comment]
Sempre per la terza ipotesi avevo visto questo: "Questo sito usa i cookie (anche di terze parti), per fornirti una migliore esperienza di navigazione. Continuando a navigare ne accetti l'utilizzo.privacyaccetta" che pero' mi smebra riesca a tenere tutto. Non ricordo dove l'ho trovata, quindi va elaborata

**Comment by 2autunni** [comment]
Buongiorno @iusondemand 

> sbaglio o per ogni modifica dei testi legali dovremmo fare:
> 1) fork
> 2) modifica testo
> 3) commit testo indicando le ragioni del cambiamento ?
> 4) da amministratori il commit sarebbe definitivo o dovremmo autorizzarcelo da qualche altra parte ?

Il fork non serve a meno che tu non faccia modifiche radicali (es cambiare tutta la struttura delle directory)
E anche il quel caso più che fare un fork (che apre un altro repository) sarebbe meglio aprire un nuovo ramo (che rimane in questo stesso repository)

Per il momento mi sembra che la pratica si sia stabilizzata in 
1. Discutiamo nelle issues 
2. quando c' è abbastanza consenso facciamo la modifica 
3. facciamo il commit spiegando la modifica 
   se modifichi online da github il passo 2 e 3 sono effetuati insieme
   se nel testo del commit inserisci #numeroissue il link al commit appare nella issue 

Il commit è immediatamente visibile a tutti, però git tiene lo storico e possiamo in ogni momento vedere le differenze e ripristinare una vecchia versione.
Tieni presente che prima di modificare i file (se lavori in locale) dovresti eseguire un git pull per essere sicuro di lavorare sull'ultima versione
@Gix075 dimmi se è corretto quanto ho scritto

**Comment by iusondemand** [comment]
Grazie @2autunni @Gix075 avevo dimenticato il semplice ramo...

Trovo difficile seguire gli issue e legarli ai files: esiste una soluzione ? Con giteye per linux per esempio non trovo gli issues... Grazie, in ogni caso continuo come abbiamo fatto ora fino a vostra diversa indicazione

**Comment by Gix075** [comment]
Entro in merito alla discussione prima dal lato GitHub: @2autunni ha spiegato egregiamente il funzionamento di githtub e come lo abbiamo usato fino ad ora. Purtroppo questo strumento è ovviamente più adatto al codice che a dei lunghi testi (in quanto a comodità di pull, push, merge,ecc...). Credo che in fatto di comodità, usare le issue o altri sistemi più meno sia uguale. 

Per quanto riguarda invece la questione dei testi, premesso che eliminerei del tutto la casistica della profilazione in prima persona perché la vedo fuori da un progetto come il nostro (almeno in prima battuta), direi che per me le casistiche sono le seguenti.

1) Niente cookie = Niente Banner (informativa breve) + Niente Informativa
2) Solo cookie tecnici = Niente Banner + Informativa estesa (possibile inserimento solo nella privacy policy)
3) Niente cookie tecnici + cookie di profilazione di terzi
4) Cookie tecnici + cookie di profilazione di terzi

Quindi se non erro nei casi 1 e 2 noi non dobbiamo produrre testo per l'informativa breve, ma solo per i casi 3 e 4, giusto?

**Comment by 2autunni** [comment]
nel caso 2 io il banner lo visualizzerei ugualmente per evitare lo scenario:
- l'utente si  collega al mio sito
- vede che ci sono cookie e niente banner 
- l'utente mi scrive  "Lo sai che setti i cookies e non hai il banner: manigoldo! ora ti denuncio al garante"
  ecc. ecc.

Diciamo che lo farei per far stare tranquilli i nostri utenti, o al limite si può dare come opzione facoltativa a chi installa il plugin?

**Comment by Gix075** [comment]
Si si può fare anche perché in configurazione ci sono al momento tre parametri boolean, cookie tecnici, cookie di profilazione, embed. Quindi ridurli a due non è un problema. Direi che quindi dal mio punto di vista possiamo mantenere tre info brevi:
1. solo cookie tecnici
2. solo cookie di profilazione di terzi
3. tecnici e profilazione

**Comment by hmtechnology** [comment]
Allora rispondo in ordine inverso, non me ne voglia nessuno!

@Gix075: il tuo caso 2 e 3 sono pressochè identici dal punto di vista concettuale. Il fatto che non vi siano cookie tecnici implica solo che essi non verranno (ovviamente) inseriti nell'informazione estesa (non essendoci), ma tutto il resto è identico.

@2autunni Sì esatto, nel mio caso 2 infatti, anche se non è espressamente richiesto, ho inserito ugualmente l'informativa breve: "Questo sito fa uso esclusivamente di cookie tecnici {[anche di terze parti]} per permetterne il corretto funzionamento."

@iusondemand grande:) scusa ancora per lo spostamento, ho compreso bene ;) Ti rispondo nel merito.

1) sito senza cookie ok
OK:)

2) Mi riporti dove il Garante dice che nel caso di cookie esclusivamente tecnici è necessaria l'informativa estesa? E che la stessa vada linkata da ogni pagina del sito?

La mia interpretazione è che ovviamente sia meglio fare l'informativa estesa per stare sicuri (e anche eventuale link da ogni pagina), ma l'unico riferimento che fa il Garante sui cooki tecnici è: "Per l'installazione di tali cookie non è richiesto il preventivo consenso degli utenti, mentre resta fermo l'obbligo di dare l'informativa ai sensi dell'art. 13 del Codice, che il gestore del sito, qualora utilizzi soltanto tali dispositivi, potrà fornire con le modalità che ritiene più idonee."

Dunque, le modalità che io reputo idonee sono proprio l'informativa breve, che non è necessaria assolutamente in senso stretto, ma ricordiamo, è sempre un VALORE AGGIUNTO se si comprende lo spirito della normativa (l'utente deve farsi un'idea abbastanza completo GIA' dal banner). Ma niente e nessuno vieta di fare anche un'informativa estesa, anzi direi proprio che è da prevedere (seppur non vi sia apparentemente nessuna richiesta esplicita del Garante)

Perchè no alla frase fra parentesi ? L'ho messa solo nel caso il sito faccia uso di cookie di terze parti (sempre analitici), che poi è la situazione più comune (vedi uso di shinystat, analytics anonimo, piwik, etc)

3) Concordo sull'uso di "prime parti" al posto di "proprietari" e sull'interpretazione in senso largo della normativa (NO BLOCCO su cookie di terze parti). I cookie tecnici, secondo me, non vanno fatti cancellare (pena il non funzionamento corretto del sito) anche se il Garante parla di "negare il consenso all'installazione di qualunque cookie". E' evidente si parli dei cookie di profilazione (mia interpretazione) perche quelli tecnici li considera essenziali al sito e nessuno farebbe cancellare dei cookie che comportano il collasso di un sito. Cmq se si può dare la possibilità di cancellare anch'essi senza conseguenze negative per il sito, ben venga (ma allora non sarebbero tecnici xD poichè il garante li considera un pò come "essenziali" per il funzionamento del sito).

Si, l'informativa breve può essere anche più breve ma io la reputo la cosa più importante della normativa. Deve necessariamente contenere alcuni elementi quindi se vogliamo attenerci letteralmente, può essere che non sia proprio solo una riga o due. Ovviamente se riusciamo a renderla più snella inserendo tutti gli elementi (come tuo ultimo esempio), sarebbe ancora meglio.

4) OK

Correggo e integro i tuoi spunti nel documento :) https://github.com/FattiDiCookies/italianPrivacyPolicy/blob/master/docs/cookie-policy/md/informativa-breve.md

**Comment by 2autunni** [comment]
> 2) Mi riporti dove il Garante dice che nel caso di cookie esclusivamente tecnici è necessaria l'informativa estesa? E che la stessa vada linkata da ogni pagina del sito?
> qui 
> http://www.garanteprivacy.it/web/guest/home/docweb/-/docweb-display/docweb/3118884
> dice 
> 4.2. L'informativa estesa.
> 
> L'informativa estesa deve contenere tutti gli elementi previsti dall'art. 13 del Codice, descrivere in maniera specifica e analitica le caratteristiche e le finalità dei cookie installati dal sito e consentire all'utente di selezionare/deselezionare i singoli cookie. Deve essere raggiungibile mediante un link inserito nell'informativa breve, come pure attraverso un riferimento su ogni pagina del sito, collocato in calce alla medesima.

però non so se c'entri con la domanda 

che poi spiegalo al garante che ci sono siti a scroll infinito per cui puoi mettere tutto quello che vuoi nel footer ;-)

**Comment by hmtechnology** [comment]
Si ma parla dell'informativa estesa, che, ove presente, va linkata ovunque, mica si sta parlando del caso di solo cookie tecnici. Non a caso l'intero punto 4 (da cui deriva il 4.2. informativa estesa che hai postato) fa riferimento ai cookie profilanti

**Comment by 2autunni** [comment]
@hmtechnology scusa, sono un po' bollito dopo giorni dietro a sta storia

**Comment by hmtechnology** [comment]
a chi lo dici:) Posto un articolo che ho trovato su G+ abb interessante per me

Più si avvicina la scadenza del 2 giugno 2015 più leggo tutto e il contrario di tutto circa la #cookielaw  . 
Capisco la necessità di comprendere le direttive del Garante della Privacy per poi trasformarle in questioni tecniche e pratiche, però si sta rapidamente scendendo nella paranoia. Davvero.

1) In molti si arrovellano perché il testo del provvedimento 229/2014 indica una cosa e poi le famigerate "FAQ del Garante" sembrano contraddire il provvedimento stesso (creando una confusione immane).
Forse non sono stato abbastanza chiaro e ribadisco il concetto: attenetevi SOLO al testo del provvedimento. La differenza fra il provvedimento e le FAQ (o le telefonate dirette all'Autorità) sta in un piccolo ma importantissimo dettaglio: il provvedimento è stato pubblicato in Gazzetta Ufficiale ed ha acquistato forza di legge mentre tutto il resto ha sicuramente un valore giuridico inferiore e, comunque, presta il fianco a facilissime contestazioni in caso di controversia. In parole povere: il provvedimento è la legge. Non altro.

2) L'informativa estesa potrà essere lunga anche chilometri ma l'informativa "breve" sarà quella che col tempo diventerà la forma di comunicazione principale. Lo sappiamo tutti come funziona: si installa un'applicazione e si clicca OK (o Avanti) senza fermarsi a leggere quei lunghi documenti in legalese, i quali, però, dopo l'accettazione vincolano con la medesima forza di un contratto. Il mio consiglio è quello di non scervellarsi a trovare il metodo migliore per propinare tutta l'informativa estesa al visitatore; piuttosto dedicate maggior tempo all'informativa breve e indicate maggiori dettagli già in quella: la prosecuzione della navigazione per il Garante equivale all'accettazione della cookie policy, quindi il "problema" sarà solo e semplicemente del visitatore che ha manifestato (più o meno sbadatamente) il consenso ai cookies.

3) Avete l'onere di notificare al Garante la profilazione solo se la fate in house con cookie generati direttamente dal vostro sito. Per la profilazione condotta da terze parti basta darne notizia nell'informativa e rimandare alla privacy policy del servizio di terze parti che la effettua.

4) La profilazione secondo il Garante è la raccolta di dati non anonima per l'individuazione di gusti, preferenze, abitudini al fine di creare messaggi pubblicitari personalizzati: parecchi servizi per il monitoraggio riescono a raccogliere gli stessi dati anche in forma anonima (cioé senza salvare l'indirizzo IP o la posizione geografica): stando così le cose, in teoria quei servizi potrebbero anche essere assimilati ai cookie tecnici e perciò sfuggire all'obbligo di menzione in informativa estesa.Valutate bene i servizi che andrete ad utilizzare e ricordate che per il Garante la profilazione ha come obiettivo la comunicazione commerciale mirata (leggasi provvedimento del 19 marzo 2015, in vigore dal 6 maggio 2015 con pubblicazione in G.U.)

5) Il 2 giugno è sì la scadenza ma ciò non significa che il 3 giugno sarete sanzionati in caso di mancato adeguamento. D'altronde è lo stesso Garante a comprendere l'impatto della #cookielaw  . La raccomandazione, però, è che in una settimana riusciate almeno ad esporre l'informativa breve e - ove necessario - una bozza di informativa estesa.

**Comment by iusondemand** [comment]
Tutti interventi fantastici. Ora mi prendo un giorno di pausa poi .... sotto :-)

**Comment by hmtechnology** [comment]
@iusondemand :) 

Stavo rivedendo la tua frase: "Questo sito fa uso di cookie tecnici e di profilazione propri e di terze parti parti per migliorare la navigazione e mostrare contenuti pubblicitari in linea con le tue preferenze. 

Io continuo a preferire questa:
Questo sito fa uso di cookie tecnici; tramite il sito sono installati cookie di profilazione (esclusivamente di terze parti) {[sia di prime parti che di terze parti]} per mostrare contenuti pubblicitari in linea con le tue preferenze. 

E ti dico perchè, parliamone e poi integriamo;) Nella tua frase risulta impossibile distinguere quali sono i cookie di terze parti (se tecnici o di profilazione), idem quelli proprietari. Non cambia nulla per i cookie tecnici (se di prime parti o di terze), ma cambia per i cookie di profilazione perchè lascerebbe intendere (senza poter districarsi bene) che si usano anche i cookie di profilazione diretta (di prime parti). OK che nessun visitatore andrà a verificare se hai notificato al Garante qualcosa (come richiedono i cookie profilanti di prime parti), però preferirei qualcosa di più limpido. Dire "esclusivamente di terze parti", che è il 99% dei casi dei cookie di profilazione, ci pone immediatamente in un'altra situazione "giuridica", molto più soft. Non so se ho reso l'idea :p

**Comment by hmtechnology** [comment]
Questo il banner proposto dal [kit pdf](http://andrea.s3.iubenda.com/gkHRyw3pg6/GUIDA-COOKIES.pdf):

> Questo sito utilizza cookie per inviarti pubblicità e servizi in linea con le tue
> preferenze. Se vuoi saperne di più o negare il consenso a tutti o ad alcuni
> cookie clicca qui. Chiudendo questo banner, scorrendo questa pagina
> o cliccando qualunque suo elemento acconsenti all’uso dei cookie.

**Comment by 2autunni** [comment]
Per i siti con solo cookies tecnici, una strada potrebbe anche essere quella  di fare come il garante stesso: niente banner e nella privacy policy informazioni sul modo id usare i cookies da parte del sito
http://www.garanteprivacy.it/web/guest/home/docweb/-/docweb-display/docweb/36573

**Comment by Gix075** [comment]
@2autunni @hmtechnology @iusondemand, i testi che sono adesso nella cartella docs li devo considerare buoni o no?

Chiedo per il tool, soprattutto vorrei sapere se almeno le casistiche sono definitive.

**Comment by iusondemand** [comment]
Li riguardo oggi, le osservazioni mi sembrano giuste. Forse dovrei fare un censimento di informative brevi e capire il perche di ogni soluzione. Ed anche una checklist come abevo fatto per l'estesa.
