### ISSUE TITLE
Informativa estesa e disabilitare i cookie

### ISSUE THREAD

**Issue by lidialab** [FattiDiCookies/italianPrivacyPolicy#17]
Ciao a tutti, 
in merito alla policy estesa, dopo l'ennesima rilettura dell'ormai noto documento 3118884, vorrei proporre una mia riflessione di oggi sulla sezione riguardante la disabilitazione dei cookie, in quanto secondo me il garante ([doc. web n. 3118884] punto 4.2, e rif. codice privacy art 122 comma 2) vuole che sia indicato come trattare i cookie del sito che si sta visitando e quindi dove possibile (Ie, FF, ...) indicare come farlo per quel sito e non per i cookie in generale.

Per esempio per Internet Explorer (per il quale riterrei idoneo fare riferimento all'ultima versione (11) e spiegare semmai dove trovare le istruzioni per le altre versioni) una bozza potrebbe essere:
# 

Internet Explorer 
In riferimento alla più recente versione 11 

Eseguire il Browser Internet Explorer

Se si sta eseguendo Internet Explorer nella versione App cliccare sull'icona a forma di chiave inglese "Strumenti Pagina" in basso a destra, 
cliccare "Opzioni" 
scegliere "Visualizza nel desktop"

altrimenti proseguire con le seguenti istruzioni.

Fare clic sul pulsante "Strumenti" (icona a forma di ingranaggio in alto a destra), oppure sul menù "Strumenti", oppure premere ALT + X 
Scegliere la voce "Opzioni Internet"

Si apre la finestra "Opzioni Internet"

Fare clic sulla scheda "Privacy";
premere il bottone "Siti" (il bottone non è disponibile nel caso si sia impostato di accettare sempre o bloccare sempre tutti i cookie);
nel campo "Indirizzo sito Web" scrivere miosito.xxx e premere "Blocca" per bloccarne sempre i cookie o "Consenti" per consentirne sempre i cookie;
il sito comparirà nell'elenco "Siti Web gestiti" , 
premere "OK".

Questa impostazione non influisce sui cookie di terze parti.

Al termine cliccare "Applica" e poi "OK"
# 

IMHO

Lo so...

**Comment by lidialab** [comment]
Ne approfitto per segnalare che è preferibile usare clic senza k (refuso da traduzione?) mentre invece è ancora ampiamente dibatutto nel mondo delle traduzioni da inglese a italiano se usare "cliccare" o "fare clic su".

**Comment by hmtechnology** [comment]
Ottime osservazioni!

**Comment by vannaccirere** [comment]
sparita la pagine cookie policy

**Comment by Gix075** [comment]
Mi scuso con voi ma dato che sono state aperte molte issue sulla cookie policy per non perderci pezzi importanti e per evitare confusioni, chiudo questa issue e invito a spostare eventuali discussioni in merito, magari segnalando ancora i problemi se non sono stati risolti [QUI](https://github.com/FattiDiCookies/italianPrivacyPolicy/issues/23)

Riaprire quesra discussione (magari segnalandola nell'altra) in caso di necessità.
