### ISSUE TITLE
Privacy Policy e il titolare del trattamento dei dati

### ISSUE THREAD

**Issue by lidialab** [FattiDiCookies/italianPrivacyPolicy#18]
Ciao a tutti,
nella privacy policy riterrei giusto far riferimento in primo luogo al "titolare" e solo dopo ai "responsabili" da lui designati;

sarebbero da integrare (art 13 del codice)
- la natura obbligatoria o facoltativa del conferimento dei dati
- le conseguenze di un eventuale rifiuto di rispondere

questa frase secondo me è pericolosa:
invio di future proposte commerciali legate alla nostra attività; 
compimento di ricerche di mercato e scopi statistici riguardanti la nostra attività

e in ogni caso nei moduli mail o newsletter si deve chiedere esplicitamente il consenso al trattamento per fini commerciali (di solito con una checkbox separata) 

ma questa policy è già open? (es: http://museumperugia.com/privacy-policy.html)

**Comment by hmtechnology** [comment]
ma attualmente dove si fa riferimento ai responsabili?

**Comment by lidialab** [comment]
Ripensandoci non è sbagliato, è più per mia abitudine, mediamente i soggetti con cui ho a che fare io difficilmente hanno designato un responsabile...

Era nella Privacy Policy ITA (v. 0.0.0 alpha) al punto 3 in cui ci si riferisce al responsabile.

Le altre considerazioni le ritengo valide, ma meglio se per oggi stacco, probabilmente sono (bis)cotta.

**Comment by Gix075** [comment]
Per quello che riguarda la responsabilità è stato messo:
- Società responsabile del trattamento
- Responsabile del trattamento 
- Eventuali delegati

Sulle frasi pericolose possiamo ovviamente discuterne. Quella delle proposte commerciali 

_"invio di future proposte commerciali legate alla nostra attività"_

voleva mettere al riparo (la scrissi per un ristorante) da scenari come: l'utente invia un messaggio con scritto "hai la pasta alle vongole?" e il titolare del ristorante risponde "No, ma se vuoi ho la pasta con le cozze a metà prezzo, 5€ invece che 10€".
Non intende ovviamente coprire scenari come quello di una newsletter di offerte e la scrissi su consiglio del legale del locale per cui veniva redatta. Forse può tranquillamente essere cancellata o modificata. Ditemi voi quello che pensate.

Per quello che riguarda le statistiche ad uso interno, 

_"compimento di ricerche di mercato e scopi statistici riguardanti la nostra attività"_

per quello che so sono considerate statistiche anche il suddividere le mail di contatto per mesi, o contare quanti uomini piuttosto che donne si sono iscritti al sito e queste pratiche devono essere dichiarate come scopo della raccolta dati (ovviamente per quello che ne so io). Anche in questo caso discutiamone insieme.

**Comment by hmtechnology** [comment]
Responsabile del trattamento dei dati personali si riferisce al Titolare del sito, che è appunto Titolare e Responsabile. Credo.

"invio di future proposte commerciali legate alla nostra attività" dovrebbe essere nel modulo "Mailchimp" ad esempio, quindi per i servizi integrati, non nella privacy "base"

"compimento di ricerche di mercato e scopi statistici riguardanti la nostra attività" invece non credo ci siano problemi

**Comment by Gix075** [comment]
Io ho redatto il testo seguendo quello che è scritto nella norma 
[http://www.garanteprivacy.it/web/guest/home/docweb/-/docweb-display/docweb/1311248](http://www.garanteprivacy.it/web/guest/home/docweb/-/docweb-display/docweb/1311248)
all'articolo 13 e rifacendomi anche ad altre parti della legge, che ovviamente riguarda la privacy in generale e non solo siti web. 

Addirittura io non credo che sia necessario in questo testo riportare i servizi nel dettaglio, va elencato il modo di raccolta (modulo di contatto, newsletter, registrazione al sito, ecc...) e riportare un elenco dei dati che vengono raccolti (nome, cognome, email, ecc...)

Ovviamente poi noi possiamo fare una cosa più dettagliata e inserire un elenco in stile cookie policy, che sicuramente male non fa.

**Comment by Gix075** [comment]
@lidialab e agli altri, ho apportato delle modifiche alle parti segnalate in questa issue, dategli un'occhiata e ditemi cosa ne pensate.

**Comment by lidialab** [comment]
Letto.
Responsabile - ok - ho capito il ragionamento che mi sembra anche giusto, diciamo che io nel caso ci sia solo il titolare metterei la dicitura "titolare" o "titolare e responsabile" per rispondere letteralmente a questo (art 13-1-f) "gli estremi identificativi del titolare e, se designati, del rappresentante nel territorio dello Stato ai sensi dell'articolo 5 e del responsabile." e perchè nella mia testa mi chiedo sempre chi sia in ultimo il titolare, ma è solo per speigarti perchè la penso così

frasi sugli usi commerciali e statistici - ok - qui sei più avanti tu visto che hai già chiesto consulenze da tempo, grazie per le info

i due punti integrati sul consenso - ok

**Comment by iusondemand** [comment]
Resp e ritilare nelle piccole strutture coincidono. In effetti avevo letto che va indicaro il titolare ma per questa parte collego la cookie policy alla privacy policy

**Comment by Gix075** [comment]
Alla fine, nel tool di configurazione ho reso dinamici i parametri riguardanti la parte degli scopi, quindi ognuno è libero di regolarsi come vuole ed in più sono comunque casi diversi da sito a sito, quindi mi sembrava giusto dargli una forma dinamica.

**Comment by hmtechnology** [comment]
aggiungerei fra i purposes: “Invio di Campagne DEM e di Newsletter informative e pubblicitarie del portale” (per chi utilizza servizi tipo Mailchimp)

**Comment by Gix075** [comment]
Intanto inserisco questa frase nel file di configurazione del tool ma, dato che queste parti sono dinamiche e per il momento è l'utente a doverle inserire a mano, direi di pensare ad un file con vari esempi di scopi che può prendere e incollare nel file di config.

**Comment by hmtechnology** [comment]
ancora meglio;)

Le elenchiamo:

"instaurare una comunicazione richiesta dall’utente al fine di poter godere appieno dei servizi offerti dalla nostra attività e rispondere ai messaggi (email, fax) inviati dagli stessi",
"invio di future proposte commerciali legate alla nostra attività",
"compimento di ricerche di mercato e scopi statistici riguardanti la nostra attività"
 “invio di campagne DEM e di newsletter informative e pubblicitarie riguardanti la nostra attività”

**Comment by Gix075** [comment]
Chiudo per vecchiaia della issue, se serve riapriamo.
