### ISSUE TITLE
Privacy Policy - Trattamento dati

### ISSUE THREAD

**Issue by Gix075** [FattiDiCookies/italianPrivacyPolicy#19]
@iusondemand @akybaud @PixedBo @lmbuffetti @andreaperugia @FattiDiCookies/writers @FattiDiCookies/developers @FattiDiCookies/owners @hmtechnology @seosmart @vannaccirere @Saladino79 @LenusMedia @lidialab e tutti gli altri

Il file [privacy-policy-it.md](https://github.com/FattiDiCookies/italianPrivacyPolicy/blob/master/privacy-policy-it.md) è il file proposto inizialmente e su cui con alcuni abbiamo lavorato, discusso, corretto e integrato. Ovviamente può essere migliorato ancora, ma dobbiamo stringere i tempi. 
Chiedo quindi a tutti di dargli un'occhiata e contribuire. Vorrei chiuderla entro giovedì massimo venerdì.

@andreaperugia ha postato una bozza (che trovate [QUI](https://github.com/FattiDiCookies/italianPrivacyPolicy/blob/master/bozze/privacy-policy/esempio1-privacypoliy)) e magari potrebbe indicare se ci sono cambiamenti da fare o integrazione seguendo anche la sua bozza.

**Comment by hmtechnology** [comment]
Il file privacy-policy-it.md a cui si fa riferimento è stato spostato qui (non da me!) https://github.com/FattiDiCookies/italianPrivacyPolicy/blob/master/docs/privacy-policy/md/privacy-policy.md

**Comment by Gix075** [comment]
Sono stato io. Ho solo tolto il testo dal primo per non creare confusione. La posizione corretta è quella attuale.

**Comment by Gix075** [comment]
Per eliminare issue duplicate, chiudo questa spostando la discussione [QUI](https://github.com/FattiDiCookies/italianPrivacyPolicy/issues/18) dove siamo un po' più avanti con il discorso
