### ISSUE TITLE
Gruppi di sviluppo

### ISSUE THREAD

**Issue by Gix075** [FattiDiCookies/italianPrivacyPolicy#2]
Direi che in base alle capacità e/o interessi dovremmo dividerci in gruppi di lavoro.
Avrei pensato ad una struttura del tipo:
- **Admins** amministratori del progetto
- **Developers** sviluppatori di eventuale codice da inserire nel progetto
- **Writers** coloro che si occupano di scrivere la parte "legale" del progetto

Che ne dite?

**Comment by hmtechnology** [comment]
pienamente d'accordo!

**Comment by ghost** [comment]
d'accordo al 100%, se avete notato, c'è uno script sotto licenza gnu che 
ho postato sulla pagina, sembra bloccare i cookie

**Comment by ghost** [comment]
Io sono più legato alla parte legale

**Comment by Gix075** [comment]
Ok, io allora apro delle milestone per fissare gli step che dobbiamo attraversare per portare a termine il progetto. Ovviamente possiamo usare anche le ISSUE per proporre o discutere di ogni cosa. Sentitevi liberi di aprirne quanti volete. Io da questa sera tornerò a pieno regime e potrò star dietro al progetto in maniera più costante.

**Comment by seosmart** [comment]
Gix075 aspetto te riguardo a come procedere sulla parte dei moduli di opt out (ovvero come e dove inserirli in github).

**Comment by Gix075** [comment]
Intanto direi che forse sarebbe meglio aprire una issue di volta in volta, riportare la parte di testo che si intende aggiungere, verificarla insieme e poi la inseriamo nel repository. Se sei pratico di GitHub la committi direttamente tu, altrimenti ci pensa qualcuno del team.

**Comment by akybaud** [comment]
nella policy, nella sezione relativa alla disabilitazione dei cookie, non sarebbe meglio mettere solo i link ai siti dei vari browser invece che inserire le istruzioni direttamente nella policy? MI sembra che così sarebbe più leggera, e soprattutto in questo modo non si è costretti ad inserire le istruzioni per le varie release dei browser (che già solo per IE c'è da diventare scemi)

**Comment by akybaud** [comment]
ghost che è più legato alla parte legale ha qualche indicazione in merito per sapere se è sufficiente?

**Comment by Gix075** [comment]
Chiudo alcune vecchie issue per fare un po' di pulizia e focalizzare sulle nuove. Se serve riaprite.
