### ISSUE TITLE
Javascript per l'informativa breve

### ISSUE THREAD

**Issue by iusondemand** [FattiDiCookies/italianPrivacyPolicy#20]
Ho guardato su git tanti javascript per dare l'informativa breve. Ho provato cookiechoises e mi sembra primordiale, imponendo una attenzione che il Garante non chiede, e che nessuno usa oggi.

Quindi ho trovato un progetto che ho forkato  e modificato secondo le mie esigenze. Eccolo:

https://gist.github.com/iusondemand/793c3ab9a461617378a3

1) mette informativa in alto
2) div personalizzabile facilmente
3) scompare dopo un qualsiasi click in qualsiasi parte del sito.

si puo' installare con un semplice search e replace. Io ho taggato i files dove devo mettere la soluzione, ora mi basta cercare il tag e sostituirlo con questo script.

Forza con i commenti :)

ps. a @Gix075 grande lavoro, ottimo. Ho creato i files su: https://github.com/FattiDiCookies/italianPrivacyPolicy/tree/master/html

pps: il javascript non agisce sul blocco preventivo dei terzi che ex punto 14 faq del Garante non e' richiesto se non profilo io stesso.

**Comment by 2autunni** [comment]
nel file iusondemand-cookie.htm il link a cookie.php non andrebbe sostituito con ./italianPrivacyPolicy.html  ?

**Comment by iusondemand** [comment]
Ciap, l'idea e' quella. 

Tieni presente che quando si crea una pagina difficilmente si usa il tuo html senza aggiungerlo in un template, cosa che sa fare solo un php.

Posso chiederti con quale editor hai realizzato il testo dell'html dell'informativa estesa ? Ci sono delle classi molto intelligenti e particolari !

**Comment by 2autunni** [comment]
@iusondemand ho visto che hai aggiunto il file cookie.php che include l'html

IMHO sembra una complicazione non necessaria, che introduce un vincolo non necessario (php).
Io lascerei tutto in html e una volta arrivati a un grado di maturità accettabile creiamo delle sottocartelle (o meglio dei fork) per i vari linguaggi di programmazione e/o cms.

@Gix075 tu che hai lanciato il progetto, come te lo immaginavi?

**Comment by iusondemand** [comment]
@2autunni tecnicamente e' una complicazione, certo. Potrei mettere direttamente il file html.

pero':
1) non credo che nessuno metta un html senza vestirlo con la grafica del proprio sito
2) php e' universale
3) e' una maggiore complessita' (Banale, un redirect o un include e' un attimo), ma permette molta molta piu' flessibilita' per chi deve poi adattare la soluzione al proprio sito.

**Comment by 2autunni** [comment]
> 1) non credo che nessuno metta un html senza vestirlo con la grafica del proprio sito
> la grafica non è "gestita" da php, ma dai css
> 2) php e' universale
> Non tutti i progetti web hanno alle spalle uno stack LAMP, ci sono molti progetti web basati su altri linguaggi (asp, java, nodejs, ruby ecc. ecc. ) 

La cosa migliore, secondo me,  per rendere il tutto flessibile è rimanere il più generali possibile e permettere agli utenti di modificare il codice secondo le loro esigenze.

Il tutto detto con la massima umiltà :-)  che non ci siamo solo io e te in sto progetto, vediamo cosa ne pensano anche gli altri

**Comment by iusondemand** [comment]
@2autunni sarebbe utile sentire anche altri. Io parlo da sviluppatore, ed ad ogni contenuto aggiungo la cornice con php, il quale a sua volta spara html, css, javascript .... :)
Chi ha altri linguaggi ha di solito anche php.
Comunque perche' non mandi una modifica con una variabile al posto della url fissa ?
MI CORREGGO: la variable ctmp e' gia' ... variabile. Ognuno deve personalizzarsela come meglio crede.

**Comment by iusondemand** [comment]
aggiungo un'altra informazione.
C'e' uno script che anonimizza google adsense. E' gpl. potrebbe rendere superflui i nostri.

https://secure.chamsys.co.uk/resources/javascript/cl.htm

**Comment by Gix075** [comment]
Io pensavo di fare inizialmente tutto html e javascript (jQuery per essere precisi) con un sistema di templating (sempre js) fatto da noi. I problemi però con questo tipo di approccio sono credo di accessibilità oltre che di seo (anche se a nessuno credo interessi indicizzare le policy)
Quindi forse sarebbe meglio un approccio un po' più ibrido, quindi anche con php, magari facendo due pacchetti distinti. 

Quindi direi che come prima cosa dovremmo sbrigarci a fare i testi in formato markdown per poi convertirli anche in html e json per poi poterli usare come vogliamo.

**Comment by Gix075** [comment]
Potreste dare un'occhiata a questo plugin jquery fatto da me per l'informativa breve e dirmi cosa ne pensate? Se lo considerate valido è già pronto ed essendo codice mio posso aggiustarlo come serve. 

https://github.com/Gix075/cookieDisclaimer

**Comment by hmtechnology** [comment]
Lato Seo, forse anche meglio se le policy non sono posizionate...tra l'altro essendo poi un modello da riutilizzare tra molti utenti, si tratterebbe di contenuti "duplicati", oltre che irrilevanti per le query di ricerca dell'utente

**Comment by hmtechnology** [comment]
@Gix075 per me è ok quell'informativa breve

**Comment by hmtechnology** [comment]
@iusondemand molto interessante per anonimizzare adsense;)
