### ISSUE TITLE
Cookie "causati" da video di  youtube

### ISSUE THREAD

**Issue by 2autunni** [FattiDiCookies/italianPrivacyPolicy#21]
Ciao, 
quando si inserisce in una pagina web un video di youtube vengono generati alcuni cookie,  è un'azione piuttosto comune, ma i cookie che vengono caricati sono definiti da google sia a fini di advertising  che tecnici  [ http://www.google.com/policies/technologies/types/ ]

Tra i cookie creati dovrebbero esserci con dominio youtube.com almeno 
VISITOR_INFO1_LIVE, YSC,  dkv, PREF, GEUP 
e 
NID e PREF provenienti da google.com 

Questi sono i cookie che uno si ritrova visitando una pagina contente un video di youtube senza che sul browser sia attiva una sessione per youtube, se l'utente è loggato su youtube i cookie sono molti di più.

A mio avviso una policy riguardante questo servizio potrebbe essere importante per un blog con più autori o un forum, dove il gestore della piattaforma non ha percezione del crearsi di questi cookie, e quindi la policy deve essere in qualche modo "preventiva". 

NOTA:  esiste anche la possibilità di incoroporare i video in modalità di privacy ottimizzata 
"L'attivazione di questa opzione fa in modo che YouTube non memorizzi le informazioni sui visitatori della tua pagina web, a meno che non riproducano il video."
https://support.google.com/youtube/answer/171780?expand=PrivacyEnhancedMode#privacy

**Comment by iusondemand** [comment]
fai un search and replace di:
www.youtube.com/embed
in
www.youtube-nocookie.com/embed

**Comment by 2autunni** [comment]
@iusondemand 
quello che suggerisci è quello che ho scritto nella nota. 
Il problema è che in un sito in cui non hai completo controllo dei contenuti (es un forum) non puoi escludere che vengano embeddati video che si portano dietro cookie di terze parti.

**Comment by Gix075** [comment]
Io direi di buttare giù due righe anche per questo scenario da aggiungere alla policy. In alcuni siti con staff fatti di persone poco preparate direi che impossibile fargli cambiare le url degli embed.

Chi se ne occupa?

**Comment by Gix075** [comment]
Proposta di testo per YouTube
Mancano i link alle pagine per la gestione dei cookie... se qualche anima pia se ne volesse occupare.

**YouTube**
Il sito **[[NOME SITO]]** utilizza porzioni di codice proveniente dal sito [https://www.youtube.com/](https://www.youtube.com/) al fine di mostrare alcuni contenuti video nelle proprie pagine.
I servizio _YouTube_ installa alcuni cookie tecnici utilizzati solo per il funzionamento del servizio e alcuni cookie di profilazione in grado di tenere traccia del comportamento dell'utente. Tali cookie possono rimanere installati nel browser dell'utente per periodi superiori alla singola sessione. 
**[[NOME SITO]]** non usa i cookie rilasciati da _YouTube_ per profilare in prima persona, né ha accordi con _YouTube_ per la profilazione in prima persona. 

Che dite la proponiamo come bozza?

**Comment by 2autunni** [comment]
l' informativa di google sui cookie si trova alla url  https://www.google.it/intl/it/policies/technologies/cookies/
o
https://www.google.it/intl/it/policies/technologies/managing/
se vogliamo le istruzioni su come si disabilita

diventerebbe:

**YouTube**
Il sito **[[NOME SITO]]** utilizza porzioni di codice proveniente dal sito [https://www.youtube.com/](https://www.youtube.com/) al fine di mostrare alcuni contenuti video nelle proprie pagine.
I servizio _YouTube_ installa alcuni cookie tecnici utilizzati solo per il funzionamento del servizio e alcuni cookie di profilazione in grado di tenere traccia del comportamento dell'utente. Tali cookie possono rimanere installati nel browser dell'utente per periodi superiori alla singola sessione. 
**[[NOME SITO]]** non usa i cookie rilasciati da _YouTube_ per profilare in prima persona, né ha accordi con _YouTube_ per la profilazione in prima persona. 

Per ulteriori informazioni su questi cookie e su come disattivarli puoi consultare le informazioni presenti nella  pagina https://www.google.it/intl/it/policies/technologies/cookies/

**Comment by Gix075** [comment]
Ok, perfetto. La metto in approvazione con una nuova issue. Chiudo questa issue per non creare confusione.
