### ISSUE TITLE
informativa breve solo cookie tecnici

### ISSUE THREAD

**Issue by 2autunni** [FattiDiCookies/italianPrivacyPolicy#22]
Qui 7adaef9f86ab983b0b8035d5a79570d94d636a66 ho aggiunto il caso raro, ma non impossibile, di un sito con solo cookie tecnici. 
Lo aggiungo più che altro per completezza, per aiutare chi utilizzerà questo codice a orientarsi nei possibili casi.
In  caso di "solo cookie tecnici" come buona pratica consiglierei di esporre comunque l'informativa breve, per essere il più trasparente possibile all'utente finael del sito
Ditemi se vi pare sensato?

**Comment by Gix075** [comment]
Dato che sono state aperte alcune proposte per la modifica delle informative brevi, per evitare confusioni, chiudo questa issue spostando la discussione [QUI](https://github.com/FattiDiCookies/italianPrivacyPolicy/issues/15)

Riaprire in caso di necessità
