### ISSUE TITLE
Cookie Policy - Informativa estesa - Introduzione

### ISSUE THREAD

**Issue by Gix075** [FattiDiCookies/italianPrivacyPolicy#23]
@vannaccirere ha postato da giorni [QUESTO FILE](https://github.com/FattiDiCookies/italianPrivacyPolicy/blob/master/bozze/cookie-policy_estesa/cookie-informativa-estesa-it.md) 

Dovremmo iniziare a discuterne attivamente. Personalmente direi di iniziare per pezzi,  magari dall'introduzione e proponendo inegrazioni, modifiche e correzioni.

**Comment by 2autunni** [comment]
possiamo cambiare mio.com in example.org.
È un dettaglio, ma mio.com esiste e non sappiamo cosa un domani ci verrà caricato sopra, mentre example è tenuto su dalla IANA per essere usato come dominio di esempio nei documenti

Nei cookie tecnici cambierei il ''di sessioni" con "di sessione"
Cambierei il  "(inficiando così la visualizzazione delle pagine del sito)." con qualcosa di più incisivo perché magari non è la visualizzazione ad essere inficiata, ma il funzionamento stesso del sito (es accesso ad aree riservate)

**Comment by Gix075** [comment]
Dobbiamo sostituire con gli stessi placeholder usati nella privacy policy ... in questo caso **[[NOME SITO]]** anzi nello specifico con **[[URL SITO]]**

**Comment by 2autunni** [comment]
con questo 04861d100e75fc12731dd386bc2958ad4e1b2edb ho sostituito mio.com con [[URL SITO]] restano le url delle img da aggiustare

**Comment by vannaccirere** [comment]
Provate a vedere se va bene cosi:

<h2>Uso dei cookie</h2>

<p>www.example.org o il “<strong>Sito</strong>” utilizza i Cookie per rendere i propri servizi semplici e efficienti per l’utenza che visiona le pagine di www.example.org.<br />
Gli utenti che visionano il Sito, vedranno inserite delle <strong>quantità minime di informazioni</strong> nei dispositivi in uso, che siano computer e periferiche mobili, in piccoli file di testo denominati “cookie” salvati nelle directory utilizzate dal browser web dell’Utente.<br />
Vi sono <strong>vari tipi di cookie</strong>, alcuni per rendere più efficace l’uso del Sito, altri per abilitare determinate funzionalità.<br />
Analizzandoli in maniera particolareggiata i nostri cookie permettono di:</p>
<ul>
<li>memorizzare le preferenze inserite</li>
<li>evitare di reinserire le stesse informazioni più volte durante la visita quali ad esempio nome utente e password</li>
<li>analizzare l’utilizzo dei servizi e dei contenuti forniti da www.example.org per ottimizzarne l’esperienza di navigazione e i servizi offerti</li>
</ul>
<h2>Tipologie di Cookie utilizzati da www.example.org</h2>
<p>A seguire i vari tipi di cookie utilizzati da www.example.org in funzione delle finalità d’uso</p>
<h3>Cookie Tecnici</h3>
<p>Questa tipologia di cookie permette il <strong>corretto funzionamento di alcune sezioni del Sito</strong>. Sono di due categorie: persistenti e di sessione:</p>
<ul>
<li><strong>persistenti</strong>: una volta chiuso il browser non vengono distrutti ma rimangono fino ad una data di scadenza preimpostata</li>
<li><strong>di sessioni</strong>: vengono distrutti ogni volta che il browser viene chiuso</li>
</ul>
<p>Questi cookie, inviati sempre dal nostro dominio, <strong>sono necessari a visualizzare correttamente il sito</strong> e in relazione ai servizi tecnici offerti, verranno quindi <strong>sempre utilizzati e inviati</strong>, a meno che l’utenza non modifichi le impostazioni nel proprio browser (inficiando così la visualizzazione delle pagine del sito).</p>
<h3>Cookie analitici</h3>
<p>I cookie in questa categoria vengono utilizzati per <strong>collezionare informazioni sull’uso del sito</strong>. www.example.org userà queste informazioni in merito ad <strong>analisi statistiche anonime</strong> al fine di migliorare l’utilizzo del Sito e per rendere i contenuti più interessanti e attinenti ai desideri dell’utenza. Questa tipologia di cookie raccoglie dati in <strong>forma anonima</strong> sull’attività dell’utenza e su come è arrivata sul Sito. I cookie analitici sono inviati dal Sito Stesso o da domini di terze parti.</p>
<h3>Cookie di analisi di servizi di terze parti</h3>
<p>Questi cookie sono utilizzati al fine di raccogliere informazioni sull’<strong>uso del Sito</strong> da parte degli utenti in <strong>forma anonima</strong> quali: pagine visitate, tempo di permanenza, origini del traffico di provenienza, provenienza geografica, età, genere e interessi ai fini di campagne di marketing. Questi cookie sono inviati da domini di terze parti esterni al Sito.</p>
<h3>Cookie per integrare prodotti e funzioni di software di terze parti</h3>
<p>Questa tipologia di cookie <strong>integra funzionalità sviluppate da terzi</strong> all’interno delle pagine del Sito come le icone e le preferenze espresse nei social network al fine di condivisione dei contenuti del sito o per l’uso di servizi software di terze parti (come i software per generare le mappe e ulteriori software che offrono servizi aggiuntivi). Questi cookie sono inviati da <strong>domini di terze parti</strong> e da <strong>siti partner</strong> che offrono le loro funzionalità tra le pagine del Sito.</p>
<h3>Cookie di profilazione</h3>
<p>Sono quei cookie necessari a creare profili utenti al fine di inviare messaggi pubblicitari in linea con le preferenze manifestate dall’utente all’interno delle pagine del Sito.<br />
www.example.org <strong>non utilizza cookie di profilazione</strong>.</p>
<hr />
<p>www.example.org, secondo la normativa vigente, non è tenuto a chiedere consenso per i <strong>cookie tecnici</strong> e di <strong>analytics</strong>, in quanto necessari a fornire i servizi richiesti.</p>
<p>Per tutte le altre tipologie di cookie il consenso può essere espresso dall’Utente con una o più di una delle seguenti modalità:</p>
<ul>
<li><strong>Mediante specifiche configurazioni del browser</strong> utilizzato o dei relativi programmi informatici utilizzati per navigare le pagine che compongono il Sito.</li>
<li><strong>Mediante modifica delle impostazioni</strong> nell’uso dei servizi di terze parti</li>
</ul>
<p>Entrambe queste soluzioni potrebbero impedire all’utente di utilizzare o visualizzare parti del Sito.</p>
<p><strong>Siti Web e servizi di terze parti</strong></p>
<p>Il Sito potrebbe contenere collegamenti ad altri siti Web che dispongono di una propria informativa sulla privacy che può essere diverse da quella adottata da www.mio.com e che che quindi <strong>non risponde</strong> di questi siti.</p>
<hr />
<h2>Cookie utilizzati da www.example.org</h2>
<p>A seguire la lista di cookie tecnici e di analytics utilizzati da questo Sito:</p>
<ul>
<li>cookiebello</li>
<li>cookiefresco</li>
</ul>
<div></div>
<hr />
<p>Come disabilitare i cookie mediante configurazione del browser</p>
<p><strong>Chrome</strong></p>
<ol>
<li>Eseguire il Browser Chrome</li>
<li>Fare click sul menù  presente nella barra degli strumenti del browser a fianco della finestra di inserimento url per la navigazione</li>
<li>Selezionare <strong>Impostazioni</strong></li>
<li>Fare clic su <strong>Mostra Impostazioni Avanzate</strong></li>
<li>Nella sezione “Privacy” fare clic su bottone “<strong>Impostazioni contenuti</strong>“</li>
<li>Nella sezione “Cookie” è possibile modificare le seguenti impostazioni relative ai cookie:
<ul>
<li>Consentire il salvataggio dei dati in locale</li>
<li>Modificare i dati locali solo fino alla chiusura del browser</li>
<li>Impedire ai siti di impostare i cookie</li>
<li>Bloccare i cookie di terze parti e i dati dei siti</li>
<li>Gestire le eccezioni per alcuni siti internet</li>
<li>Eliminazione di uno o tutti i cookie</li>
</ul>
</li>
</ol>
<p>Per maggiori informazioni visita la <a href="https://support.google.com/accounts/answer/61416?hl=en" target="_blank" rel="nofollow">pagina dedicata</a>.</p>
<p><strong>Mozilla Firefox</strong></p>
<ol>
<li>Eseguire il Browser Mozilla Firefox</li>
<li>Fare click sul menù  presente nella barra degli strumenti del browser a fianco della finestra di inserimento url per la navigazione</li>
<li>Selezionare <strong>Opzioni</strong></li>
<li>Seleziona il pannello <strong>Privacy</strong></li>
<li>Fare clic su <strong>Mostra Impostazioni Avanzate</strong></li>
<li>Nella sezione “Privacy” fare clic su bottone “<strong>Impostazioni contenuti</strong>“</li>
<li>Nella sezione “<strong>Tracciamento</strong>” è possibile modificare le seguenti impostazioni relative ai cookie:
<ul>
<li>Richiedi ai siti di non effettuare alcun tracciamento</li>
<li>Comunica ai siti la disponibilità ad essere tracciato</li>
<li>Non comunicare alcuna preferenza relativa al tracciamento dei dati personali</li>
</ul>
</li>
<li>Dalla sezione “<strong>Cronologia</strong>” è possibile:
<ul>
<li>Abilitando “Utilizza impostazioni personalizzate” selezionare di accettare i cookie di terze parti (sempre, dai siti più visitato o mai) e di conservarli per un periodo determinato (fino alla loro scadenza, alla chiusura di Firefox o di chiedere ogni volta)</li>
<li>Rimuovere i singoli cookie immagazzinati</li>
</ul>
</li>
</ol>
<p>Per maggiori informazioni visita la <a href="https://support.mozilla.org/en-US/kb/enable-and-disable-cookies-website-preferences" target="_blank" rel="nofollow">pagina dedicata</a>.</p>
<p><strong>Internet Explorer</strong></p>
<ol>
<li>Eseguire il Browser Internet Explorer</li>
<li>Fare click sul pulsante <strong>Strumenti</strong> e scegliere <strong>Opzioni Internet</strong></li>
<li>Fare click sulla scheda <strong>Privacy</strong> e nella sezione Impostazioni modificare il dispositivo di scorrimento in funzione dell’azione desiderata per i cookie:
<ul>
<li>Bloccare tutti i cookie</li>
<li>Consentire tutti i cookie</li>
<li>Selezione dei siti da cui ottenere cookie: spostare il cursore in una posizione intermedia in modo da non bloccare o consentire tutti i cookie, premere quindi su Siti, nella casella Indirizzo Sito Web inserire un sito internet e quindi premere su Blocca o Consenti</li>
</ul>
</li>
</ol>
<p>Per maggiori informazioni visita la <a href="http://windows.microsoft.com/it-it/windows-vista/block-or-allow-cookies" target="_blank" rel="nofollow">pagina dedicata</a>.</p>
<p><strong>Safari 6</strong></p>
<ol>
<li>Eseguire il Browser Safari</li>
<li>Fare click su <strong>Safari</strong>, selezionare <strong>Preferenze</strong> e premere su <strong>Privacy</strong></li>
<li>Nella sezione <em>Blocca Cookie</em> specificare come Safari deve accettare i cookie dai siti internet.</li>
<li>Per visionare quali siti hanno immagazzinato i cookie cliccare su <strong>Dettagli</strong></li>
</ol>
<p>Per maggiori informazioni visita la <a class="broken_link" href="http://support.apple.com/kb/ph11913" target="_blank" rel="nofollow">pagina dedicata</a>.</p>
<p><strong>Safari iOS (dispositivi mobile)</strong></p>
<ol>
<li>Eseguire il Browser Safari iOS</li>
<li>Tocca su <strong>Impostazioni</strong> e poi <strong>Safari</strong></li>
<li>Tocca su <strong>Blocca Cookie</strong> e scegli tra le varie opzioni: “Mai”, “Di terze parti e inserzionisti” o “Sempre”</li>
<li>Per cancellare tutti i cookie immagazzinati da Safari, tocca su <strong>Impostazioni</strong>, poi su <strong>Safari</strong> e infine su <strong>Cancella Cookie e dati</strong></li>
</ol>
<p>Per maggiori informazioni visita la <a href="http://support.apple.com/kb/HT1677?utm_source=Agillic%20Dialogue" target="_blank" rel="nofollow">pagina dedicata</a>.</p>
<p><strong>Opera</strong></p>
<ol>
<li>Eseguire il Browser Opera</li>
<li>Fare click sul Preferenze poi su Avanzate e infine su Cookie</li>
<li>Selezionare una delle seguenti opzioni:
<ul>
<li>Accetta tutti i cookie</li>
<li>Accetta i cookie solo dal sito che si visita: i cookie di terze parti e che vengono inviati da un dominio diverso da quello che si sta visitando verranno rifiutati</li>
<li>Non accettare mai i cookie: tutti i cookie non verranno mai salvati</li>
</ul>
</li>
</ol>
<p>Per maggiori informazioni visita la <a href="http://windows.microsoft.com/it-it/windows-vista/block-or-allow-cookies" target="_blank" rel="nofollow">pagina dedicata</a>.</p>
<hr />
<h2>Come disabilitare i cookie di servizi di terzi</h2>
<ul>
<li><a href="http://www.google.com/ads/preferences/?hl=it" rel="nofollow">Servizi di Google</a></li>
<li><a href="https://www.facebook.com/help/cookies?ref_type=sitefooter" rel="nofollow">Facebook</a></li>
<li><a href="https://support.twitter.com/articles/20170519-uso-dei-cookie-e-di-altre-tecnologie-simili-da-parte-di-twitter#" rel="nofollow">Twitter</a></li>
</ul>
<hr />
<p>Questa pagina è visibile, mediante link in calce in tutte le pagine del Sito ai sensi dell’art. 122 secondo comma del D.lgs. 196/2003 e a seguito delle modalità semplificate per l’informativa e l’acquisizione del consenso per l’uso dei cookie pubblicata sulla Gazzetta Ufficiale n.126 del 3 giugno 2014 e relativo registro dei provvedimenti n.229 dell’8 maggio 2014.</p>
<p>Inoltre puoi leggere la nostra informativa sulla privacy da qui <a href="http://example.org/privacy">privacy</a></p>
<p>Questi cookie, inviati sempre dal nostro dominio, <strong>sono necessari a visualizzare correttamente il sito</strong> e in relazione ai servizi tecnici offerti, verranno quindi <strong>sempre utilizzati e inviati</strong>, a meno che l’utenza non modifichi le impostazioni nel proprio browser (inficiando così la visualizzazione delle pagine del sito).</p>
<span style="font-size: 12pt;">
<br style="margin: 0px;">
<span style="font-size: 12pt;">Per eliminare i cookie dal browser Internet del proprio smartphone/tablet, è necessario fare riferimento al manuale d'uso del dispositivo. </span>
</p>

**Comment by vannaccirere** [comment]
@2autunni, cancella questo file che per favore, per problemi vecchi con 
un azienda privata : 04861d1 
https://github.com/FattiDiCookies/italianPrivacyPolicy/commit/04861d100e75fc12731dd386bc2958ad4e1b2edb

**Comment by 2autunni** [comment]
@vannaccirere scusa, non capisco cosa devo cancellare? il commit? il file che in origine avevi postato?

**Comment by vannaccirere** [comment]
04861d1 
https://github.com/FattiDiCookies/italianPrivacyPolicy/commit/04861d100e75fc12731dd386bc2958ad4e1b2edb 
questo file

**Comment by 2autunni** [comment]
@vannaccirere  quello è il link a un commit, cioè è la traccia di una modifica, onestamente non so se con git puoi riscrivere la storia... 
Se vuoi posso eliminare dai file esistenti questo  https://github.com/FattiDiCookies/italianPrivacyPolicy/blob/master/bozze/cookie-policy_estesa/cookie-informativa-estesa-it.md

**Comment by vannaccirere** [comment]
ok

**Comment by 2autunni** [comment]
@Gix075 @vannaccirere  se volete ripulire la storia dei commit (operazione delicata) ci sono queste istruzioni https://help.github.com/articles/remove-sensitive-data/

**Comment by 2autunni** [comment]
@vannaccirere ho cancellato anche la versione html, se ho sbagliato puoi ripristinare a prima del mio commit

**Comment by Gix075** [comment]
Dobbiamo togliere anche il file nella directory "docs" dato che dovrebbe essere più o meno uguale all'altro?

**Comment by 2autunni** [comment]
Scusate, ma a sto punto non abbiamo più un'informativa estesa valida o sbaglio?

**Comment by Gix075** [comment]
Credo di no. Per sicurezza stavo iniziando a riscriverla

**Comment by Gix075** [comment]
@2autunni @vannaccirere dato che non abbiamo più l'altra, ho iniziato a buttare giù una nuova policy estesa per i cookie.
Dategli un'occhiata che siamo troppo in ritardo. 

@iusondemand help us!

**Comment by 2autunni** [comment]
@Gix075 dove l'hai messa?

update: vista

**Comment by vannaccirere** [comment]
ragazzi no problem  ho un backup @Gix075  @2autunni

**Comment by iusondemand** [comment]
scusa, su altro thread ho messo la mia: www.civile.it/cookie.php copia, incolla, modific aliberamente, e' originale, l'ho scritta partendo dalla mia checklist. Comunque alla luce delle ultime riflessioni si puo' semplificare ancora di piu'.

A proposito, sono disponibile ad un incontro fisico in Milano o zona Bergamo. Se volete ci incontriamo tutti.

**Comment by hmtechnology** [comment]
@Gix075 Il cappello introduttivo deve necessariamente (per la cookie policy) tenere conto degli elementi del codice privacy e deve essere quindi qualcosa del genere:

"Con il presente documento, ai sensi degli artt. 13 e 122 del D.Lgs. 196/2003 (“codice privacy”), e a seguito delle modalità semplificate per l'informativa e l'acquisizione del consenso per l'utilizzo dei cookie, pubblicate sulla Gazzetta Ufficiale n.126 del 3 giugno 2014 e previsto dal provvedimento generale del Garante Privacy dell'8 Maggio 2014, NOME e COGNOME, titolare del trattamento, fornisce agli utenti del sito WWW.SITO.IT fornisce ai visitatori un'informativa su cosa sono i Cookie e sul loro utilizzo all'interno del sito."

**Comment by hmtechnology** [comment]
e poi si parte con Cosa sono i cookie e via dicendo

**Comment by Gix075** [comment]
Se mi confermi che il testo è tuo e non ci sono problemi di copyright lo inseriamo subito.

**Comment by hmtechnology** [comment]
E' un testo abbastanza standard (che ho cercato di modificare leggermente) che in forma più o meno diversa è presente in tantissimi siti, non credo proprio ci sia alcun problema di copyright. Esempi: http://robertarapicavoli.it/informativa-cookie/, http://www.giulianiautomilano.it/cookies.html

**Comment by Gix075** [comment]
@hmtechnology 
Il problema è che iubenda ci ha già minacciato quindi non vorrei incorrere in ulteriori problemi con loro o altri. Se dici che però è abbastanza custom da essere tuo non ci sono problemi. Ho fatto qualche modifica per andare ancora più sul sicuro. Vedi se ti piace.

"La presente pagina, redatta ai sensi degli artt. 13 e 122 del D.Lgs. 196/2003 (“codice privacy”), e a seguito delle modalità semplificate per l'informativa e l'acquisizione del consenso per l'utilizzo dei cookie, pubblicate sulla Gazzetta Ufficiale n.126 del 3 giugno 2014 e prevista dal provvedimento generale del Garante Privacy dell'8 Maggio 2014, **[[NOME E COGNOME DEL RESPONSABILE]]**, titolare del trattamento dei dati personali, fornisce agli utenti del sito **[[NOME SITO]]**  un'informativa dettagliata su cosa sono i Cookie e sul loro utilizzo all'interno di questo sito."

**Comment by 2autunni** [comment]
se no possiamo chiedere alla rapicavoli il permesso di usare la sua versione... 
come dice in fonod a questa pagina http://robertarapicavoli.it/condizioni-generali/

**Comment by hmtechnology** [comment]
No, quell'azienda privata non centra niente in questo caso anzi non mi pare usino niente del genere loro. Comunque comprendo benissimo ciò che dici ma direi che nella tua versione, è ancora meglio e credo nessuno possa eccepire nulla, d'altronde alcune cose devono necessariamente assomigliarsi tra loro

**Comment by hmtechnology** [comment]
Ho visto che c'è un errore perchè la prima frase comincia ma non finisce correttamente (La presente pagina, redatta bla bla, a seguito bla bla, Nome e Cognome fornisce l'informativa). Se vogliamo lasciarla così deve necessariamente cominciare così: "CON la presente pagina etc etc"

**Comment by Gix075** [comment]
@hmtechnology hai ragione, quindi diventa:

"Con la presente pagina, redatta ai sensi degli artt. 13 e 122 del D.Lgs. 196/2003 (“codice privacy”), e a seguito delle modalità semplificate per l'informativa e l'acquisizione del consenso per l'utilizzo dei cookie, pubblicate sulla Gazzetta Ufficiale n.126 del 3 giugno 2014 e prevista dal provvedimento generale del Garante Privacy dell'8 Maggio 2014, **[[NOME E COGNOME DEL RESPONSABILE]]**, titolare del trattamento dei dati personali, fornisce agli utenti del sito **[[NOME SITO]]**  un'informativa dettagliata su cosa sono i Cookie e sul loro utilizzo all'interno di questo sito."

**Comment by hmtechnology** [comment]
Perfetta. Se qualcuno vuole ulteriormente personalizzarla, ben venga, se no comunque va già benone questa. La metti nel repo?

**Comment by Gix075** [comment]
Inserita.

**Comment by hmtechnology** [comment]
Vista, ottima. Chiudo qui.

**Comment by hmtechnology** [comment]
Apporto delle modifiche nel file della repo per personalizzare ulteriormente il testo di cappello e inserire qualche link di riferimento.

**Comment by Gix075** [comment]
Chiudo alcune vecchie issue per fare un po' di pulizia e focalizzare sulle nuove. Se serve riaprite.
