### ISSUE TITLE
Servizio YouTube

### ISSUE THREAD

**Issue by Gix075** [FattiDiCookies/italianPrivacyPolicy#24]
Dalla segnalazione di @2autunni è stata partorita questa descrizione per il servizio YouTube. 
Per smaltire il lavoro e sveltire i tempi la mettiamo in approvazione da subito.

**YouTube**
Il sito **[[NOME SITO]]** utilizza porzioni di codice proveniente dal sito [https://www.youtube.com/](https://www.youtube.com/) al fine di mostrare alcuni contenuti video nelle proprie pagine.
I servizio _YouTube_ installa alcuni cookie tecnici utilizzati solo per il funzionamento del servizio e alcuni cookie di profilazione in grado di tenere traccia del comportamento dell'utente. Tali cookie possono rimanere installati nel browser dell'utente per periodi superiori alla singola sessione. 
**[[NOME SITO]]** non usa i cookie rilasciati da _YouTube_ per profilare in prima persona, né ha accordi con _YouTube_ per la profilazione in prima persona. 

Per ulteriori informazioni su questi cookie vedi la pagina [ https://www.google.it/intl/it/policies/technologies/cookies/](https://www.google.it/intl/it/policies/technologies/cookies/)

Per disattivare questi cookie puoi consultare le informazioni presenti nella  pagina https://www.google.it/intl/it/policies/technologies/managing/

**Comment by Gix075** [comment]
Data la mancanza di tempo **ho dato per buono questo testo** (con le modifiche suggerite) ed ho aggiunto un file nella directory **["docs/md/cookie-policy/services"](https://github.com/FattiDiCookies/italianPrivacyPolicy/tree/master/docs/cookie-policy/md/services). 

Per il momento chiudo l'issue. In caso di cambiamenti da fare è possibile riaprire il ticket.

**Comment by hmtechnology** [comment]
### Youtube

_Youtube_ è una è una piattaforma web, [http://www.youtube.com](http://www.youtube.com), che consente la condivisione e visualizzazione di video online. _Youtube_ raccoglie, oltre ai dati forniti dall'utente, informazioni sui servizi utilizzati tra cui identificatori univoci dei dispositivi, informazioni sulla rete mobile, dati sulla posizione, e altro. _Youtube_ utilizza cookie e identificatori anonimi quando l'utente interagisce con Youtube per migliorare la qualità generale dei servizi e l'esperienza degli utenti.  
[[NOME SITO]] non utilizza il servizio _Youtube_ per la profilazione dell'utente in prima parte e non ha accordi con _Youtube_ per profilare in prima parte.

##### Link di riferimento
- [Privacy Policy](https://www.google.it/intl/it/policies/privacy/)

**Comment by Gix075** [comment]
Per me è ok.
