### ISSUE TITLE
servizio google maps

### ISSUE THREAD

**Issue by 2autunni** [FattiDiCookies/italianPrivacyPolicy#25]
Dalla policy elaborata da @Gix075 per youtube cambiando poco si ha quella per Google Maps, che ne dite?

**Google Maps**
Il sito **[[NOME SITO]]** utilizza porzioni di codice proveniente dal sito [https://maps.google.com/](https://maps.google.com/) al fine di mostrare alcuni mappe nelle proprie pagine.
Il servizio _Google Maps_ installa alcuni cookie tecnici utilizzati solo per il funzionamento del servizio e alcuni cookie di profilazione in grado di tenere traccia del comportamento dell'utente. Tali cookie possono rimanere installati nel browser dell'utente per periodi superiori alla singola sessione. 
**[[NOME SITO]]** non usa i cookie rilasciati da _Google Maps_ per profilare in prima persona, né ha accordi con _Google_ per la profilazione in prima persona. 

Per ulteriori informazioni su questi cookie vedi la pagina [ https://www.google.it/intl/it/policies/technologies/cookies/](https://www.google.it/intl/it/policies/technologies/cookies/)

Per disattivare questi cookie puoi consultare le informazioni presenti nella  pagina https://www.google.it/intl/it/policies/technologies/managing/

**Comment by Gix075** [comment]
Per me è ok!

**Comment by 2autunni** [comment]
devo aggiungerci anche un link a questo https://www.google.com/intl/it_IT/help/terms_maps.html 
come indicato nella milestone? A senso direi di no, visto che rimanda al documento sulla privacy che linkiamo

**Comment by Gix075** [comment]
Se rimanda ad una stessa pagina già linkata direi di no.

**Comment by iusondemand** [comment]
metti che uno abbia solo mappe e non youtube ne' altro di google. Serve comunque. Meglio ripetere che mancare

**Comment by Gix075** [comment]
@2autunni forse @iusondemand ha ragione, inseriamolo.

**Comment by 2autunni** [comment]
@iusondemand gli dai tu forma definitiva?

**Comment by iusondemand** [comment]
vedi quanto scritto sulla possibilita' di usare www.youronlinechoices.com/it In effetti potremmo anche restare tipo kaspersky, senza spiegare nel dettaglio ogni cookie di terzi. Anzi, con www.youronlinechoices.com/it potremmo proprio tenere questo progetto solo per gli embed piu' usati (youtube, google map) ma solo per aiutare i lettori.

**Comment by Gix075** [comment]
Data la mancanza di tempo **ho dato per buono questo testo** (con le modifiche suggerite) ed ho aggiunto un file nella directory **["docs/md/cookie-policy/services"](https://github.com/FattiDiCookies/italianPrivacyPolicy/tree/master/docs/cookie-policy/md/services). 

Per il momento chiudo l'issue. In caso di cambiamenti da fare è possibile riaprire il ticket.
