### ISSUE TITLE
Embed Social Networks

### ISSUE THREAD

**Issue by 2autunni** [FattiDiCookies/italianPrivacyPolicy#26]
Ciao, 
Forse serve un frammento per coprire tutti i casi di embedd dai principali social 
Twitter, Vine, Pinterest, Instagram, Google Plus, senza dover fare un frammento per ognuno.

Sarebbe utile ad esempio per un blog, in modo che si setta la policy e si è coperti il giorno che ci si trova ad includere un contenuto da una di queste fonti 
Fb lo lascerei a parte perché è più complesso e potrebeb essere utilizzato come piattaforma per i commenti, non solo per embeddare contenuti.

Una cosa del genere: 

Il sito [[NOME SITO]] può utilizzare porzioni di codice provenienti dai social network Twitter, Vine, Pinterest, Instagram, Google Plus.
Questi servizi installano alcuni cookie tecnici utilizzati solo per il funzionamento del servizio e alcuni cookie di profilazione in grado di tenere traccia del comportamento dell'utente. Tali cookie possono rimanere installati nel browser dell'utente per periodi superiori alla singola sessione. 
[[NOME SITO]] non usa questi cookie per profilare in prima persona, né ha accordi con i gestori di questi social network per la profilazione in prima persona.

Che dite?
Ovviamente devo recuperare i link alle informative privacy dei vari servizi

**Comment by iusondemand** [comment]
si puo' fare una cosa simile per ogni servizio, allora. Non e' male come idea. Un testo base che si riempie con quello che serve che e' variabile: nome servizio, link a policy, link a modulo per esercitare il consenso presso terzi.

**Comment by Gix075** [comment]
@2autunni se ce la fai a reperire i vari link la inseriamo subito.

**Comment by 2autunni** [comment]
Il sito [[NOME SITO]] può utilizzare porzioni di codice provenienti dai social network Twitter, Vine, Pinterest, Instagram.
Questi servizi installano alcuni cookie tecnici utilizzati solo per il funzionamento del servizio e alcuni cookie di profilazione in grado di tenere traccia del comportamento dell'utente. Tali cookie possono rimanere installati nel browser dell'utente per periodi superiori alla singola sessione. 
[[NOME SITO]] non usa questi cookie per profilare in prima persona, né ha accordi con i gestori di questi social network per la profilazione in prima persona.

Maggiori informazioni possono essere reperite ai seguenti link:

[Twitter privacy plicy](https://twitter.com/privacy?lang=it)
[Vine privacy policy](https://vine.co/privacy)
[Pinterest privacy policy](https://about.pinterest.com/it/privacy-policy)
[Instagram cookies policy](https://instagram.com/legal/cookies/) 
[Instagram privacy policy](https://instagram.com/about/legal/privacy/)

Che ne dite? Tolgo gplus perché condivide link e cookie con altri servizi di google

**Comment by Gix075** [comment]
Io comunque gplus lo metterei comunque, però mi rimetto a voi. Intanto passo il file nella cartella dei servizi. Metto in approvazione anche se per me è già ok, ma se qualcuno vuole dire ancora la sua fino a domani sera lo lasciamo.

**Comment by Gix075** [comment]
Ho inserito il testo di @2autunni  in [docs/cookie-policy/md/services/social-networks.md](https://github.com/FattiDiCookies/italianPrivacyPolicy/blob/master/docs/cookie-policy/html/services/social-networks.md)

**Comment by 2autunni** [comment]
@Gix075 spostato nella directory md

**Comment by Gix075** [comment]
Visto che è stato inserito chiudo la issue. Riaprire in caso di necessità.

**Comment by hmtechnology** [comment]
Mi pare che ci si riferisca a questo no? https://github.com/FattiDiCookies/italianPrivacyPolicy/blob/master/docs/cookie-policy/md/services/social-networks.md

io più che Social Network la chiamerei "Contenuti embed da terze parti" (Twitter, Vine, Pinterest, Instagram). E ci aggiungerei Vimeo e anche le Google Map [idealmente tutto ciò che è iframe o simile]

Quindi al momento si avrebbe
1. "Contenuti embed da terze parti" (Twitter, Vine, Pinterest, Instagram, Vimeo, Google Map) 
2. "Strumenti di condivisione sociale" (AddThis, ShareThis)

**Comment by hmtechnology** [comment]
Tra tutti i servizi "recensiti" restano Disqus (Sistema di Commenti), Google Analytics (Sistema di Statistica)

**Comment by Gix075** [comment]
Si infatti è questo, sono i bottoncini che arrivano come codice esterno ma rilasciano cookie. Abbiamo pensato di includerli come social in quanto simili e per far prima. Poi noto che manca Facebook. 
Disqus e Analytics sono stati fatti.

**Comment by hmtechnology** [comment]
Dal punto di vista della normativa però, a livello Macro, si fa riferimento ai cookie di profilazione, senza riferimento all'embed (che è piu una cosa tecnica). Sono tutti cookie di profilazione di terze parti.

**Comment by hmtechnology** [comment]
Si Disqus Analytics fatti, li stavo solo categorizzando perchè sicuramente aggiungeremo Facebook Comments, che andrà a sposarsi con Disqus fra i sistemi di commenti oppure Shinystat (che andrà con Analytics tra gli strumenti di statistica)

**Comment by 2autunni** [comment]
l'avevo definito social, perché ragionavo più dal punto di vista dell'utente che apre un blog e sa che avrà prima o poi necessità di includere contenuti dai social così invece di elencarli uno ad uno e aggiungerli man mano li aveva già pacchettizzati insieme

**Comment by Gix075** [comment]
Si ma infatti queste descrizioni di servizi nella policy vanno tutte sotto la voce di elenco dei cookie. Però se ritieni di doverla cambiare, posta una bozza e se ne discute.

**Comment by hmtechnology** [comment]
non ho capito @Gix075. cambiare cosa?
@2autunni si si per carità non volevo criticare la tua scelta. ma social è un pò troppo generico secondo me perchè racchiuderebbe anche i social sharing button ad esempio (addthis, sharethis, etc) che invece sono in un altro insieme

**Comment by Gix075** [comment]
@hmtechnology scusa non avevo visto i commenti prima, intendevo se volevi proporre qualche cambiamento a questa parte di testo.

**Comment by hmtechnology** [comment]
Ok ora vediamo un attimo. 

Fra i milestones vedo "Twitter buttons", "facebook buttons", "google plus share button", ma credo siano inutili perchè inclusi/da includere qui sopra no?

**Comment by 2autunni** [comment]
@hmtechnology nessun problema :-) 
Spero che il tono non ti sia apparso offeso, non era mia intenzione, 
Per facebook facciamo un solo frammento che tiene tutti i suoi servizi (commenti, embedd di post ecc. ecc) ?

**Comment by hmtechnology** [comment]
No ma figurati:) ci mancherebbe!

Su Facebook però non sono d'accordo xD lo farei finire qui sopra con gli altri per quanto riguarda l'embed (facebook buttons, post condivisi, etc). Mentre i commenti (facebook comments) li metterei a parte, insieme a Disqus, fra i Sistemi di Commenti

**Comment by 2autunni** [comment]
Ok, 
mi piace questo modo di raggruppare i servizi a seconda dello scopo, mi sembra molto intuitivo per l'utente che poi dovrà compilare il file di config

**Comment by hmtechnology** [comment]
Esatto, è proprio quello lo scopo, ma anche x rendere più snella l'eventuale lettura per i visitatori

**Comment by Gix075** [comment]
Dobbiamo fare un elenco di categorie con i relativi servizi associati, così lo inizio ad implementare nel tool. Al momento sono tutti insieme ma posso dividerli in oggetti differenti a seconda della categoria.

**Comment by hmtechnology** [comment]
Per ora abbiamo 
1. "Contenuti embed da terze parti" (Twitter, Vine, Pinterest, Instagram)
2. "Strumenti di condivisione sociale" (AddThis, ShareThis)
3. "Sistema di Commenti" (Disqus)
4. "Sistema di Statistica (Google Analytics)

Fra poco mi metto su AdSense, che potrebbe rientrare nei "Sistema di Banner Pubblicitari" (insieme a Tradedoubler, etc)

Aggiungerei Facebook, Vimeo e Google Map all'insieme 1.

**Comment by hmtechnology** [comment]
Aggiunto Adsense, ora abbiamo:

"Contenuti embed da terze parti" (Twitter, Vine, Pinterest, Instagram)
"Strumenti di condivisione sociale" (AddThis, ShareThis)
"Sistema di Commenti" (Disqus)
"Sistema di Statistica" (Google Analytics)
"Strumenti Pubblicitari" (Google AdSense)

Aggiungerei Facebook, Vimeo e Google Map all'insieme 1.

**Comment by Gix075** [comment]
Aggiorno il repository e il tool con il nuovo materiale e la divisione in categorie dei servizi. Nella directory dei documenti al momento però li lasciamo tutti insieme.

**Comment by 2autunni** [comment]
@Gix075  spero di non intralciarti con le modifiche che ho fatto per la issue #34

**Comment by Gix075** [comment]
@2autunni no no, nessun intralcio.

**Comment by Gix075** [comment]
Chiudo alcune vecchie issue per fare un po' di pulizia e focalizzare sulle nuove. Se serve riaprite.
