### ISSUE TITLE
Vimeo

### ISSUE THREAD

**Issue by 2autunni** [FattiDiCookies/italianPrivacyPolicy#27]
Ciao, frammento da usare in caso si incorporino nel sito video da vimeo

**Vimeo** 
Il sito [[NOME SITO]] utilizza porzioni di codice proveniente dal sito https://vimeo.com/ al fine di mostrare alcuni contenuti video nelle proprie pagine.
Il servizio Vimeo installa alcuni cookie tecnici utilizzati solo per il funzionamento del servizio e alcuni cookie di profilazione in grado di tenere traccia del comportamento dell'utente. Tali cookie possono rimanere installati nel browser dell'utente per periodi superiori alla singola sessione. 
[[NOME SITO]] non usa i cookie rilasciati da Vimeo per profilare in prima persona, né ha accordi con Vimeo per la profilazione in prima persona.

Per ulteriori informazioni su questi cookie vedi le pagine
https://vimeo.com/cookie_policy
https://vimeo.com/cookie_list

**Comment by Gix075** [comment]
Per me è ok, magari attendiamo qualche parere tipo di @iusondemand che sembra essere il più ferrato in materia di legge, ma per quanto mi riguarda lo darei già per buono.

**Comment by 2autunni** [comment]
quando uno di sti frammenti è approvato che facciamo lo piazziamo in un file json dentro la cartella bozze?

**Comment by Gix075** [comment]
Io pensavo di metterli intanto dentro una cartella in formato .md così sono sempre facilmente consultabili da GitHub e chi non vuole usare il nostro software potrà comunque fare copia e incolla. Poi si dovremmo trasformare tutto in json.

**Comment by Gix075** [comment]
@2autunni  Questa sera butto giù una prima prova di inclusione automatica, così ne discutiamo assieme.

**Comment by iusondemand** [comment]
per me ok. 
A proposito dell'elenco dettagliato, il garante consente il link e l'uso di http://www.youronlinechoices.com/it/le-tue-scelte 

Questo ci potrebbe permette di non fare noi stessi l'elenco di tutti i servizi.

In ogni caso il lavoro che si sta facendo a censirli non e' affatto male e dovremmo andare avanti, ma ovviamente la possibilita' di inserire http://www.youronlinechoices.com/it/le-tue-scelte nelle informative estese riduce tanta fatica ora.

Ci potremmo concentrare sui nostri cookies, e non e' male questo.

**Comment by 2autunni** [comment]
@iusondemand scusa vado forse OT:
 http://www.youronlinechoices.com/it se non ho capito male traccia solo quelli di circuiti pubblicitari  che facciamo? policy solo per quelli non inclusi nella loro lista?

**Comment by Gix075** [comment]
Data la mancanza di tempo **ho dato per buono questo testo** ed ho aggiunto un file nella directory **["docs/md/cookie-policy/services"](https://github.com/FattiDiCookies/italianPrivacyPolicy/tree/master/docs/cookie-policy/md/services). 

Per il momento chiudo l'issue. In caso di cambiamenti da fare è possibile riaprire il ticket.
