### ISSUE TITLE
Suddivisione dei task

### ISSUE THREAD

**Issue by Gix075** [FattiDiCookies/italianPrivacyPolicy#3]
Indicate qui la parte precisa del progetto alla quale intendete lavorare. Ho aperto, e sto continuando ad inserirne altri, alcune milestones sulle varie cose da fare. Buttateci un'occhiata e scegliete. Ovviamente poi ognuno potrà contribuire con commenti, suggerimenti e critiche ad ogni parte del progetto ma dobbiamo anche metterci un po' di fretta altrimenti non finiamo mai. Se avete del materiale pronto per servizi ancora non compresi nelle milestones aperte o volete suggerirne alcuni, fate pure, siete liberissimi di farlo. Aprite una nuova ISSUE per qualsiasi cosa vogliate discutere riguardo al progetto.

**Comment by ghost** [comment]
Testi privacy

**Comment by seosmart** [comment]
Link ai moduli di opt out dei vari browser

**Comment by Gix075** [comment]
Potresti stilare un elenco dei link?

**Comment by Gix075** [comment]
Chiudo alcune vecchie issue per fare un po' di pulizia e focalizzare sulle nuove. Se serve riaprite.
