### ISSUE TITLE
Cookie Policy

### ISSUE THREAD

**Issue by vannaccirere** [FattiDiCookies/italianPrivacyPolicy#30]
<h2>Uso dei cookie</h2>

<p>www.example.org o il “<strong>Sito</strong>” utilizza i Cookie per rendere i propri servizi semplici e efficienti per l’utenza che visiona le pagine di www.example.org.<br />
Gli utenti che visionano il Sito, vedranno inserite delle <strong>quantità minime di informazioni</strong> nei dispositivi in uso, che siano computer e periferiche mobili, in piccoli file di testo denominati “cookie” salvati nelle directory utilizzate dal browser web dell’Utente.<br />
Vi sono <strong>vari tipi di cookie</strong>, alcuni per rendere più efficace l’uso del Sito, altri per abilitare determinate funzionalità.<br />
Analizzandoli in maniera particolareggiata i nostri cookie permettono di:</p>
<ul>
<li>memorizzare le preferenze inserite</li>
<li>evitare di reinserire le stesse informazioni più volte durante la visita quali ad esempio nome utente e password</li>
<li>analizzare l’utilizzo dei servizi e dei contenuti forniti da www.example.org per ottimizzarne l’esperienza di navigazione e i servizi offerti</li>
</ul>
<h2>Tipologie di Cookie utilizzati da www.example.org</h2>
<p>A seguire i vari tipi di cookie utilizzati da www.example.org in funzione delle finalità d’uso</p>
<h3>Cookie Tecnici</h3>
<p>Questa tipologia di cookie permette il <strong>corretto funzionamento di alcune sezioni del Sito</strong>. Sono di due categorie: persistenti e di sessione:</p>
<ul>
<li><strong>persistenti</strong>: una volta chiuso il browser non vengono distrutti ma rimangono fino ad una data di scadenza preimpostata</li>
<li><strong>di sessioni</strong>: vengono distrutti ogni volta che il browser viene chiuso</li>
</ul>
<p>Questi cookie, inviati sempre dal nostro dominio, <strong>sono necessari a visualizzare correttamente il sito</strong> e in relazione ai servizi tecnici offerti, verranno quindi <strong>sempre utilizzati e inviati</strong>, a meno che l’utenza non modifichi le impostazioni nel proprio browser (inficiando così la visualizzazione delle pagine del sito).</p>
<h3>Cookie analitici</h3>
<p>I cookie in questa categoria vengono utilizzati per <strong>collezionare informazioni sull’uso del sito</strong>. www.example.org userà queste informazioni in merito ad <strong>analisi statistiche anonime</strong> al fine di migliorare l’utilizzo del Sito e per rendere i contenuti più interessanti e attinenti ai desideri dell’utenza. Questa tipologia di cookie raccoglie dati in <strong>forma anonima</strong> sull’attività dell’utenza e su come è arrivata sul Sito. I cookie analitici sono inviati dal Sito Stesso o da domini di terze parti.</p>
<h3>Cookie di analisi di servizi di terze parti</h3>
<p>Questi cookie sono utilizzati al fine di raccogliere informazioni sull’<strong>uso del Sito</strong> da parte degli utenti in <strong>forma anonima</strong> quali: pagine visitate, tempo di permanenza, origini del traffico di provenienza, provenienza geografica, età, genere e interessi ai fini di campagne di marketing. Questi cookie sono inviati da domini di terze parti esterni al Sito.</p>
<h3>Cookie per integrare prodotti e funzioni di software di terze parti</h3>
<p>Questa tipologia di cookie <strong>integra funzionalità sviluppate da terzi</strong> all’interno delle pagine del Sito come le icone e le preferenze espresse nei social network al fine di condivisione dei contenuti del sito o per l’uso di servizi software di terze parti (come i software per generare le mappe e ulteriori software che offrono servizi aggiuntivi). Questi cookie sono inviati da <strong>domini di terze parti</strong> e da <strong>siti partner</strong> che offrono le loro funzionalità tra le pagine del Sito.</p>
<h3>Cookie di profilazione</h3>
<p>Sono quei cookie necessari a creare profili utenti al fine di inviare messaggi pubblicitari in linea con le preferenze manifestate dall’utente all’interno delle pagine del Sito.<br />
www.example.org <strong>non utilizza cookie di profilazione</strong>.</p>
<hr />
<p>www.example.org, secondo la normativa vigente, non è tenuto a chiedere consenso per i <strong>cookie tecnici</strong> e di <strong>analytics</strong>, in quanto necessari a fornire i servizi richiesti.</p>
<p>Per tutte le altre tipologie di cookie il consenso può essere espresso dall’Utente con una o più di una delle seguenti modalità:</p>
<ul>
<li><strong>Mediante specifiche configurazioni del browser</strong> utilizzato o dei relativi programmi informatici utilizzati per navigare le pagine che compongono il Sito.</li>
<li><strong>Mediante modifica delle impostazioni</strong> nell’uso dei servizi di terze parti</li>
</ul>
<p>Entrambe queste soluzioni potrebbero impedire all’utente di utilizzare o visualizzare parti del Sito.</p>
<p><strong>Siti Web e servizi di terze parti</strong></p>
<p>Il Sito potrebbe contenere collegamenti ad altri siti Web che dispongono di una propria informativa sulla privacy che può essere diverse da quella adottata da www.mio.com e che che quindi <strong>non risponde</strong> di questi siti.</p>
<hr />
<h2>Cookie utilizzati da www.example.org</h2>
<p>A seguire la lista di cookie tecnici e di analytics utilizzati da questo Sito:</p>
<ul>
<li>cookiebello</li>
<li>cookiefresco</li>
</ul>
<div></div>
<hr />
<p>Come disabilitare i cookie mediante configurazione del browser</p>
<p><strong>Chrome</strong></p>
<ol>
<li>Eseguire il Browser Chrome</li>
<li>Fare click sul menù  presente nella barra degli strumenti del browser a fianco della finestra di inserimento url per la navigazione</li>
<li>Selezionare <strong>Impostazioni</strong></li>
<li>Fare clic su <strong>Mostra Impostazioni Avanzate</strong></li>
<li>Nella sezione “Privacy” fare clic su bottone “<strong>Impostazioni contenuti</strong>“</li>
<li>Nella sezione “Cookie” è possibile modificare le seguenti impostazioni relative ai cookie:
<ul>
<li>Consentire il salvataggio dei dati in locale</li>
<li>Modificare i dati locali solo fino alla chiusura del browser</li>
<li>Impedire ai siti di impostare i cookie</li>
<li>Bloccare i cookie di terze parti e i dati dei siti</li>
<li>Gestire le eccezioni per alcuni siti internet</li>
<li>Eliminazione di uno o tutti i cookie</li>
</ul>
</li>
</ol>
<p>Per maggiori informazioni visita la <a href="https://support.google.com/accounts/answer/61416?hl=en" target="_blank" rel="nofollow">pagina dedicata</a>.</p>
<p><strong>Mozilla Firefox</strong></p>
<ol>
<li>Eseguire il Browser Mozilla Firefox</li>
<li>Fare click sul menù  presente nella barra degli strumenti del browser a fianco della finestra di inserimento url per la navigazione</li>
<li>Selezionare <strong>Opzioni</strong></li>
<li>Seleziona il pannello <strong>Privacy</strong></li>
<li>Fare clic su <strong>Mostra Impostazioni Avanzate</strong></li>
<li>Nella sezione “Privacy” fare clic su bottone “<strong>Impostazioni contenuti</strong>“</li>
<li>Nella sezione “<strong>Tracciamento</strong>” è possibile modificare le seguenti impostazioni relative ai cookie:
<ul>
<li>Richiedi ai siti di non effettuare alcun tracciamento</li>
<li>Comunica ai siti la disponibilità ad essere tracciato</li>
<li>Non comunicare alcuna preferenza relativa al tracciamento dei dati personali</li>
</ul>
</li>
<li>Dalla sezione “<strong>Cronologia</strong>” è possibile:
<ul>
<li>Abilitando “Utilizza impostazioni personalizzate” selezionare di accettare i cookie di terze parti (sempre, dai siti più visitato o mai) e di conservarli per un periodo determinato (fino alla loro scadenza, alla chiusura di Firefox o di chiedere ogni volta)</li>
<li>Rimuovere i singoli cookie immagazzinati</li>
</ul>
</li>
</ol>
<p>Per maggiori informazioni visita la <a href="https://support.mozilla.org/en-US/kb/enable-and-disable-cookies-website-preferences" target="_blank" rel="nofollow">pagina dedicata</a>.</p>
<p><strong>Internet Explorer</strong></p>
<ol>
<li>Eseguire il Browser Internet Explorer</li>
<li>Fare click sul pulsante <strong>Strumenti</strong> e scegliere <strong>Opzioni Internet</strong></li>
<li>Fare click sulla scheda <strong>Privacy</strong> e nella sezione Impostazioni modificare il dispositivo di scorrimento in funzione dell’azione desiderata per i cookie:
<ul>
<li>Bloccare tutti i cookie</li>
<li>Consentire tutti i cookie</li>
<li>Selezione dei siti da cui ottenere cookie: spostare il cursore in una posizione intermedia in modo da non bloccare o consentire tutti i cookie, premere quindi su Siti, nella casella Indirizzo Sito Web inserire un sito internet e quindi premere su Blocca o Consenti</li>
</ul>
</li>
</ol>
<p>Per maggiori informazioni visita la <a href="http://windows.microsoft.com/it-it/windows-vista/block-or-allow-cookies" target="_blank" rel="nofollow">pagina dedicata</a>.</p>
<p><strong>Safari 6</strong></p>
<ol>
<li>Eseguire il Browser Safari</li>
<li>Fare click su <strong>Safari</strong>, selezionare <strong>Preferenze</strong> e premere su <strong>Privacy</strong></li>
<li>Nella sezione <em>Blocca Cookie</em> specificare come Safari deve accettare i cookie dai siti internet.</li>
<li>Per visionare quali siti hanno immagazzinato i cookie cliccare su <strong>Dettagli</strong></li>
</ol>
<p>Per maggiori informazioni visita la <a class="broken_link" href="http://support.apple.com/kb/ph11913" target="_blank" rel="nofollow">pagina dedicata</a>.</p>
<p><strong>Safari iOS (dispositivi mobile)</strong></p>
<ol>
<li>Eseguire il Browser Safari iOS</li>
<li>Tocca su <strong>Impostazioni</strong> e poi <strong>Safari</strong></li>
<li>Tocca su <strong>Blocca Cookie</strong> e scegli tra le varie opzioni: “Mai”, “Di terze parti e inserzionisti” o “Sempre”</li>
<li>Per cancellare tutti i cookie immagazzinati da Safari, tocca su <strong>Impostazioni</strong>, poi su <strong>Safari</strong> e infine su <strong>Cancella Cookie e dati</strong></li>
</ol>
<p>Per maggiori informazioni visita la <a href="http://support.apple.com/kb/HT1677?utm_source=Agillic%20Dialogue" target="_blank" rel="nofollow">pagina dedicata</a>.</p>
<p><strong>Opera</strong></p>
<ol>
<li>Eseguire il Browser Opera</li>
<li>Fare click sul Preferenze poi su Avanzate e infine su Cookie</li>
<li>Selezionare una delle seguenti opzioni:
<ul>
<li>Accetta tutti i cookie</li>
<li>Accetta i cookie solo dal sito che si visita: i cookie di terze parti e che vengono inviati da un dominio diverso da quello che si sta visitando verranno rifiutati</li>
<li>Non accettare mai i cookie: tutti i cookie non verranno mai salvati</li>
</ul>
</li>
</ol>
<p>Per maggiori informazioni visita la <a href="http://windows.microsoft.com/it-it/windows-vista/block-or-allow-cookies" target="_blank" rel="nofollow">pagina dedicata</a>.</p>
<hr />
<h2>Come disabilitare i cookie di servizi di terzi</h2>
<ul>
<li><a href="http://www.google.com/ads/preferences/?hl=it" rel="nofollow">Servizi di Google</a></li>
<li><a href="https://www.facebook.com/help/cookies?ref_type=sitefooter" rel="nofollow">Facebook</a></li>
<li><a href="https://support.twitter.com/articles/20170519-uso-dei-cookie-e-di-altre-tecnologie-simili-da-parte-di-twitter#" rel="nofollow">Twitter</a></li>
</ul>
<hr />
<p>Questa pagina è visibile, mediante link in calce in tutte le pagine del Sito ai sensi dell’art. 122 secondo comma del D.lgs. 196/2003 e a seguito delle modalità semplificate per l’informativa e l’acquisizione del consenso per l’uso dei cookie pubblicata sulla Gazzetta Ufficiale n.126 del 3 giugno 2014 e relativo registro dei provvedimenti n.229 dell’8 maggio 2014.</p>
<p>Inoltre puoi leggere la nostra informativa sulla privacy da qui <a href="http://example.org/privacy">privacy</a></p>

<p>Questi cookie, inviati sempre dal nostro dominio, <strong>sono necessari a visualizzare correttamente il sito</strong> e in relazione ai servizi tecnici offerti, verranno quindi <strong>sempre utilizzati e inviati</strong>, a meno che l’utenza non modifichi le impostazioni nel proprio browser (inficiando così la visualizzazione delle pagine del sito).</p>
<span style="font-size: 12pt;">
<br style="margin: 0px;">
<span style="font-size: 12pt;">Per eliminare i cookie dal browser Internet del proprio smartphone/tablet, è necessario fare riferimento al manuale d'uso del dispositivo. </span>
</p>

**Comment by vannaccirere** [comment]
@iusondemand  @Gix075  @PixedBo  @akybaud @andreaperugia @lmbuffetti @Saladino79 @seosmart ho caricato una paginetta html nella directory principale, Ovviamente poi a questa pagina vanno inseriti i link a tutti i servizi terzi aggiuntivi (analytics, disqus etc.) chiuderei l'issue entro Lunedi

**Comment by Gix075** [comment]
@vannaccirere Hai fatto modifiche al testo rispetto al vecchio file?

**Comment by vannaccirere** [comment]
si, ma solo su www.miosito.com e tolto il link alle immagini

**Comment by vannaccirere** [comment]
ho inserito www.example.org e ho tolto una parte doppia nel finale

**Comment by Gix075** [comment]
Allora sostituirei www.example.org con il placeholder standard  [[URL SITO]] che è quello che abbiamo usato in tutti gli altri file e passerei il questo testo direttamente in "docs/md/cookie-policy/informativa-estesa.md

Che ne dici?

**Comment by vannaccirere** [comment]
si, perfetto, mi sembra che tu gia l'abbia caricato se non erro

**Comment by Gix075** [comment]
Si però ho caricato il vecchio, se hai fatto modifiche lo ricarico.

**Comment by vannaccirere** [comment]
ok

**Comment by Gix075** [comment]
Inserito nella dir "docs/cookie-policy/md/informativa-estesa.md"

**Comment by akybaud** [comment]
Io non ho ancora avuto risposte da quel conoscente che vi dicevo. A questo
punto gli rimando la versione aggiornata e gli sollecito risposta.
Buona giornata a tutti
 Il 29/Mag/2015 00:07, "Gix075" notifications@github.com ha scritto:

**Comment by iusondemand** [comment]
Vedo tanti usare testi mokto lunghi. Seguendo questa impostazione sembra interessante come punto di partenza. Non ho visto info su elenco dei cooki propri e su cookiechouses per gli embed terzi che vanno elencati. Pitreste seguire la checklist che ho messo su www.iusondemand.com tra le ultime news

**Comment by akybaud** [comment]
Ciao ragazzi. Ho appena ricevuto le considerazioni sul testo (versione di
qualche giorno fa) da quel conoscente che vi dicevo.

## Ve le riporto qui:

mi sono letto con più attenzione il testo che avete predisposto e ti giro
le mie considerazioni.

Il testo è molto articolato sotto l’aspetto tecnico, però, a mio giudizio,
finisce per diventare un po’ lungo e, in alcuni punti, ripetitivo. Premesso
che, in genere, quasi nessuno si prenderà la briga di leggere queste
informative, in ogni caso è bene che l’informativa sia il più possibile
agevole da leggere e comprensibile. Secondo me, è sufficiente che una sola
volta si dica quali siano i cookie tecnici, di profilazione e di terze
terze parti effettivamente presenti sul sito, descrivendone le funzionalità
e, per i siti di terze parti, inserire i link per accedere alle pagine
delle relative informative e consensi.

Non mi è poi chiara la distinzione fra cookie analitici e cookie di analisi
di servizi di terze parti che voi fate, mentre, invece, a mio giudizio,
mentre i cookie analiti cd. di prima parte, cioè del proprietario del sito,
non necessitano di consenso, i Google Analytics, per precauzione, io
continuo a considerarli di terza parte e, quindi, il consiglio che do è di
inserire in loro presenza il banner in home page per poter dare o meno il
consenso. Quando ci sarà il fatidico chiarimento da parte del garante,
vedremo che interpretazione darà.

Per quanto riguarda la parte sulle icone e preferenze espresse nei social
network, confesso la mia ignoranza tecnica, per cui sinceramente non saprei
come considerarli.

Ad un certo punto voi dite chewww.mio.com, secondo la normativa vigente,
non è tenuto a chiedere consenso per i cookie tecnici e di analytics, in
quanto necessari a fornire i servizi richiesti. E’ senz’altro corretto che
in questi casi non ci voglia il consenso (salvo che, per quanto detto
prima, per i Google Analytics), però, con riferimento agli analitici, non
direi che questi ultimi sono necessari a fornire i servizi richiesti.

In merito poi alle modalità di esprimere il consenso, occorre esplicitare
che il consenso viene dato implicitamente anche chiudendo il banner
contenente l’informativa breve, scorrendo la home page(c.d. scroll down) o
cliccando qualunque suo elemento.

---

Il 29/Mag/2015 08:11, "Valentino Spataro" notifications@github.com ha
scritto:

**Comment by iusondemand** [comment]
fantastico. sottoscrivo tutto. E' esattamente quello che ho finito di fare pochi minuti fa. Guardate come funziona: http://www.civile.it/cookie.php
Praticamente ho unito la libreria javascript forkata aggiungendo anche l'evento scroll; poi alla libreria php che mi sono installato sul sito ho detto di controllare il cookie. Se c'e', mostra tutto.

Ho modularizzato tutto da far paura, e sembra andare. Che ne dite ? Potete prendere spunto dalla mia policy, naturalmente. Se non erro sul sito ho licenza creative commons.

Ascolta, io lo voglio il nome del tuo conoscente :-), me lo puoi mandare a www.iusondemand.com/mail ? o facebook/valentino.spataro .

A volte un avvocato per cose di internet mi serve, anche se ne ho gia' alcuni (che pero' stavolta non hanno seguito il tema).

**Comment by Gix075** [comment]
Purtroppo il testo in questione è stato ritirato. Quindi io ne stavo riscrivendo uno in velocità. Non so se possa andare bene. Forse come dite ci sono soluzioni possibili più snelle. 

Il file è questo https://github.com/FattiDiCookies/italianPrivacyPolicy/blob/master/bozze/cookie-informativa-estesa-new.md 

Io chiederei a chiunque del team di buttare giù qualche bozza (magari anche riscrivendo/modificando direttamente la mia), seguendo le indicazioni di @akybaud e @iusondemand

**Comment by vannaccirere** [comment]
Valentino, lavoro fa paura!!!!

**Comment by iusondemand** [comment]
ciao ragazzi. Per non farmi influenzare ho scritto qualcosa partendo solo dalla mia checklist. Il mio testo e' tutto originale, l'ho linkato sopra, potete usarlo :-)
Una cosa che torna utile sicuramente e' un database (anche json o csv):
nome servizio, link privacy o cookie policy, link a modulo consenso.
Youronlinechoises dovrebbe bbastare, ma sarebbe utile e farebbe informaione

**Comment by iusondemand** [comment]
vi segnalo questo link. Ancora piu' permissivo su embed social tipo facebook, perche' a livello europeo espressamente sono stati semplificati dal gruppo art 29: http://www.alessandrodelninno.it/upload/art_articoli/documenti/00000068.pdf
