### ISSUE TITLE
Disabilitare analytics sul proprio browser

### ISSUE THREAD

**Issue by PixedBo** [FattiDiCookies/italianPrivacyPolicy#31]
Potrebbe essere utile mettere il link al componente aggiuntivo che disabilita analytics? Vedo che molte aziende (estere) che seguo lo stanno mettendo:

https://tools.google.com/dlpage/gaoptout?hl=en=GB]

**Comment by 2autunni** [comment]
secondo me sì... è una info in più che dai all'utente finale

**Comment by Gix075** [comment]
Aggiungo subito

**Comment by Gix075** [comment]
Ho aggiunto il link alla parte di analytics.
Chiudo la issue, se serve riaprite pure.
