### ISSUE TITLE
Tool di compilazione dinamica delle policy

### ISSUE THREAD

**Issue by Gix075** [FattiDiCookies/italianPrivacyPolicy#32]
@iusondemand @2autunni  @hmtechnology  @vannaccirere @Saladino79 @akybaud @PixedBo  @LenusMedia @lmbuffetti @andreaperugia @lidialab e tutti gli altri

Ho appena terminato la prima stesura del plugin jquery per la compilazione automatica delle policy. Il plugin genera sia la privacy che la cookie policy, quest'ultima in forma modulare per quanto riguarda i servizi. Tutto funziona con un solo json di configurazione (valido di per entrambe le policy).

https://github.com/FattiDiCookies/italianPrivacyPolicy/tree/master/fdc-tool

Il sistema funziona in questo modo:
- NOI scriviamo i testi in formato md
- NOI generiamo i formati html usando Grunt (un colpo da linea di comando e abbiamo tutti i file)
- L'UTENTE scarica il pacchetto "tool" che contiene plugin e documenti html.
- L'UTENTE compila il file di configurazione e lancia il plugin jquery es: **$(elemento).fdCookieLaw({page: "cookie"});** ottenendo la pagina personalizzata

Ancora manca la parte del banner per l'informativa breve. Credo che prenderò un po' di codice da @iusondemand che l'ha già postato. Ovviamente è tutto migliorabile, quindi vi invito a dargli un'occhiata e vediamo di migliorarlo, fare i vari debug, ecc...

**Comment by akybaud** [comment]
Mizzega ragazzi. Si toccano livelli altissimi qui.
Complimenti!
 Il 30/Mag/2015 15:13, "Gix075" notifications@github.com ha scritto:

**Comment by Gix075** [comment]
Grazie! Lo hai provato?

**Comment by akybaud** [comment]
Non ancora perché sono ad un evento oggi
Ma lo proverò appena riesco a metterci le mani
Il 30/Mag/2015 16:14, "Gix075" notifications@github.com ha scritto:

**Comment by vannaccirere** [comment]
A Vicenza faremo una giornata proprio per parlare della cookielaw e del casini generato, non proptrò non citare questo gruppo. Il lavoro è super. Contribuiamo a mantenere il web un luogo dove poter esprimere in piena libertà la propria opinione :) #WOR

**Comment by Gix075** [comment]
@vannaccirere grandi! Non potrò essere lì, ma sono con voi!

**Comment by iusondemand** [comment]
da brivido. Faccio il punto per quello che riguarda quello che ho messo online:
www.civile.it/cookie.php l'informativa estesa piu' aggiornata
http://www.civile.it/cookiechoices.js il javascript che prende anche un click o scroll da body.

Infine: dobbiamo incontrarci tutti. Non sono un grande organizzatore di eventi, sono su Milano ( http://www.iusondemand.com/where ), ma dobbiamo fare un incontro fisico. C'e' qualcuno che vuole aiutarmi ? Alla peggio metto a disposizione la mia sede a Milano, in una decina ci stiamo, di piu' ci si organizza.

@Gix075  @2autunni @hmtechnology @vannaccirere @Saladino79 @akybaud @PixedBo @LenusMedia @lmbuffetti @andreaperugia @lidialab e tutti gli altri

**Comment by akybaud** [comment]
Ottima idea quella dell'evento off-line
 Il 30/Mag/2015 17:19, "Alessandro N" notifications@github.com ha scritto:

**Comment by vannaccirere** [comment]
l'azienda con cui collaboro più assiduamente mi ha chiesto di fare una relazione sulla tematica a (Vicenza), sarebbe bello presentare questo progettino e i nomi di chi ha sviluppato il progetto , il giusto compenso per ore passate a smanettare

**Comment by vannaccirere** [comment]
Però sarebbe bello incontrarsi tutti
@iusondemand @2autunni @hmtechnology @vannaccirere @Saladino79 @akybaud @PixedBo @LenusMedia @lmbuffetti @andreaperugia @lidialab

**Comment by vannaccirere** [comment]
@iusondemand sono disposto ad aiutarti nell'organizzazione (è stata il mio lavoro per 11 anni :) ) penso che potremmo parlare di progetti molto interessanti.

**Comment by lidialab** [comment]
Vicenza? :) Quando?

**Comment by vannaccirere** [comment]
@lidia #aperitvidigitali teoricamente tra due settimane, ti terrò aggiornata

**Comment by Gix075** [comment]
@vannaccirere perché non fate un Hangout live?

**Comment by iusondemand** [comment]
Ottimo, lasciam i tui contatti i miei su www.iusondemand.com/mail

**Comment by akybaud** [comment]
Per vederci live io ci sono, anche se non ho potuto essere molto di aiuto.
Io arrivo da Torino quindi Milano mi andrebbe bene.
L'unica cosa sono i tempi, direi non prima di inizio luglio :(
Il 30/Mag/2015 18:59, "Alessandro N" notifications@github.com ha scritto:

**Comment by Gix075** [comment]
Ho aggiornato ulteriormente il plugin jQuery.
Adesso il tool gestisce anche il banner con relativa accettazione della policy. La policy può essere accettata anche on-scroll se viene attivata l'opzione nel file di configurazione.
Il testo dell'informativa breve (il banner) viene generato automaticamente scegliendo cosa includere tra cookie tecnici, cookie di profilazione di terzi (i servizi) e embed

Ho cercato di racchiudere tutti i parametri del plugin nel file di configurazione, ma alcune opzioni sono sovrascrivibili utilizzando le opzioni del plugin (questo per quelle parti che potrebbero dover essere personalizzate da pagina a pagina).

Non l'ho ancora testato molto e sicuramente qualcosa mi è sfuggita. Datemi una mano facendo delle prove per vedere se ci sono bug.

Cercherò di scrivere una prima documentazione il prima possibile.

P.S.: I testi non sono aggiornati all'ultima versione e quelli dei banner sono miei. Ovviamente andranno tutti sostituiti.

**Comment by hmtechnology** [comment]
non ho ben compreso come si attiva per testarlo sorry:/

**Comment by Gix075** [comment]
Lo so che senza documentazione è difficile smanettarci a dovere. Se scarichi il pacchetto fdc-tool dentro c'è un file demo.html e da lì un'idea puoi fartela. Comunque è un comune plugin jQuery che si attiva con 
$('body').fdCookieLaw();  // così mostra solo il banner
$('#elmID').fdCookieLaw({page:"cookie"});  // stampa la cookie policy nell'elemento scelto
$('#elmID').fdCookieLaw({page:"privacy"});  // stampa la provacy policy nell'elemento scelto

Le configurazioni le fai da config.json

**Comment by akybaud** [comment]
Domani lo provo anche io
Il 31/Mag/2015 22:03, "Gix075" notifications@github.com ha scritto:

**Comment by 2autunni** [comment]
scusa @Gix075 sto provando a usare grunt,
su una opensuse 13.1 con 
grunt-cli v0.1.13
grunt v0.4.5

ottengo questi errori
Loading "clean.js" tasks...ERROR
Error: Cannot find module 'rimraf'
Loading "dom_munger.js" tasks...ERROR
Error: Cannot find module 'cheerio'
Loading "string-replace.js" tasks...ERROR
Error: Cannot find module 'async'
Warning: Task "clean" not found. Use --force to continue.

uso una versione troppo vecchia di grunt?

**Comment by Gix075** [comment]
Hai fatto **npm install** dalla console nella directory del progetto?

**Comment by 2autunni** [comment]
fatto npm install,  
scusa sono alle prime prove con grunt.... 
ora compila solo che mi da un warning

Running "dom_munger:clean_ids" (dom_munger) task
 Dest cannot be specified with multiple src files.

**Comment by Gix075** [comment]
Sì scusa, è un problema dato da un plugin. Usa **Grunt --force**

**Comment by 2autunni** [comment]
ok, sto già usando il --force... scrivo queste istruzioni in un file dentro fdc-tool ?

**Comment by Gix075** [comment]
Sì facciamolo. Mettiamolo nella root dato che il file Grunt è lì, che ne dici?

**Comment by Gix075** [comment]
Chiudo alcune vecchie issue per fare un po' di pulizia e focalizzare sulle nuove. Se serve riaprite.
