### ISSUE TITLE
Proposta di riorganizzazione repository

### ISSUE THREAD

**Issue by Gix075** [FattiDiCookies/italianPrivacyPolicy#33]
Dato che stiamo andando molto avanti nello sviluppo del progetto e si avvicina il momento del rilascio di una prima versione beta, direi che forse è il caso di dare una struttura più organizzata al repository.

Visto che poi il progetto dovrà essere rilasciato pubblicamente e dovrà quindi essere caricato su Bower e simili per un'istallazione più semplice e veloce, direi di suddividere il repository in due directory principali: **"dev"** e **"dist"**.

**"dev"** sarà la directory di sviluppo. 
Noi dovremo lavorare solo dentro questa directory generando file di testo (le policy) esclusivamente in formato .md, mentre per i file del tool utilizzeremo i linguaggi e formati necessari

**"dist"** sarà invece la directory di rilascio
Qui andranno solo i file per la distribuzione (quindi quelli che dovrà usare l'utente finale) e che saranno generati usando _Grunt_. Ogni update di **"dist"** dovrà corrispondere ad un numero di versione di rilascio.

Nella root del repository rimarranno quindi solo i file di Bower e Grunt, più il readme e la licenza.

Di seguito un disegnino del repository per come lo immagino.

```
├── dev/
│   ├── bozze/  (directory per upload di bozze)
│   ├── docs/   (directory per lo sviluppo dei file di testo)
│   │     └── md/
│   ├── tool/ (directory per lo sviluppo del tool di config)
│         └── css/
│         └── docs/
│         └── js/
│         └── demo.html
│ 
├── dist/
│   ├── docs/ (esportazione dei documenti)
│   │     └── md/
│   │     └── html/
│   ├── tool/ (esportazione tool)
│         └── css/
│         └── docs/
│         └── js/
│         └── demo.html
│ 
├── bower.json
├── Gruntfile.js
├── package.json
├── LICENSE
└── README.md
```

Voi che ne pensate?
Attendo vostri pareri.

**Comment by 2autunni** [comment]
Scusa, ma visto che siamo su GIT  invece di avere le cartelle dev e dist non sarebbe meglio avere due rami dev e master... e le directory che non devono finire rilasciate lasciarle vivere solo in dev?

Forse poi sarebbe utile in un futuro avere due repository: uno per la stesura dei documenti (che potrebbero così essere usati per altri progetti es. plugin wordpress ) e uno per la parte software

Ovviamente tutto IMHO

Inoltre ci sto pensando da un poco: ma se abbiamo i file md, perché non convertirli al volo con js?  togliendo la dipendenza da grunt?

**Comment by Gix075** [comment]
I due repository forse potrebbero essere meglio, però ho visto che spesso i progetti opensource distribuiscono anche la directory di sviluppo per eventuali pull-request e quindi mantenere un solo repository forse incasina un po' meno, ma anche qui questo è quello che penso io e mi rimetto alla maggioranza. 

Per quello che riguarda la conversione con js l'ho evitata solo perché avendo già gli html mi sembrava un passaggio in più.
Ho implementato Grunt un po' perché ce l'ho per deformazione ;-) , un po' perché dovendo fare i vari pacchetti dist (minimizzazioni css e js, ecc...) e le esportazioni in html, json, ecc... da distribuire mi sembrava una soluzione comoda e abbastanza standard. 

Ovviamente è tutto solo una mia ipotesi. Aperto ad ogni ipotesi.

P.S.: l'idea del plugin WP mi piace molto. Tu potresti scriverlo?

**Comment by 2autunni** [comment]
In realtà di solito sviluppo per drupal, però mi stuzzicava l'idea di  provare a fare il plugin per wp... non appena trovo un po' di tempo ...

**Comment by Gix075** [comment]
@2autunni io invece con joomla, ah ah, però direi che si potrebbero prendere  tutti in considerazione ... ovviamente in futuro!
Hai dato un'occhiata al tool?

**Comment by 2autunni** [comment]
non ancora cerco di farlo stasera

**Comment by iusondemand** [comment]
Cerco chi possa per wordpress. Tenuamo anche una versione fenerica.

Mi piace quanto dice @2autunni ma sarei piu' per due directory

**Comment by raynor85** [comment]
Condivido l'idea di mantenere grunt, è un tool ottimo che permette di velocizzare molto il lavoro; inoltre nella task di default ho aggiunto la compilazione less e l'estensione jshint, con la quale si può controllare la stesura dei javascript.
Condivido la necessità di organizzare meglio la struttura dei file, lo stavo per proporre quando ho visto questo post, e penso che tale task abbia la priorità siccome è veramente confuso per l'utente medio includere il plugin. Se volete posso pensarci io al refactoring.

**Comment by iusondemand** [comment]
se @raynor85  vuole metterci le mani per me ok. fate,c ondivido tutto !
