### ISSUE TITLE
eliminare [[Nome sito]] dai frammenti per i services

### ISSUE THREAD

**Issue by 2autunni** [FattiDiCookies/italianPrivacyPolicy#34]
Toglierei dai frammenti dei servizi tutti i riferimenti a [[NOME SITO]], es 
qui https://github.com/FattiDiCookies/italianPrivacyPolicy/blob/master/docs/cookie-policy/md/services/google-analytics.md

Il servizio di statistiche Google Analytics utilizzato da [[NOME SITO]] è un sistema in grado di tracciare il comportamento degli utenti durante la navigazione. 

lo farei diventare 

Il servizio di statistiche Google Analytics utilizzato da questo sito  è un sistema in grado di tracciare il comportamento degli utenti durante la navigazione. 

In fondo questi frammenti sono caricati nella policy estesa e in cima c'è il nome del sito

che ne dite?

**Comment by Gix075** [comment]
Se non ci sono problemi legali nel farlo per me è ok.

**Comment by hmtechnology** [comment]
forse lo diceva per una migliore controllabilità dei dati ? d'accordo anche io cmq

**Comment by Gix075** [comment]
Il tool li sostituisce automaticamente, ma per chi li copia e incolla forse è meglio toglierli. Se non ci sono ulteriori pareri contrari all'eliminazione domani li eliminiamo tutti.

**Comment by 2autunni** [comment]
volevo eliminarli per rendere più scorrevole il discorso...
se va bene mi occupo io di cambiare i testi.

**Comment by Gix075** [comment]
@2autunni ok fai tu.

**Comment by hmtechnology** [comment]
Se si leva [[NOME SITO]], forse a inizio documento bisogna scrivere qualcosa come:

Benvenuto su www.example.com ("Example", "Questo Sito").

Un pò come fa AddThis qui http://www.addthis.com/tos per fissare una correlazione fra i due termini. A me cmq non dispiace neanche tenere NOME SITO ehehe

**Comment by Gix075** [comment]
Concordo. In più infatti va fatta anche un minimo di revisione del testo della policy per renderla coerente in questi dettagli.

**Comment by hmtechnology** [comment]
Pensiamoci su...o hai già levato tutto ? xD

Nel frattempo chiudo milestone Adsense e AddThis!

**Comment by Gix075** [comment]
Credo che @2autunni abbia già fatto pulizia.
Chiudi pure le milestone

**Comment by hmtechnology** [comment]
Ho notato che c'è un problema (che è forse quello che dicevate quando parlavate di dover riformulare le frasi) abb serio con l'utilizzo della formula "Questo sito" ovvero che nelle frasi dei servizi non si capisce clamorosamente se è riferito al sito del proprietario o del servizio di cui si sta parlando (sharethis, addthis, etc)! Secondo me è un limite abbastanza grosso.
