### ISSUE TITLE
licenze

### ISSUE THREAD

**Issue by 2autunni** [FattiDiCookies/italianPrivacyPolicy#35]
Ciao, 
il software se non sbaglio è già sotto GPL, possiamo mettere sotto cc o altra licenza libera i testi che produciamo?

Forse come diceva qualcuno in qualche issue precedente è il caso di scrivere un disclaimer da allegare ai testi in cui diciamo che li si usa a proprio rischio e pericolo...

**Comment by Gix075** [comment]
Certamente, per ora quello che c'è è il file generico che mette GitHub, quindi possiamo cambiare come vogliamo. 

Per il disclaimer credo anche io sia assolutamente necessario!

Chi lo scrive?

**Comment by iusondemand** [comment]
Eccomi
Io amo la mit, o la lgpl, gpl avolte la sento stretta. 

Per il disclaimer:

Questi materiali, testi, link e software, vanno considerati come modelli in divenire e sono stati realizzati con il contributo spontaneo dei vari autori che hanno partecipato. Non e' una consulenza legale e ognuno dovra' adattarli e valutare autonomamente come correggerli, condividendo le proprie valutazioni per migliorarli. Si raccomanda di partecipare solo con contenuti originali perche' anche le istruzioni a testi di legge con contributo creativo sono soggette a diritto d'autore e possono essere usate solo specificando per finalita' di studio, ma non nei materiali finali.

**Comment by iusondemand** [comment]
Ah: sconsiglio licenza cc per il software

**Comment by 2autunni** [comment]
infatti direi licenza (mit, lgpl o gpl ) per il software 
cc per i testi

il disclaimer lo piazzerei nel readme generale del progetto, e la pubblicherei su una pagina del sito del progetto, inserendo in ogni policy generata un link a quella pagina

**Comment by iusondemand** [comment]
Ok @2autunni 
Per la licenza
Mit tutto libero
Gpl vincolo ai derivati
Lgpl vincolo unferiore 

Sbaglio ?

Proposte ? Io indeciso tra mit o lgpl

**Comment by Gix075** [comment]
Per me per i software MIT è ok! Per i documenti direi CC totalmente libera.

**Comment by 2autunni** [comment]
per i documenti proporrei cc condividi allo stesso modo

**Comment by duarme** [comment]
Concordo anche io su MIT + CC libera.

**Comment by Gix075** [comment]
Forse per i testi sarebbe meglio CC condividi allo stesso modo come proposto da @2autunni almeno eventuali ditte non possono prenderci i testi ed inserirli in progetti a pagamento.

**Comment by iusondemand** [comment]
Allora cc nc , cc noj basta. Per me va benone. Ricordate che debomo cmq sempre indiccare gli autori si può sottolineare.

**Comment by iusondemand** [comment]
Software licenza mit anche per me

**Comment by Gix075** [comment]
Al momento ho assegnato MIT al software e **CC Attribuzione - Non Commerciale - Non opere derivate** per proteggere il lavoro di chi ha scritto i testi da possibili furti da parte di coloro che intendono rivendere servizi simili. Dico questo perché così mi è stato riferito.

Poi si potrebbe pensare ad un tipo di licenza http://www.creativecommons.it/CCPlus 

Chiudo questa issue. Se ci sono cose da aggiungere riapriamo.
