### ISSUE TITLE
FattiDiCookies Website

### ISSUE THREAD

**Issue by Gix075** [FattiDiCookies/italianPrivacyPolicy#36]
Sperando in una collaborazione attiva, adesso abbiamo anche un repository per la pagina web di FattiDiCookie. Ho caricato html5 boilerplate giusto per mettere online una pagina... senza cookie. 

Personalmente preferieri continuare a lavorare sul progetto, ma se qualcuno ha voglia di sviluppare una paginetta, che si diverta pure!

Il repository è questo:
https://github.com/FattiDiCookies/FattiDiCookies.github.io

Il link del sito è questo:
http://fattidicookies.github.io/

**Comment by iusondemand** [comment]
Ok. Com struttura penso a:

Il progetto e chi siamo e partecipa e disclaimer
Le risorse legali ufficiali it e eu
Raccolta di link utili
Come seguirci e partecipare

**Comment by Gix075** [comment]
Se non ci sono cookie la policy non ci vuole giusto? Ormai è paranoia pura ;-)

**Comment by hmtechnology** [comment]
No, però serve comunque la privacy policy (in presenza di anche un solo Contact Form). E nessuno vieta di creare una sezione (sempre nell informativa privacy) in cui si dichiara che non si fa uso di cookie di alcun tipo, nè tecnico nè di profilazione.

**Comment by Gix075** [comment]
Ok, mi preoccupavo della pagina attuale, che è praticamente vuota. Per la versione futura ovviamente andranno inserite tutte le pagine, dato che almeno un analytics lo metteremo.

Ma qualcuno che ha voglia di farla c'è?

**Comment by hmtechnology** [comment]
la homepage del sito dici? certo. Serve un mini brief

**Comment by Gix075** [comment]
@hmtechnology avevi qualche idea per il brief, anche su come organizzarci ?

**Comment by hmtechnology** [comment]
Se riuscissimo a dare una risposta a queste domande, non per forza a mero scopo accademico (anzi), inizieremmo col piede giusto

1) Informazioni Generali
Nome del progetto:
URL corrente (o URL desiderato):
Contatti per questo progetto:
Data per il lancio del nuovo sito di destinazione:

2) Perche?
Qual è il problema che si spera di risolvere con questo progetto? Cosa si cerca di generare con questo progetto?

3) Chi?
Chi è il vostro utente / target di riferimento ? Qual è il target (età , livello di istruzione ... )

4) Valore
Perché i vostri utenti hanno bisogno di voi? Qual è il vostro vantaggio principale (per l’utente non per voi)? Cosa offrite di differente dalla concorrenza ? Come appare/deve apparire il vostro prodotto agli occhi dell’utente? Come utilizzeranno il sito i vostri utenti? Quali sono i loro obiettivi?

5) Percezione
Che cosa si desidera far risaltare agli occhi dei visitatori? Utile anche una lista di aggettivi che descrivono come si desidera che i visitatori percepiscano il nuovo sito. Elencare eventualmente URL di siti che vi piacciono. Cosa vi piace in particolare di questi siti ?

6) Contenuto
Ci sono contenuti esistenti da inserire nel sito o è necessario creare nuovi contenuti? Chi si occupa di scrivere il contenuto? Ci sono eventuali immagini o contenuti che desiderate utilizzare nel sito (logo , combinazioni particolari di colori, di navigazione, acronimi particolari , ecc) ?

7) Tecnologie
Ci sono tecnologie specifiche che desiderate utilizzare nel sito ? In caso affermativo, spiegare come queste tecnologie possono permettere di migliorare l'esperienza dell'utente. Eventuali esigenze di programmazione aggiuntive? 

8) Comunicazione
Come le persone ricercano e trovano attualmente informazioni simili a quelle trattate dal vosto sito web? 

9) Aggiornamento
Come si prevede di mantenere aggiornato ed attuale il contenuto del sito? Quanto spesso il contenuto del sito dovrebbe aggiornarsi di nuovi contenuti? Chi è responsabile per la creazione di nuovi contenuti e l’inserimento nel sito? Quale software siete disposti ad utilizzare per mantenere il sito aggiornato ?

10) Commenti / Note supplementari

**Comment by Gix075** [comment]
Chiudo per vecchiaia della issue, se serve riapriamo.
