### ISSUE TITLE
testo per disattivare i cookie nei browser per android

### ISSUE THREAD

**Issue by lidialab** [FattiDiCookies/italianPrivacyPolicy#37]
Scusate se apro un issue, spero sia corretto, ma non so come/dove segnalare la proposta di aggiungere anche le istruzioni per disattivare i cookie nei browser per android smartphone (appena posso verifico per i tablet ma credo proprio che siano uguali)

Inoltre utilizzando il tool ho visto che il titolo "Come disabilitare i cookie mediante configurazione del browser" è in piccolo.

---

Impostazioni dei cookie nel browser stock (predefinito) per Android:

   versione precedente a Lollipop (la mia però è una cyanogenmod e non ho trovato la pagina ufficiale nel web, domani cerco meglio)
    aprire il browser 
    premere il tasto menù 
    premere Impostazioni 
    premere Privacy e sicurezza 
    qui è possibile togliere la spunta dalla voce “Accetta cookie” per rifiutare tutti i cookie

   Lollipop: 
    aprire il browser 
    premere il tasto menù 
    premere Impostazioni 
    premere Privacy 
    qui è possibile togliere la spunta dalla voce “Accetta cookie” per rifiutare tutti i cookie

Chrome
    aprire il browser 
    premere il tasto menù 
    premere Impostazioni 
    premere Impostazioni sito 
    premere Cookie 
    qui è possibile 
        disattivare la voce "Cookie" per rifiutare tutti i cookie
            oppure
        togliere la spunta da "Consenti cookie di terze parti" per rifiutare solo i cookie di terze parti
Per maggiori informazioni visita la pagina dedicata (https://support.google.com/chrome/answer/2392971?hl=it)

Firefox
    aprire il browser 
    premere il tasto menù 
    premere Impostazioni 
    premere Privacy 
    premere Cookie 
    qui è possibile 
        scegliere "Disattivati" per rifiutare tutti i cookie
        scegliere "Attivi, esclusi di terze parti" per rifiutare solo i cookie di terze parti
Per maggiori informazioni visita la pagina dedicata (https://support.mozilla.org/it/kb/attivare-disattivare-cookie-firefox-android)

**Comment by Gix075** [comment]
Grazie @lidialab per me possiamo inserirlo. Attendo qualche parere ma entro domani vorrei inserirlo.
Grazie anche per la segnalazione del titolo, controllo subito.

**Comment by iusondemand** [comment]
Mi sembra utilissimo! Ora cerco chi per firefoxos

**Comment by hmtechnology** [comment]
Ottima! Servirebbe anche per Iphone per coprire grosso modo tutto il Mobile.

**Comment by Gix075** [comment]
Ho inserito i testi prodotti da @lidialab nella cookie policy
