### ISSUE TITLE
fdc-tool non genera elenco servizi

### ISSUE THREAD

**Issue by 2autunni** [FattiDiCookies/italianPrivacyPolicy#38]
Su firefox su linux aprendo il file demo_cookiePolicy.html non viene generato l'elenco dei servizi.

**Comment by Gix075** [comment]
Ora controllo, in effetti su Firefox non l'ho proprio testato. La console ti da errori?

**Comment by Gix075** [comment]
Ok il bug l'ho riscontrato anche su Firefox su Windows dove però l'ho fixato. Pubblico la fix (anche se nel file adesso sto lavorando al banner che è incompleto però)

**Comment by Gix075** [comment]
@2autunni ho committato il file corretto (almeno su Windows). Se puoi testalo ancora anche su Linux.

**Comment by 2autunni** [comment]
ora funziona su firefox linux, chiudo issue
