### ISSUE TITLE
AddThis

### ISSUE THREAD

**Issue by hmtechnology** [FattiDiCookies/italianPrivacyPolicy#39]
Testo per Informativa Estesa Cookie su AddThis (appartenente alla categoria degli Strumenti di Condivisione Sociale)
### AddThis

_AddThis_ è un sistema rilasciato da [http://www.addthis.com/](http://www.addthis.com/) che permette la facile condivisione dei contenuti di questo sito attraverso e-mail e i principali siti web di social network.
Il servizio _AddThis_ può permettere agli amministratori del sito **[[NOME SITO]]** di mostrare automaticamente pulsanti di condivisione diversi a seconda delle preferenze sociali degli utenti o di consultare statistiche in forma aggregata sul numero e sui contenuti delle condivisioni effettuate dagli utenti.
Il servizio _AddThis_ attraverso l'uso dei propri cookie colleziona dati sulla navigazione degli utenti anche al di fuori di questo sito. 
Il sito **[[NOME SITO]]** non utilizza il servizio _AddThis_ per la profilazione dell'utente in prima parte e non ha accordi con _AddThis_ per profilare in prima parte.
##### Link di riferimento
- [Privacy Policy](http://www.addthis.com/privacy/privacy-policy)
- [Opt-Out](http://www.addthis.com/privacy/opt-out)

**Comment by Gix075** [comment]
@hmtechnology eccezionale! Direi di sostituire [[NOME SITO]] con "questo sito" fin da subito, dato che sembriamo orientati a rimuoverlo da tutti i servizi. Per il resto mi sembra ok e da inserire. Intanto lo passo subito nel repository per via dei tempi stretti, ma lo metto comunque in approvazione da parte del team.

Se ci dovessero essere modifiche le apporteremo anche al file del repo.

**Comment by 2autunni** [comment]
mi sembra ok

**Comment by Gix075** [comment]
File aggiunto al repository. Ho sostituito i [[NOME SITO]]

**Comment by hmtechnology** [comment]
Eppure non sn convinto della rimozione del [[NOME SITO]], forse dava più aderenza e consistenza al tutto...ma va benissimo come preferite voi;)

**Comment by 2autunni** [comment]
non so, il mio era il tenativo di spostarci dal legalese a una forma scorrevole e amichevole...
certo che anche il "questo sito" ripetuto molte volte come ho fatto io  è brutto... non so
