### ISSUE TITLE
AdSense 

### ISSUE THREAD

**Issue by hmtechnology** [FattiDiCookies/italianPrivacyPolicy#40]
### Google AdSense

_Google AdSense_ è un sistema di gestione di banner pubblicitari offerto da Google, [http://www.google.com/adsense/](http://www.google.com/adsense/), che permette di selezionare e personalizzare il tipo di annunci da pubblicare sul proprio sito.
Il servizio _Google AdSense_ utilizza cookie per pubblicare annunci in relazione al comportamento degli utenti durante la navigazione in rete.
Il servizio _Google AdSense_ mette a disposizione un sistema di statistiche che consente di visualizzare il numero di impression e di click, i ricavi giornalieri e totali.
Questo sito non utilizza il servizio _Google AdSense_ per la profilazione dell'utente in prima parte e non ha accordi con _Google AdSense_ per profilare in prima parte.
##### Link di riferimento
- [Privacy](https://www.google.com/intl/it/policies/privacy/)
- [Pubblicità](http://www.google.com/policies/technologies/ads/)
- [Opt-Out](http://google.com/settings/ads/onweb/optout?hl=it)

**Comment by Gix075** [comment]
@hmtechnology stasera vai a mille! Ottimo lavoro direi! Anche in questo caso direi che per me può andare.

**Comment by hmtechnology** [comment]
:D Mi sentivo in colpa

Ho sistemato i 3 link finali, il primo forse è ripetuto da altre parti (Google Plus o altrove, nn saprei) perchè è quello generale di Google sulla Privacy, il secondo è specifico per la Pubblicità e il terzo è di Opt-Out (da inserire sempre, ove si trovi)

**Comment by Gix075** [comment]
Hai dato veramente un gran contributo oggi.
Ho aggiunto il file al repository.

**Comment by hmtechnology** [comment]
Grazie, spero di aumentare e essere costante..purtroppo sono cotto dopo tutto il giorno dietro ai cookie per lavoro, questo invece è un piacere. Ho visto nel repo, ho aggiunto il nome del cookie (DoubleClick) così siamo ancora piu precisi. Oltretutto mi pare che per i vari servizi, bisogna indicarlo il nome, magari non singolarmente ma se possibile sarebbe meglio.

Si potrebbe anche indicare, in fondo, per ogni servizio: Luogo del trattamento dei dati (ma a volte potrebbe essere difficoltoso trovare la sede) e Tipi di dati raccolti (principalmente Dati di navigazione e Cookie)

**Comment by Gix075** [comment]
Altri hanno detto che se questi dettagli sono reperibili dai link che mettiamo non serve elencarli, in più se non è possibile reperire un dato noi non possiamo farci niente.

**Comment by hmtechnology** [comment]
Ottimo allora, nn mettiamoli. Anche perchè sarebbe quasi sempre Dati di navigazione + Cookie e USA :D
