### ISSUE TITLE
test in locale con firefox e chrome

### ISSUE THREAD

**Issue by 2autunni** [FattiDiCookies/italianPrivacyPolicy#41]
Testando il progetto in locale con firefox sembra non funzionare.
Segnala che config.json è non well-formed.
In realtà il json va benissimo: il problema è che firefox e chrome supportano le  cross origin requests solo per il protocollo http e non per il protocollo file.
http://stackoverflow.com/questions/20041656

Due soluzioni (senza toccare il codice):
Usare un local server (ad esempio tramite python o php)
oppure fare le prive su un webserver online 
Aggiungo istruzioni a riguardo per gli sviluppatori nel file INSTRUCTIONS.md

**Comment by Gix075** [comment]
Scusatemi, colpa mia, davo la cosa per scontata. Ci sono comunque anche alcuni editor che permettono di lanciare preview come da server locale, uno di questi è [Brackets](http://brackets.io/) (editor orientato al frontend) ma ce ne sono anche altri.

**Comment by Gix075** [comment]
@2autunni  Il file di istruzioni mi sembra ottimo.

**Comment by 2autunni** [comment]
@Gix075 grazie, se ho tempo (oggi sto finendo di aggiornare policy su siti ) cerco di riportare il tutto su wiki 

Lascio aperta l'issue per gli altri, ma non lo considererei un baco

**Comment by Gix075** [comment]
Anche io oggi sono un po' impicciato e domani non ci sono proprio. Facciamo quello che possiamo. Sto mettendo nel wiki una prima bozza di documentazione (incompleta) del tool.

**Comment by 2autunni** [comment]
riportate le istruzioni per gli sviluppatori qui https://github.com/FattiDiCookies/italianPrivacyPolicy/wiki/Istruzioni-per-gli-sviluppatori 
ho messo anche due link su git nella home del wiki  e adesso linko le istruzioni per gli sviluppatori dalla home del wiki, aggiungo da tutte e due le parti il tuo suggerimento su brackets:
Qualcuno sa se atom fa la stessa cosa?

**Comment by Gix075** [comment]
Ottimo! Il progetto sta prendendo forma... e mi piace!

**Comment by Gix075** [comment]
Chiudo la issue segnalando la pagina del wiki:
https://github.com/FattiDiCookies/italianPrivacyPolicy/wiki/Istruzioni-per-gli-sviluppatori 

Per problemi con il tool che non siano già stati risolti in questa issue, aprirne una nuova.
