### ISSUE TITLE
Google e Privacy Policy

### ISSUE THREAD

**Issue by hmtechnology** [FattiDiCookies/italianPrivacyPolicy#42]
http://www.ansa.it/sito/notizie/tecnologia/internet_social/2015/06/01/googlepiu-controllo-privacy-e-sicurezza_ce1cb35b-2a0b-4b13-82fe-cef7d6ad33fe.html

D'ora in poi credo che questo link: https://myaccount.google.com/ possa essere inserito tra i link per i principali servizi di Google

**Comment by 2autunni** [comment]
e bello che arriva adesso dopo tutte la giornata passata a scrivere policy  ;)
Cmq si per i servizi google mi sembra ottimo metterlo, io però stasera non riesco

**Comment by Gix075** [comment]
Il bello è che l'utente deve registrasi su Google, ah ah! Cosi vedrai come profilano!
Comunque sì inseriamo il link tra i vari di google.

**Comment by Gix075** [comment]
Chiudo per vecchiaia della issue, se serve riapriamo.
