### ISSUE TITLE
dubbio su: disattivare i cookie in IOS

### ISSUE THREAD

**Issue by lidialab** [FattiDiCookies/italianPrivacyPolicy#43]
Vorrei segnalare che nel caso dei dispositivi IOS bisogna specificare che si va nelle impostazioni del dispositivo e poi si sceglie Safari (nell'app Safari non c'è bottone o menù, ma ammetto che non mi sono mai addentrata nel mondo apple l'ho solo cercato sul mio ipad)

**Comment by lidialab** [comment]
Nella mia policy ho fatto così:

Safari iOS 8/7 (dispositivi mobile)
    premere Impostazioni
    premere Safari
    premere Blocca Cookie e scegliere tra:  “Consenti sempre”, “Consenti solo dai siti web che visito”, “Consenti solo dal sito web attuale” oppure “Blocca sempre”
       ( in iOS 7 scegliere tra: “Mai”, ” Di terze parti e inserzionisti” oppure “Sempre” )

Per maggiori informazioni visita la pagina dedicata.
http://support.apple.com/it-it/HT1677

**Comment by lidialab** [comment]
anzi forse meglio mettere :
"aprire le Impostazioni del dispositivo"

**Comment by iusondemand** [comment]
Ciao, ben fatto :-) ci sono anche altre impostazioni pubblicitarie ora cge mi ci fai pensare

**Comment by lidialab** [comment]
Ciao Valentino, sì ci sono.
O almeno credo tu ti riferisca a do not track / navigazione anonima / potezione da monitoraggio

Internet Explorer : http://windows.microsoft.com/it-it/internet-explorer/ie-security-privacy-settings#ie=ie-11
Firefox : https://support.mozilla.org/it/products/firefox/protect-your-privacy
Chrome : https://support.google.com/chrome/answer/114836?hl=it&ref_topic=3421433

Safari (MAC): http://help.apple.com/safari/mac/8.0/#/ibrw1069 (navigazione privata) ;
http://help.apple.com/safari/mac/8.0/#/sfri40732 (do not track)

Ma non sono del tutto efficaci o "automatiche" (mi riferisco a come potrebbe interpretarle l'utente medio).

Infine trovo utile citare anche i circuiti tipo 
youronlinechoices.com

**Comment by iusondemand** [comment]
si', citare youronlinechoices senza dubbio.
C'e' anche: impostazioni, privacy, pubblicita', id pubblicitario e limita raccolta dati pubblicitari
disattivato appena scoperto per caso mesi fa :)

**Comment by Gix075** [comment]
Chiudo per vecchiaia della issue, se serve riapriamo.
