### ISSUE TITLE
Chi siamo nel gruppo

### ISSUE THREAD

**Issue by hmtechnology** [FattiDiCookies/italianPrivacyPolicy#44]
Ragazzi ogni tanto mi piacerebbe scambiare instant messages con voi, a seconda delle necessità. Ci localizziamo? Profilo FB?Skype? Cosa preferite?

**Comment by Gix075** [comment]
Gildo Giuliani su FB

**Comment by 2autunni** [comment]
https://about.me/mcerruti (non molto aggiornata)
https://www.facebook.com/marcellocerruti

**Comment by Gix075** [comment]
Chiudo per vecchiaia della issue, se serve riapriamo.
