### ISSUE TITLE
ShinyStat - Servizio (di terze parti) con cookie tecnici

### ISSUE THREAD

**Issue by hmtechnology** [FattiDiCookies/italianPrivacyPolicy#46]
### ShinyStat

**[descrizione]** _ShinyStat_ è un sistema di rilevazione e statistiche rilasciato da [http://www.shinystat.com](http://www.shinystat.com/) che permette di monitorare gli accessi ai siti web.
**[dati di utilizzo]** Il servizio _ShinyStat_ acquisisce alcuni dati degli utenti (dati di navigazione) che non sono raccolte per essere associate a interessati identificati ma al solo fine di ricavare informazioni statistiche anonime sull'uso del sito e per controllarne il corretto funzionamento. 
**[cookie utilizzati]** Il servizio _ShinyStat_ utilizza cookie di tipo analytics assimilati ai cookie tecnici in quanto vengono utilizzati in forma anonima e aggregata e non collezionano alcun dato personale in grado di identificare personalmente gli utenti.
**[disclaimer]** [[NOME SITO]] non utilizza il servizio _ShinyStat_ per la profilazione dell'utente in prima parte e non ha accordi con _ShinyStat_ per profilare in prima parte.
##### Link di riferimento
- [Privacy Policy](http://www.shinystat.com/it/informativa_privacy_generale.html)
- [Cookie Policy](http://www.shinystat.com/it/informativa_cookie_sito.html)
- [Opt-Out](http://www.addthis.com/privacy/opt-out)
- [Anonimizzazione IP ShinyStat](http://www.shinystat.com/it/anonimizzazione.html)

**Comment by Gix075** [comment]
Testo Inserito
Chiudo per vecchiaia della issue, se serve riapriamo.
