### ISSUE TITLE
Categorie dei Servizi

### ISSUE THREAD

**Issue by hmtechnology** [FattiDiCookies/italianPrivacyPolicy#47]
"Contenuti embed da terze parti" (Twitter, Vine, Pinterest, Instagram)
"Strumenti di condivisione sociale" (AddThis, ShareThis)
"Sistema di Commenti" (Disqus)
"Sistema di Statistica" (Google Analytics, ShinyStat)
"Strumenti Pubblicitari" (Google AdSense)

**Comment by 2autunni** [comment]
Mi va bene però due domande:

Facebook, è trasversale (commenti, contenuti che vegono embeddati, la page plugin per mostrare i mi piace alla pagina ): facciamo una categoria a se stante?

Nei "Contenuti embed da terze parti" ci sarebbero anche vimeo e youtebe: che facciamo li mettiamo lì o facciamo una categoria video?

Vorrei poi nella sezione "Sistema di Statistica"  aggiungere anche piwik che uno si può installare e utilizzare al posto di Google Analytics.

**Comment by hmtechnology** [comment]
Aggiorno l'elenco
1. "Contenuti embed da terze parti" (Twitter, Vine, Pinterest, Instagram)
2. "Strumenti di condivisione sociale" (AddThis, ShareThis)
3. "Sistema di Commenti" (Disqus, Facebook Comments)
4. "Sistema di Statistica" (Google Analytics, ShinyStat)
5. "Strumenti Pubblicitari" (Google AdSense)

@2autunni Sì Facebook è trasversale, infatti come noti l'ho spezzato in FB comments tra i sistemi di statistica (punto 4) e inserirei i contenuti embeddati, le page box, like box etc tra i contenuti embed di terze parti (punto 1)

Yes nel punto 1 ci stà anche vimeo e youtube (non li ho inseriti perchè ho inserito solo i servizi che abbiamo recensito) e non solo. Io li metterei tutti insieme per ora, poi alla fine vediamo se ulteriormente ramificare con ad esempio "contenuti video embed", 

Sì, aggiungiamo anche Piwik ovviamente, apro la milestone;)

**Comment by iusondemand** [comment]
piwik e slimstat; google maps; poi c'e' il mondo delle api, ma non credo serva per i cookies anche se serve per la privacy

**Comment by hmtechnology** [comment]
piwik e slimstat li mettiamo tra i sistemi di statistica, google map nei contenuti embed di terze parti; per le api dammi dettagli in più:)

**Comment by Gix075** [comment]
Ci sarebbero anche alcuni CDN.

**Comment by Gix075** [comment]
Comunque se vi interessa vedere il tool in azione l'ho implementato qui:
http://museumperugia.com/

**Comment by Gix075** [comment]
Chiudo per vecchiaia della issue, se serve riapriamo.
