### ISSUE TITLE
Facebook Comments - Servizi (di terze parti) con cookie di profilazione?

### ISSUE THREAD

**Issue by hmtechnology** [FattiDiCookies/italianPrivacyPolicy#48]
### Facebook Comments

**[descrizione]** _Facebook Comments_ è un sistema di commenti rilasciato da [http://www.facebook.com](http://www.facebook.com/) che permette agli utenti di scrivere contenuti sui siti web attraverso il proprio account Facebook e di condividerli sulla stessa piattaforma.
**[dati di utilizzo]** Il servizio _Facebook Comments_ acquisisce alcuni dati degli utenti (dati di navigazione e dati forniti volontariamente dall'utente) riconducibili al profilo pubblico, all'ID utente, la fascia d'età e altre informazioni condivise dall'utente.
**[cookie utilizzati]** Il servizio _Facebook Comments_ utilizza cookie di profilazione (Facebook Social Plugins, Facebook Connect) che permettono funzionalità di tipo social basate sulle attività dell'utente sui siti web.
**[disclaimer]** [[NOME SITO]] non utilizza il servizio _Facebook Comments_ per la profilazione dell'utente in prima parte e non ha accordi con _Facebook Comments_ per profilare in prima parte.
##### Link di riferimento
- [Privacy Policy](https://www.facebook.com/about/privacy/)
- [Cookie Policy](https://www.facebook.com/help/cookies/?ref=sitefooter)

**Comment by Gix075** [comment]
@hmtechnology chiudo questa issue perché credo che questo testo sia stato ritirato. In caso contrario riapri la issue, altrimenti se vuoi cancellala proprio.
