### ISSUE TITLE
piwik

### ISSUE THREAD

**Issue by 2autunni** [FattiDiCookies/italianPrivacyPolicy#49]
Ci serve inserire nella privacy policy e nela cookie policy anche piwik che è usato a volte al posto di analytics.
La situazione è però un po' complicata percheé è un prodotto opensource e pertanto:
- può essere installato da chi crea il sito sullo stesso server o su uno diverso
- può essere utilizzato cloud (piwik pro) ospitato sui server della ditta che lo sciluppa (ma controllato sempre dal gestore del sito per cui effettua le statistiche)
- potrebbe essere installato dall'hosting e offerto come servizio ai clienti (mai visto, ma nulla mi vieta di immaginarlo)
  Inoltre piwik può essere fatto funzionare con cookie (che sono di primo parte) o senza inserendo o meno una riga nel codice js che si usa per fargli contare le pagine
  Piwik come impostazione di base anonimizza gli ip, ma questa opzione può essere disabilitata.
  Permette inoltre di embeddare sul sito per cui sta tenendo le statistiche un iframe con un "comando" per l'opt-out. Se un utente decide per l'opt-out setta un cookie (che può essere di terza parte)

Prendo spunto da qunato emerso qui #45 e qui  #13

**Comment by hmtechnology** [comment]
Il bello che proprio piwik è chiaramente indicato da fonti vicine al Garante come cookie di terze parti che fa statistica aggregata e quindi rientra tra i cookie tecnici.

**Comment by hmtechnology** [comment]
Lo stesso problema si può avere con Disqus o altri servizi di cui nn siamo sicuri al 100% se facciano profilazione o meno

**Comment by 2autunni** [comment]
http://piwik.org/faq/general/#faq_146 qui è spiegato bene,
I cookie sono di prima parte, nel senso che se il js è installato su pippo.com i cookie sono di pippo.com, anche se piwik risiede su paperino.org, però se fai opt-out il cookie è di paperino.org e ti rende invisibile a tutti i siti tracciati da paperino.org

**Comment by hmtechnology** [comment]
Grazie..Roba da impazzire cmq...no??

**Comment by hmtechnology** [comment]
ahhh, pero stiam parlando di cookie tecnici di prima parte o terza parte. Quindi non cambia molto.

Profilanti solo se togli l'anonimizzazione, esatto?

**Comment by 2autunni** [comment]
non so, io lo uso, cercando di renderne il comportamento uguale a quello di google analytics, ma a mali estremi posso passare alla versione no cookies.
forse @iusondemand può chiarirci meglio le idee, mi sembrava più ferrato sui cavilli della normativa

**Comment by iusondemand** [comment]
Piwik installato o in cloud e ' di prima parte. Se non profila e' tecnico.

Non ricordo se c'e' una versione free gestita dall'"autore".

Ricordo che prevede impostazione per non essere tracciati nemmeno aggregati.

Come dice @hmtechnology e' la classica situazione di stat interne, quando non usato diversamente

Slimstat dovrebbe essere nella stessa situazione

**Comment by 2autunni** [comment]
> Non ricordo se c'e' una versione free gestita dall'"autore".

non capisco:  cosa intendi?  piwik è GPL, poi c'è la versione cloud http://piwik.pro che è a pagamento e non è altro che un hosting dedicato, ma il funzionamento rimane lo stesso: chi amministra piwik decide il livello di "privacy" lasciato agli utenti (livello di anonimizzazione ip,cookie oppure no, ecc ecc,)

> Ricordo che prevede impostazione per non essere tracciati nemmeno aggregati.

Sì è l'opt-out di cui parlavo prima, ma non avevo messo il link alle faq http://piwik.org/faq/general/faq_20000/

Slimstat non lo conosco, grazie per averlo segnalato

**Comment by Gix075** [comment]
Personalmente direi che prima di tutto dobbiamo occuparci della situazione più semplice, ovvero chi usa piwik per ottenere statistiche senza profilazione. Il cookie di questo servizio è assimilabile ai tecnici e lo usa anche il Garante che fa solo informativa estesa senza banner. Quindi magari possiamo implementare nel repository un disclaimer dove spieghiamo anche queste cose o in futuro ampliarlo anche a diversi scenari. Ho inserito un testo nella issue #67

**Comment by Gix075** [comment]
Chiudo anche qui per smaltire issue, ce ne sono troppe aperte. Ho inserito un testo per piwik nel repository, magari dategli un'occhiata e ripartiamo da lì altrimenti non finiamo mai.
