### ISSUE TITLE
privacy policy g.a. non anonimizzato

### ISSUE THREAD

**Issue by ghost** [FattiDiCookies/italianPrivacyPolicy#5]
http://www.google.com/intl/it_ALL/analytics/learn/privacy.html

**Comment by Gix075** [comment]
Per quanto riguarda il testo da inserire nella policy per il servizio Analytics, anche a fronte delle lamentele di iubenda, secondo voi così può andare?

**Google Analytics (testo generico)**
Il servizio di statistiche Google Analytics utilizzato da NOME SITO è un sistema in grado di tracciare il comportamento degli utenti durante la navigazione. 
I cookie rilasciati da questo servizio vengono utilizzati per collezionare informazioni sull’uso del sito nonché generare statistiche dettagliate fruibili dagli amministratori del sito NOME SITO  in forma completamente anonima.
Goolge, proprietaria del servizio, utilizzerà tali dati al fine di condividerli con altri servizi da essa forniti e per generare annunci pubblicitari (proposti attraverso i canali AdSense), che siano di gradimento all’utente.

**Google Analytics Anonimo**
Questo sito utilizza il sistema Google Analytics in modalità anonima.
Attraverso questa modalità di utilizzo Google registrerà l’indirizzo IP dell’utente in forma non estesa, garantendo quindi l’anonimato dell’utente. Questa modalità è attiva solo all’interno dei paesi facenti parte della Comunità Europea.

**Comment by seosmart** [comment]
Secondo me si, l'unica cosa che vorrei capire è se si possono (o si devono) inserire entrambe nella informativa estesa.

**Comment by Gix075** [comment]
Io da quello che ho capito è necessario riportare una descrizione dei servizi di terzi che istallano cookies durante la navigazione nel sito e ovviamente i link alle pagine di privacy, accettazione e/o cancellazione dei cookie rilasciati e termini e condizioni del servizio in questione.

**Comment by Gix075** [comment]
Chiudo il ticket perché ho spostato le due discussioni Analytics in un'altra nuova per l'approvazione del testo
