### ISSUE TITLE
Facebook Social Plugins 

### ISSUE THREAD

**Issue by hmtechnology** [FattiDiCookies/italianPrivacyPolicy#50]
#### Facebook Social Plugins

_Facebook Social Plugin_ comprende elementi web rilasciati da [http://www.facebook.com](http://www.facebook.com) quali il pulsante Mi piace, il pulsante Condividi, i commenti e altri strumenti di integrazione sociale. _Facebook Social Plugin_ utilizza i contenuti e le informazioni che fornite dall'utente quando utilizza i Servizi. _Facebook Social Plugin_ utilizza cookie per poter mostrare contenuti e inserzioni più pertinenti, per migliorare i prodotti e servizi e per garantire la sicurezza nei Servizi. 
[[NOME SITO]] non utilizza il servizio _Facebook Social Plugin_ per la profilazione dell'utente in prima parte e non ha accordi con _Facebook Social Plugin_ per profilare in prima parte.
#### Link di riferimento
- [Normativa sui Dati](https://www.facebook.com/full_data_use_policy)
- [Cookie](https://www.facebook.com/help/cookies/)

**Comment by 2autunni** [comment]
era a volte plugins  a volte plugin, metto dovunque plugins 

#### Facebook Social Plugins

_Facebook Social Plugins_ comprende elementi web rilasciati da [http://www.facebook.com](http://www.facebook.com) quali il pulsante Mi piace, il pulsante Condividi, i commenti e altri strumenti di integrazione sociale. _Facebook Social Plugins_ utilizza i contenuti e le informazioni che fornite dall'utente quando utilizza i Servizi. _Facebook Social Plugins_ utilizza cookie per poter mostrare contenuti e inserzioni più pertinenti, per migliorare i prodotti e servizi e per garantire la sicurezza nei Servizi. 
[[NOME SITO]] non utilizza il servizio _Facebook Social Plugins_ per la profilazione dell'utente in prima parte e non ha accordi con _Facebook Social Plugins_ per profilare in prima parte.

#### Link di riferimento
- [Normativa sui Dati](https://www.facebook.com/full_data_use_policy)
- [Cookie](https://www.facebook.com/help/cookies/)

**Comment by Gix075** [comment]
@hmtechnology chiudo questa issue perché credo che questo testo sia stato ritirato. In caso contrario riapri la issue, altrimenti se vuoi cancellala proprio.
