### ISSUE TITLE
Facebook Connect

### ISSUE THREAD

**Issue by hmtechnology** [FattiDiCookies/italianPrivacyPolicy#51]
### Facebook Connect

_Facebook Connect_ è il sistema rilasciato da [http://www.facebook.com](http://www.facebook.com) che consente agli utenti di effettuare il login ai siti usando le proprie credenziali Facebook. _Facebook Connect_ può accedere ai dati personali forniti dall'utente su Facebook. Tali dati potrebbero essere trattati da Facebook, in alcuni casi e con il suo consenso, per finalità di marketing e/o analitiche, e non solo per fornire il servizio. _Facebook Connect_ utilizza cookie per mostrare contenuti e inserzioni più pertinenti e "social" quando visiti altri siti Web che utilizza i plug-in social di Facebook.
[[NOME SITO]] non utilizza il servizio _Facebook Social Plugin_ per la profilazione dell'utente in prima parte e non ha accordi con _Facebook Social Plugin_ per profilare in prima parte.
#### Link di riferimento
- [Normativa sui Dati](https://www.facebook.com/full_data_use_policy)
- [Cookie](https://www.facebook.com/help/cookies/)

**Comment by Gix075** [comment]
Per me è ok. Visto che questo servizio è stato inserito nel repo e non mi sembra che ci siano obiezioni, direi di chiudere issue e milestone, giusto per fare un po' di ordine. Riaprire issue in caso di bisogno.

**Comment by iusondemand** [comment]
Scusate se riapro, ma questo e' uno dei punti che piu' si collega ad una eventuale privacy policy.
Sotto il profilo dei cookie mi limiterei a chiedermi se il solo connect profila o meno. Credo di no, perche' i primi scambi di dati sono tra sito e facebook per un id sessione temporaneo, l'utente non e' coinvolto, a meno che non si agisca espressamente per il riconoscimento di solito su un bottone.

Poi invece i dati che il sito puo' andare a leggere da facebook sono l'infinita' che sappiamo, oltre a quelli che sono oltre l'autorizzazione base e che vanno autorizzati singolarmente. Questi dati sarebbero in privacy policy.

(Argh... come diavolo si riapre ... ?)

**Comment by iusondemand** [comment]
Sono poi considerazioni che potrebbero valere per ogni "connect" (linkedin, twitter, etc etc)

**Comment by Gix075** [comment]
@hmtechnology chiudo questa issue perché credo che questo testo sia stato ritirato. In caso contrario riapri la issue, altrimenti se vuoi cancellala proprio.
