### ISSUE TITLE
Twitter Button

### ISSUE THREAD

**Issue by hmtechnology** [FattiDiCookies/italianPrivacyPolicy#52]
### Twitter Button

_Twitter Button_ è una suite di widget rilasciata da [http://www.twitter.com](http://www.twitter.com) che integra contenuti e pulsanti da Twitter sul sito per incoraggiare la condivisione tra gli utenti. _Twitter Button_ utilizza alcune informazioni relative al browser che permette ai i pulsanti e ai widget di funzionare correttamente. _Twitter Button_ utilizza cookie per finalità di misurazione e di personalizzazione del contenuto. Ad esempio, il cookie "metrics_token" aiuta a contare il numero di utenti che hanno visto un particolare Tweet.
[[NOME SITO]] non utilizza il servizio _Twitter Button_ per la profilazione dell'utente in prima parte e non ha accordi con _Twitter Button_ per profilare in prima parte.
##### Link di riferimento
- [Privacy Policy](https://twitter.com/privacy?lang=it)
- [Cookie](https://support.twitter.com/articles/20170514-twitters-use-of-cookies-and-similar-technologies)

**Comment by Gix075** [comment]
Anche questo per me è ok!

**Comment by iusondemand** [comment]
Bellissima la "chiosa" finale che avevo proposto ma che hai realizzato in modo eccellente. Grande, alla via cosi' !

**Comment by Gix075** [comment]
Per me è ok. Visto che questo servizio è stato inserito nel repo e non mi sembra che ci siano obiezioni, direi di chiudere issue e milestone, giusto per fare un po' di ordine. Riaprire issue in caso di bisogno.
