### ISSUE TITLE
Google+ Platform

### ISSUE THREAD

**Issue by hmtechnology** [FattiDiCookies/italianPrivacyPolicy#53]
### Google+ Platform

_Google+ Platform_ è una suite di widget rilasciata da [http://www.google.com](http://www.google.com) che integrano contenuti e pulsanti da Google sul sito per incoraggiare la condivisione tra gli utenti. _Google+ Platform_ utilizza alcune informazioni relative al browser che permette ai i pulsanti e ai widget di funzionare correttamente. _Google+ Platform_ utilizza cookie per finalità di misurazione e di personalizzazione del contenuto. 
[[NOME SITO]] non utilizza il servizio _Google+ Platform_ per la profilazione dell'utente in prima parte e non ha accordi con _Google+ Platform_ per profilare in prima parte.
##### Link di riferimento
- [Privacy Policy](http://www.google.com/intl/en/policies/privacy/)
- [Cookie](https://support.twitter.com/articles/20170514-twitters-use-of-cookies-and-similar-technologies)

**Comment by Gix075** [comment]
Per me è ok!

**Comment by Gix075** [comment]
@hmtechnology dovrò rinominare il file per via del tool.

**Comment by iusondemand** [comment]
piu' che perfetto, mitico il testo e mitico tu, sembra che tu abbia messo velocita' curvatura :) grande !

**Comment by Gix075** [comment]
@hmtechnology ho rinominato questo file in google+.md

**Comment by Gix075** [comment]
Per me è ok. Visto che questo servizio è stato inserito nel repo e non mi sembra che siano obiezioni, direi di chiudere issue e milestone, giusto per fare un po' di ordine. Riaprire issue in caso di bisogno.
