### ISSUE TITLE
Tradedoubler

### ISSUE THREAD

**Issue by hmtechnology** [FattiDiCookies/italianPrivacyPolicy#54]
### Tradedoubler

_Tradedoubler_ è un sistema di advertising online online rilasciato da  [http://www.tradedoubler.com/](http://www.tradedoubler.com/) che consente agli editori affiliati di pubblicare annunci sul proprio sito web. _Tradedoubler_ utilizza alcuni dati anonimi dell'utente, al fine di mostrare una pubblicità più attinente e per fornire report aggregati non personali per conto dei suoi clienti. Il sistema di _Tradedoubler_ di advertising e di retargeting è basato sull'utilizzo di cookie; sulla base delle informazioni anonime memorizzate nel cookie dell'Utente, _Tradedoubler_ è in grado di fornire pubblicità più rilevanti per l'utente per conto dei suoi clienti.
[[NOME SITO]] non utilizza il servizio _Tradedoubler_ per la profilazione dell'utente in prima parte e non ha accordi con _Tradedoubler_ per profilare in prima parte.
##### Link di riferimento
- [Privacy Policy](http://www.tradedoubler.com/uk-en/privacy-policy/)

**Comment by Gix075** [comment]
Per me è ok. Visto che questo servizio è stato inserito nel repo e non mi sembra che siano obiezioni, direi di chiudere issue e milestone, giusto per fare un po' di ordine. Riaprire issue in caso di bisogno.
