### ISSUE TITLE
Adform

### ISSUE THREAD

**Issue by hmtechnology** [FattiDiCookies/italianPrivacyPolicy#55]
### Adform

_Adform_ è una società specializzata in display advertising [http://site.adform.com/](http://site.adform.com/) che permette una personalizzazione delle offerte in tempo reale attraverso l’integrazione delle stesse nei siti degli editori affiliati. 
_Adform_ utilizza alcuni dati anonimi dell'utente, al fine di mostrare una pubblicità più attinente. _Adform_, attraverso cookie con numeri di identificazioni casuali, raccoglie e memorizza informazioni anonime, quali: sistema operativo, la versione del browser, collocazione geografica, gli URL in cui Adform visualizza annunci pubblicitari, o fatti su interazioni con annunci pubblicitari (come il numero di clic o visualizzazioni).
[[NOME SITO]] non utilizza il servizio _Adform_ per la profilazione dell'utente in prima parte e non ha accordi con _Adform_ per profilare in prima parte.
##### Link di riferimento
- [Privacy Policy](http://site.adform.com/privacy-policy/en/)

**Comment by Gix075** [comment]
@hmtechnology  Ho rinominato questo file in adform.md

**Comment by Gix075** [comment]
Per me è ok. Visto che questo servizio è stato inserito nel repo e non mi sembra che ci siano obiezioni, direi di chiudere issue e milestone, giusto per fare un po' di ordine. Riaprire issue in caso di bisogno.
