### ISSUE TITLE
Zanox

### ISSUE THREAD

**Issue by hmtechnology** [FattiDiCookies/italianPrivacyPolicy#56]
##### Zanox

_Zanox_ è un sistema di advertising online rilasciato da [http://www.zanox.com/](http://www.zanox.com/) che consente, tramite un programma di affiliazione, di pubblicare offerte e prodotti all'interno del sito degi editoriali affiliati. _Zanox_ utilizza alcuni dati anonimi dell'utente, al fine di mostrare una pubblicità più attinente. _Zanox_ utilizza cookie al fine di registrare le transazioni commerciali (lead e vendite); i cookie contengono solo una sequenza individuale di cifre che non possono essere assegnati a un particolare utente.
[[NOME SITO]] non utilizza il servizio _Zanox_ per la profilazione dell'utente in prima parte e non ha accordi con _Zanox_ per profilare in prima parte.
##### Link di riferimento
- [Privacy Policy](http://www.zanox.com/it/riguardo-a-zanox/privacy_policy/)

**Comment by Gix075** [comment]
Per me è ok. Visto che questo servizio è stato inserito nel repo e non mi sembra che siano obiezioni, direi di chiudere issue e milestone, giusto per fare un po' di ordine. Riaprire issue in caso di bisogno.
