### ISSUE TITLE
Cosa e' azione ?

### ISSUE THREAD

**Issue by iusondemand** [FattiDiCookies/italianPrivacyPolicy#57]
Un tema del quale non si parla piu' e': cosa e' azione. Uno scroll ? Un click ovunque o su un link o su un form ?

In realta' la nuova pagina del garante sotto linkata, con l'enfasi di un corsivo, sottolinea che e' un click su link o immagine:

"4) l'indicazione che proseguendo nella navigazione (ad es., accedendo ad un'altra area del sito o selezionando un'immagine o un link)  si presta il consenso all'uso dei cookie."

Nel javascript che ho inviato come ramo (spero di averla azzeccata) ho previsto sia lo scroll che il click sulla pagina, in un punto qualsiasi, ma li ho commentati per lasciarli a chi li voglia usare.

In realta' la soluzione piu' aderente sembra essere quella di controllare se il link sia stato fatto su un qualsiasi link o (come dicono in europa) su un form. Non ho previsto il click su una immagine per pigrizia.

Funziona. Non sembra nemmeno rallentare. Poiche' imposta un cookie non c'e' nemmeno interferenza con il normale click sul link, credo almeno.

Ecco il codice: https://github.com/FattiDiCookies/italianPrivacyPolicy/tree/iusondemand-what-is-action

v.

**Comment by 2autunni** [comment]
Domanda se clicco sulla pagina e non su un link come si usa di solito per far sparire i div modali che si aprono sui siti per invitarti a dare il mi piace su fb, oppure contengo pubblicità non si sblocca, vero?
Immagino sia voluto?

p.s. quello che hai fatto è una pratica comune lavorando con git, vuoi introdurre una features e fai un ramo, quando la features viene accettata uniamo il ramo al master. ricordati solo di aggiornare i file che non tocchi dal master ogni tanto per non rimanere troppo indietro.  Scusa se sono pedante con queste spiegazioni non richieste ;-)

**Comment by iusondemand** [comment]
@2autunni ho bisogno come il pane di queste spiegazioni, fai conto che siano sempre richieste :) grazie mille, ho tanto da imparare.

Quanto allo script, la prima versione ascoltava l'evento click su body. La seconda versione anche lo scroll. La terza versione cerca un click su ogni link e su ogni input (potrei aggiungere anche checkbox, select e textarea e radio).

Dopo aver perso tanto tempo sul blocco preventivo di terze parti, che alcuni ancora vogliono spaventare dicendo sia obbligatorio, stavo riflettendo sull'evento da associare all'impostazione del cookie.

In realta' non sono convito che il click sul body sia sbagliato. Customizzando la classe che viene dinamicamente associata a body si potrebbe mettere una trasparenza e renderlo piu' evidente. Lascio aperte le diverse soluzioni. Puoi riattivare la preferita come vuoi, oppure supportando meglio i flag impostati all'inizio nelle variabili globali.

**Comment by iusondemand** [comment]
scoll ufficialmente accettato dal Garante. Il resto (mio) e' fuffa :-( 
quindi scroll, ok, click ok, l'importante e' scriverlo nell'informativa breve.
