### ISSUE TITLE
Esportazione JSON

### ISSUE THREAD

**Issue by Gix075** [FattiDiCookies/italianPrivacyPolicy#59]
Ho committato l'esportazione JSON dei documenti in quanto sto pensando ad alcune modifiche (per questioni di performance) al tool.
Al momento Grunt crea un file json unico con tutti i testi dentro.

**Comment by 2autunni** [comment]
qui fb52e37?  pensi di creare un json per frammento?  è possibile aver esalvato da qualche parte in un json l'elenco di tutti i frammenti disponibili

**Comment by iusondemand** [comment]
Seguo

**Comment by Gix075** [comment]
SI quello è il task di grunt, ovviamente mi sono dimenticato di dire che ho aggiunto una dipendenza, sorry, quindi dovete sincronizzare il vostro repository locale e fare di nuovo **npm install**.

Il plugin grunt che ho usato per questo non permette file diversi, prende una cartella sorgente e fonde tutto in un unico json, però credo di averne scovato un'altro, lo devo testare, che può essere usato per fare anche file singoli, solo che la cosa noiosa è che sembra che bisogni aggiungere una riga al file grunt per ogni file che si vuole generare.

@2autunni  Per quello di cui si diceva ieri via fb sull'uso del cdn ho provato questo servizio https://rawgit.com/ che sembra poter fare al caso nostro. Ad un primo test sembra funzionare anche per chiamate ajax cross-domain. Quindi la tua idea di connettere il tool al file online in modo che l'utente l'abbia sempre aggiornato è fattibile. Può essere poi un buon servizio per chi necessita solo dei testi.

**Comment by 2autunni** [comment]
rawgit l'ho visto dopo che abbiao parlato su fb, sembra usabile, solo che dicendo lui stesso di non garantire uptime lascerei come opzionale il caricamento al volo da rawgit

**Comment by Gix075** [comment]
Al momento sto riscrivendo tutto il tool basandomi sulla versione json dei documenti. Sto cercando di limitare le chiamate ajax a due soltanto (nella versione attuale potrebbero essere potenzialmente infinite per via dei servizi). 
Più precisamente, una viene eseguita sempre (file di config), la seconda (i documenti) solo se necessario. Spero di farcela e di finire in poco tempo. 

Detto questo noi potremmo distribuire comunque nel tool il file json, però permettere da configurazione la scelta del cdn.

**Comment by 2autunni** [comment]
se usare cdn o file locali può essere una scelta dell'utente nel config json

**Comment by Gix075** [comment]
Sì, l'unica cosa è che però si tratterà sempre del json unico con tutti i documenti dentro.

**Comment by Gix075** [comment]
@2autunni @iusondemand @hmtechnology 
Credo che dovrò rinominare quasi tutti i file md dei documenti. Questo perché nelle esportazioni in json si creano problemi con le chiavi degli oggetti per via dei trattini. Quindi dovrò sostituire i trattini con un underscore. 

Magari poi apro una issue per segnalarlo.

**Comment by iusondemand** [comment]
Per me ok tutto.

**Comment by Gix075** [comment]
Allarme rientrato! Almeno per il momento.

**Comment by iusondemand** [comment]
Hai lavorato anche tu stanotte :-)

**Comment by Gix075** [comment]
Si, per me è sempre il momento migliore ;-)
