### ISSUE TITLE
Proprietà intellettuale di iubenda

### ISSUE THREAD

**Issue by Facens** [FattiDiCookies/italianPrivacyPolicy#6]
I documenti legali di iubenda fanno parte della proprietà intellettuale dell'azienda. Le clausole che vedo sono state palesemente riprese dal nostro servizio. Siete pregati di rimuovere le parti riprese per intero o palesemente ispirate al nostro servizio, così come di adottare un metodo di lavoro diverso nel futuro. In alternativa, ci vedremo costretti ad agire a nostra tutela.

**Comment by ghost** [comment]
Non era intenzione "copiare"

Verranno rimosse, tuttavia richiamare le privacy policy dei vari servizi
non è reato. Potremmo sapere quali sono le parti interessate da modificare?
Il 25/mag/2015 00:06, "Andrea Giannangelo" notifications@github.com ha
scritto:

**Comment by Facens** [comment]
Le privacy policy sono protette dalle leggi sulla proprietà intellettuale così come ogni documento legale e come qualunque altra opera dell'ingegno. Violare queste tutele è reato, eccome, e ti assicuro che se non rimuovete quanto avete ripreso, iubenda non starà qui a guardare.
Questo commit, in particolare, è palesemente copiato dal nostro servizio: https://github.com/FattiDiCookies/italianPrivacyPolicy/commit/f4242a94830193add2df9b5beeafe524c6c27946
Siete invitati a rimuovere immediatamente.

**Comment by 2autunni** [comment]
Gentile @Facens, 
subito dopo la segnalazione abbiamo rimosso dal repository il materiale oggetto delle contestazione. 
Restano, ovviamente, tracce del commit nella history, ma non ci è possibile emendarla, spero che questo non sia un problema. 
Ci dispiace per l'incidente e restiamo a diposizione per qualunque chiarimento.
