### ISSUE TITLE
Ultimi aggiornamenti 

### ISSUE THREAD

**Issue by iusondemand** [FattiDiCookies/italianPrivacyPolicy#60]
Dal garante http://garanteprivacy.it/web/guest/home/docweb/-/docweb-display/docweb/4006878

. Scroll valido
. Embed di terze parti sono tecnici  se terze parti dichiarano che non profilano
. No a elenco dettagliato cookie ma basta per categorie (di interessi ?)
. Profilare anche con una sola domabds per piu' siti
. Analitiche se non profilanti (dicono shinystat o google noip)

Altro ?

**Comment by Gix075** [comment]
C'è questa frase 
_la terza parte si impegna a non incrociare  le informazioni contenute nei cookies con altre di cui già dispone_ 
se applicata a **google analytics** significa doverlo togliere.

**Comment by Gix075** [comment]
Io non riesco proprio a capire! Questo legalese da interpretazione libera è a me veramente ostile e oscuro. Mi sembra di capire che il consenso bisogna ottenerlo noi gestori e preventivamente all'istallazione, con blocco preventivo per quasi ogni servizio, a meno che questi dichiari di non profilare. @iusondemand aiutami a capire!

**Comment by 2autunni** [comment]
non sembra così male:

-cookies tecnici nessun banner
-analitici di prima parte assimilati a tecnici
-analitici di terza parte come tecnici se anonimizzi ip **o** terza parte  fa giurin giurella di non profilare 

il dubbio è se invece non sia 
analitici di terza parte come tecnici se anonimizzi ip **e** terza parte  fa giurin giurella di non profilare 

La parte fondamentale mi sembra questa:

> Preme sottolineare che l'obbligo di rendere l'informativa e acquisire il consenso nasce dalla scelta del sito di ospitare pubblicità mirata basata sulla profilazione degli utenti tramite i cookie, in luogo di quella generalista offerta indistintamente a tutti.

Quindi vogliono colpire i siti che utilizzano pubblicità basata sulla profilazione e chi la fornisce. ovviamente tutto imho.

**Comment by 2autunni** [comment]
Da questo chiarimento, emerge ad esempio che un servizio che non viene colpito sono gli embed da vimeo, perché vimeo dice esplicitamente che non profila

**Comment by Gix075** [comment]
Secondo voi però youtube come sarà considerato? Cosa bisognerà fare?

**Comment by iusondemand** [comment]
Ciao a tutti. Alla luce dei nuovi chiarimenti ho preso contatto con un altro vero esperto di queste cose, e abbiamo fatto una bella telefonata di 15 minuti organizzandoci il lavoro.
Gli ho subito parlato di noi e lo cosa lo interessa. 

A proposito dei chiarimenti, dovremmo iniziare a censire se vi sono dichiarazioni documentali o meno, per quanto sia un qualcosa ancora da valutare, e il lavoro che state facendo e' eccezionale.

Insomma: giunge il momento di scambiarci nomi, cognomi e recapiti anche telefonici.
Io vi cerco online, ma se mi aiutaste non sarebbe male, poi ci facciamo un hangout o simili.
Potete scrivermi a valentinospataro@gmail.com o www.iusondemand.com/mail

**Comment by iusondemand** [comment]
Sono un po' a disagio a dare una risposta, e ancora di piu' a leggere interpretazioni dste come ovvie su fb e riviste , ma senza spiegazioni.

L'unica certezza e' sullo scroll, tutto italiano, che secondo me non può  valere in ambito europeo.

A tutti quelli che parlano di blocco preventivo generalizzato sulle terze parti chiederei di leggere i testi del 2014. Il blocco e' uscito solo ora. La faq 14 e' chiara. Il resto e' diverso.

**Comment by iusondemand** [comment]
Ho appena letto un pist corretto in tutto, ma discutibile sul blocco preventivo di terze parti. E infatti nei commenti se ne discute. http://www.ilsoftware.it/articoli.asp?tag=Cookie-law-analisi-dei-chiarimenti-del-Garante_12328

**Comment by 2autunni** [comment]
Scusa se rispondo solo ora, non ho capito questo.

> A proposito dei chiarimenti, dovremmo iniziare a censire se vi sono dichiarazioni documentali o meno, per quanto sia un qualcosa ancora da valutare, e il lavoro che state facendo e' eccezionale.

per il resto ti ho amicato su fb

**Comment by iusondemand** [comment]
Si ci vuole una lista di servizi terzi secondo legge. Con @ht...ne ho parlato a voce. Oggi vi senntiamo su fb lavoro permettendo :-(
