### ISSUE TITLE
Guida sui Cookie sempre aggiornata

### ISSUE THREAD

**Issue by duarme** [FattiDiCookies/italianPrivacyPolicy#61]
Uno dei requisiti fondamentali della informativa estesa è informare su cosa siano i cookie, sui rischi a essi connessi e su come gestirli dal proprio browser. A detta di tutti i legali che ho contattato adempiere al meglio a questo requisito può effettivamente mettere al riparo da multe per errori od omissioni minori.

Sembrerebbe di dover praticamente inserire un manuale di tutti i browser in ogni sito...

Tuttavia il Parlamento Europeo, per esempio, nella sua cookie policy linka questo sito: http://aboutcookies.org/

Propongo di creare un contenuto in italiano con lo stesso scopo.
Si potrebbe partire da questa mini guida che ho già scritto e integrarla:
http://nemboweb.com/blog/didattica/cosa-sono-i-cookies-e-come-gestirli-dal-proprio-browser

Questo con l'intento di collaborare tutti per tenerla aggiornata.

Ovviamente il contenuto andrebbe messo in un contenitore neutro, possibilmente un .org o una sezione del sito che realizzeremo per i contenuti di questa repo.

Che ne dite?

**Comment by iusondemand** [comment]
me gusta, io ne ho trovata un'altra in Europa leggerissima. Lasciami il tempo di leggere la tua.

USO IL TUO POST PER PROPORRE DI REALIZZARE L'INDICE CON UNA MAPPA MENTALE (tasto ins per aggiungere una nuova voce): https://www.mindmeister.com/550907632/cookie-law

Ecco i link europei che ho trovato oggi:
- Tutti i temi legali correlati: http://ec.europa.eu/ipg/basics/legal/cookies/index_en.htm
- Per chi cerca mappe, video e altri servizi approvati dall'europa: http://ec.europa.eu/ipg/services/interactive_services/index_en.htm
- i like: http://ec.europa.eu/ipg/services/interactive_services/like_dislike/index_en.htm

**Comment by brunosaetta** [comment]
eccomi, da dove si parte?

**Comment by 2autunni** [comment]
Il progetto (iniziato da @Gix075  che è la persona che ha più chiare le linee di sviluppo ) ha come scopo quello di creare un plugin in js che sia facilmente integrabile in siti web, sia configurabile dall'utente  e implementi: banner, privacy policy e cookies policy.

Ci sono una parte tecnica di programmazione e una parte di scrittura dei vari pezzi della cookies policy (uno per servizio o gruppo di servizi).

I vari pezzi di "legalese" sono stati scritti prima degli ultimi "chiarimenti" del garante, nelle issue trovate le discussioni relative ai vari servizi. @brunosaetta (benvenuto ), come vedrà dalle issue abbiamo alcuni dubbi circa l'implementazione (blocco preventivo, analitycs, cookies di prima e terza parte), forse lei può aiutarci a chiarire 

La guida completa che propone @darmens (benvenuto anche a te ) potrebbe essere ospitata su quello che sarà il sito del progetto: di cui si parlava nella issue #36 
Un "estratto" potrebbe finire nella cookie policy base che fa parte del progetto.

Per voi va bene rilasciare i testi con licenza creative commons come dicevamo qui #35 ?

**Comment by duarme** [comment]
Si, ho scritto in #35 che concordo su MIT+CC.

**Comment by iusondemand** [comment]
Se volete non commerciale ci vuole cc nc

**Comment by Gix075** [comment]
Al momento ho assegnato MIT al software e **CC Attribuzione - Non Commerciale - Non opere derivate** per proteggere il lavoro di chi ha scritto i testi da possibili furti da parte di coloro che intendono rivendere servizi simili. Dico questo perché così mi è stato riferito.

Poi si potrebbe pensare ad un tipo di licenza http://www.creativecommons.it/CCPlus 

Chiudo questa issue. Se ci sono cose da aggiungere riapriamo.
