### ISSUE TITLE
Proposta di merge

### ISSUE THREAD

**Issue by iusondemand** [FattiDiCookies/italianPrivacyPolicy#62]
L'autore di https://github.com/lucatwiv/Free-cookie-law-tools mi propone un merge. Che ne pensat e?

**Comment by Gix075** [comment]
Di preciso l'idea quale sarebbe, te lo ha spiegato?

**Comment by iusondemand** [comment]
Gli ho detto di venire qui era un commento in Fatti di cookies

**Comment by iusondemand** [comment]
Ecco e' issue #63 questo si può  chiudere

**Comment by 2autunni** [comment]
chiudo. 
@iusondemand mi sono permesso di editare il tuo commento in modo che ci sia il link all'altra issue
