### ISSUE TITLE
Link a  Free cookie law tools

### ISSUE THREAD

**Issue by TheBestMovieIsYourImagination** [FattiDiCookies/italianPrivacyPolicy#63]
Per comprendere anche l'aspetto tecnico della faccenda suggerisco di mettere un link nel file Readme.md al mio repository dedicato agli script e ai plugin gratuiti per la legge sui cookie.
 https://github.com/lucatwiv/Free-cookie-law-tools

**Comment by iusondemand** [comment]
Ciao ci parli un po' del tuo repository ?

**Comment by TheBestMovieIsYourImagination** [comment]
Non è soltanto una lista, raccoglie le caratteristiche, i vantaggi e gli svantaggi dei vari tool gratuiti per la cookie law, in modo da rendere più agevole e rapida la scelta da parte degli utenti/coder.

**Comment by Gix075** [comment]
@lucatwiv e dal lato tuo inserirai il nostro progetto nel tuo repository?

**Comment by lucatwiv** [comment]
certo, e eventualmente anche il link a privacy e cookie policy in altre lingue

**Comment by Gix075** [comment]
@lucatwiv dato che nessuno si sbilancia rispondo per ora io dicendo di sì. Se nessuno ha da ridire domani chiudiamo la issue e dal lato mio si può fare. Magari cominciando da appena rilasciamo una beta version del servizio.

**Comment by iusondemand** [comment]
@lucatwiv  e @Gix075  mi scuso anche io per non essermi sbilanciato :-). Ok anche per me.
