### ISSUE TITLE
jquery.fdCookieLaw.js - suggerimenti di implementazione

### ISSUE THREAD

**Issue by raynor85** [FattiDiCookies/italianPrivacyPolicy#65]
Ho un paio di osservazioni e conseguenti suggerimenti riguardo la parte di sviluppo del plugin.
1. Attualmente il plugin si attiva con il debug di default nel costruttore, pertanto l'utente che usufruirebbe del servizio si porterebbe dietro i log nella console. Suggerisco di cambiare il default dell'opzione di debug da true a false.
2. Entrambe le pagine di demo Policy e Cookie vengono generate con il banner attivo, il che significa che in aggiunta alle scritte appare il banner di informativa breve. Suggerisco di togliere il banner da entrambe le pagine aggiungendo banner: 'false' nel costruttore (tali pagine sono esterne al sito e non contengono cookie, ma soprattutto il banner coprirebbe il testo da leggere).
3. Il plugin interrompe la sua esecuzione se non trova una pagina specificata nel config.json (es: facebook-connect: true). Questo comporta un errore e non consente di caricare i successivi blocchi di informativa. Suggerisco di aggiungere un controllo che elimina l'errore.

Fatemi sapere se siete d'accordo su questi punti, che mi metto a lavorarci.

**Comment by Gix075** [comment]
@raynor85 sono d'accordo su tutta la linea,  anche se al momento il debug è attivo di default solo per comodità dato che siamo in versione alpha (l'intenzione era di switchare a false dalla prima stable) quindi al momento questo lo lascerei così. Per il punto due, sì sono d'accordo togliamo il banner dalle pagine. Per quello che riguarda invece l'ultimo punto, l'errore avviene in quanto sono stati tolti dei testi dal repository e il plugin non è stato aggiornato, comunque sì se mettiamo un controllo ed evitiamo l'errore male non fa, anzi. Quindi se vuoi per quanto mi riguarda puoi lavorarci su.

**Comment by Gix075** [comment]
Visto che questi task sono stati processati chiudo la issue. Riaprire se serve.
