### ISSUE TITLE
Sviluppo - Grunt - Suggerimento riguardo l'automazione della compilazione less

### ISSUE THREAD

**Issue by raynor85** [FattiDiCookies/italianPrivacyPolicy#69]
Ho notato che sebbene il progetto contenga dei file in formato less non esiste nessuna task Grunt per la compilazione. Siccome Grunt è perfetto per lo scopo, suggerisco di aggiungere l'implementazione di tale feature aggiungendo un plugin (pensavo grunt-contrib-less)

**Comment by Gix075** [comment]
Sì è colpa mia,  ho un plugin su Brackets che lo fa quindi non installo mai il contrib grunt. Fai pure che vedo che vai forte ;-) ! 
Faccio il merge della pull request.

**Comment by raynor85** [comment]
Le pagine policy e cookie non hanno html, head o body. Immagino che
andrebbero modificate giusto? Ho notato che i caratteri accentati non danno
problemi, tuttavia starei più tranquillo con un charset utf-8 specificato.
Tali pagine dovrebbero essere indipendenti dal cliente al 100%, tranne per
il titolo <title> e la favicon. Possiamo tuttavia pensare di adottare un
titolo e una favicon standard per sollevare il cliente dalla
personalizzazione.
Poi ci sarebbe una considerazione da fare riguardo l'uso dei tab nei css e
nei js. Sarebbe meglio sostituirli con dei doppi spazi (ho fatto del mio
meglio per preservare l'indentatura. Praticamente ogni editor ti consente
di settare il tab per generare altre combinazioni di caratteri. Non voglio
dire che dobbiamo cambiare tutti i tab in spazi, però vorrei sapere che
pensi riguardo la problematica. Sono sicuro che se usi git conosci gli
svantaggi di utilizzare tab invece degli spazi.

Ruben

2015-06-28 18:16 GMT+02:00 Gix075 notifications@github.com:

**Comment by Gix075** [comment]
L'esportazione delle pagine policy e cookie senza head è stata fatta per rendere quelle parti di codice inseribili all'interno di strutture preesistenti, quindi con possibili head già definiti, però nulla ci vieta di crearne una versione stand-alone completa di tutto. Per quello che riguarda i tab o gli spazi per ora non ho mai trovato problemi con i tab e devo essere sincero, questa cosa la ignoro completamente.

**Comment by iusondemand** [comment]
Di solito uso tab, magari tra qualche copia e incolla online ho fatto su casino. 

Proporrei di fare un elenco chiaro di cosa fa chi; di chi coordina i sottoprogetti. Come ci si organizza di solito qui ? 

Io mi candido per i testi legali :)

**Comment by raynor85** [comment]
Il problema dei tab è che ogni editor interpreta il loro spazio in modo
indipendente, quindi quando più persone lavorano sullo stesso file usando i
tab, capitano quelle simpatiche situazioni dove tutte le indentature sono
diverse. Ecco una risorsa che lo conferma:
http://programmers.stackexchange.com/questions/57/tabs-versus-spaces-what-is-the-proper-indentation-character-for-everything-in-e
Una soluzione sarebbe quella di configurare l'editor in modo che quando si
digita tab, vengono aggiunti 2 (o 4) spazi in automatico (così non si perde
il vantaggio di cliccare il tasto una sola volta). Ovviamente se tutti
decidessero di usare gli spazi, bisogna decidere se adottare 2 o 4 spazi, e
siccome ho iniziato a scrivere codice con 2, direi in caso di optare per
questa opzione.

Ruben

2015-06-30 14:50 GMT+02:00 Valentino Spataro notifications@github.com:

**Comment by Gix075** [comment]
@raynor85 non odiarmi so che sono rompiscatole ma ho un problema agli occhi e con due soli spazi (dato che non vedo perfettamente i contorni) non riesco a focalizzare al volo le indentazioni e mi stanco più velocemente. So che sembra folle come cosa ma a me cambia molto usare 4 spazi invece di 2, però ovviamente se per la maggioranza è meglio 2 o ci sono altri problemi a riguardo mi adeguo.

**Comment by raynor85** [comment]
Ok fatto con http://jsbeautifier.org/. A questo punto direi di utilizzare
tabulazioni con 4 spazi.

Ruben

2015-06-30 17:13 GMT+02:00 Gix075 notifications@github.com:
