### ISSUE TITLE
Versione HTML e script JS

### ISSUE THREAD

**Issue by Gix075** [FattiDiCookies/italianPrivacyPolicy#7]
Sto committando una bozza di versione html (directory "html" del repository) di quella che potrebbe essere una policy sul trattamento dei dati personali nel formato da rilasciare.
Questa cartella, contiene:
- un file **html**;
- un **json** di configurazione;
- un file **javascript** con una funzione per la personalizzazione della policy;
- un file **less** molto basilare e il suo corrispettivo **css**;

In pratica è del codice che stavo preparando per i siti che gestisco e che pubblico per dare un'idea di quello che intendevo fare. Dategli un'occhiata per capire, tenendo presente che è solo una bozza e che ovviamente ogni parte, dal testo, al codice può essere cambiata, migliorata, integrata e via dicendo.

Attendo pareri.

**Comment by hmtechnology** [comment]
Il mio parere è che è una formula anche troppo completa, complimenti, funziona una meraviglia e penso sia la strada migliore! a disposizione per qualsiasi cosa. 

Ps. Secondo me dovremmo focalizzarci e dividerci il lavoro su:

#### 1. Redazione dell'informativa estesa Privacy Policy

Documento interno al sito, idealmente con url /privacy-policy.html 
1.1 Si potrebbero localizzare i vari template/modelli da utilizzare come base 
1.2 Si potrebbero localizzare i vari esempi sul web di informative estese complete (http://bruzzano.com/privacy-policy/)

#### 2. Redazione dell'informativa estesa Cookie Policy

Documento interno al sito, idealmente con url /cookie-policy.html
2.1 Si potrebbero localizzare i vari template/modelli da utilizzare come base (ad es: http://www.freenetlaw.com/free-cookies-policy/) 
2.2 Si potrebbero localizzare i vari esempi sul web di informative estese complete (ad es: http://it.matchtrip.com/cookie-policy/, http://www.haymarket.com/cookies-policy, http://robertarapicavoli.it/informativa-cookie/, http://www.ducati.it/it/cookieManager.do, http://pastebin.com/ixv0z0rz, http://bruzzano.com/cookies-policy/, http://www.giulianiautomilano.it/cookies.html, http://www.infiniti.eu/it/cookies/, http://tech.reumer.net/Google-Maps/Documentation-of-plugin-Googlemap/google-maps-api-cookies.html) 

#### 3. Realizzazione dell'informativa breve (banner su tutte le pagine) Cookie Policy (nel caso il sito utilizzi cookie NON solo tecnici).

Banner presente all'interno del sito, idealmente realizzato in JS. Sarà quindi un codice da inserire nell'head del proprio sito, personalizzabile.

#### 4. Analisi e localizzazione dei cookie nel sito web

Documento esterno al sito: contenente link e/o guida per strumenti di analisi su quale cookie sforna il sito (es: webcookies.org, http://cookiepedia.co.uk/, etc)

#### 5. Blocco preventivo dei cookie non tecnici

Documento esterno al sito: contenente link e/o guida per plugin, scripts o altro che blocchino i cookie in mancanza di un "consenso esplicito" (ad es: http://cookie-script.com/, http://sitebeam.net/cookieconsent/code/, http://cookiesdirective.com/, etc)

**Comment by Gix075** [comment]
Tendenzialmente sono d'accordo con tutto. Il testo che ho proposto è stato redatto seguendo passo passo la normativa del garante (il link di riferimento è in calce al documento).

Per quello che riguarda i modelli da seguire direi che è bene andarci con le pinze per eventuali questioni di copyright.

Per il banner da inserire io ho già pronto questo [plugin jquery](https://github.com/Gix075/cookieDisclaimer)  che è abbastanza versatile, ma ovviamente ogni ulteriore alternativa è bene accetta.

Per quello che riguarda il blocco preventivo ancora non sappiamo se integrarlo o meno. Stiamo attendendo pareri più autorevoli dei nostri. Speriamo arrivino in giornata.

**Comment by hmtechnology** [comment]
Il testo per la privacy policy però non è direttamente correlato alle funzionalità del sito web (ad es: Mailchimp, Contact Form, Ecommerce, etc)? Nel senso, non dovrebbe essere modulabile?

Sì, gli esempi (inspiration) non sono per essere seguiti o copiati assolutamente ma solo come punti di riferimento per guidare il percorso.

Per il banner ottimo, anche se l'ideale sarebbe se connesso alla funzionalità del blocco preventivo: al momento l'unico che fa un lavoro del genere, free, per siti statici e con CMS (wordpress) è http://sitebeam.net/cookieconsent/, che è stato forkato tra l'altro per creare questo plugin WP (che non so se funziona) https://github.com/henrytriplette/wordpress-cookie-law-plugin

Il blocco preventivo per i cookie terze parti è ahimè una quasi certezza.

**Comment by Gix075** [comment]
Questo primo testo riguarda solo il trattamento dei dati poi dovremo creare dei testi modulari come dici tu per cookies e servizi integrati. 

Per il blocco preventivo possiamo provare a scrivere qualche cosa di nostro o troviamo qualche strada alternativa come quelle che hai citato. 

Ti va di scrivere qualche parte della policy? Tipo qualche servizio di quelli che hai citato?

**Comment by LenusMedia** [comment]
Cercate una soluzione che blocchi in automatico?

O si può pensare a "indicare" quali zone bloccare?
Il 26/Mag/2015 22:49, "Gix075" notifications@github.com ha scritto:

**Comment by Gix075** [comment]
Beh, dato che ancora non è molto chiaro (anche se molti pareri sembrano propendere per il no) e visto che nessuno ancora si sente di prendere una posizione chiara, direi che pensare a qualcosa di "preventivo" ci può stare. Se tu hai qualche soluzione proponila tranquillamente.

**Comment by hmtechnology** [comment]
@Gix075 si volentieri, devo solo trovare un pò di tempo perchè è anche la parte principale che mi manca x i miei siti (intendo l'informativa estesa sia per Privacy che per Cookie), mentre sono molto sul pezzo per il banner + bloccaggio preventivo dei cookie, cmq conto di mettermici al primo momento libero;)

La soluzione free che io propongo per il blocco preventivo è sitebeam.net/cookieconsent/, considerando che comunque stiamo parlando, sia per il banner che per il blocco, di codici javascript è utile associare ad esso una piccola porzione di codice (da inserire nell'head) per redirectare su una pagina ad hoc tutti gli utenti che usano JS disabilitato. Non riesco a incollare il codice, inserisco uno screen, scusate
![clipboard04](https://cloud.githubusercontent.com/assets/12564824/7826789/5293556a-041f-11e5-807d-f33f6c19e585.png)

**Comment by hmtechnology** [comment]
Questa pagina italianPrivacyPolicy.html verrà aggiornata seguendo le modifiche di questa https://github.com/FattiDiCookies/italianPrivacyPolicy/blob/master/privacy-policy-it.md ? Perchè ho visto che qualcuno ha fatto modifiche nell'ultimo documento che ho linkato ma non so se nel file .html vengono aggiornate le modifiche

**Comment by Gix075** [comment]
@hmtechnology sì nella cartella html ho messo un file di esempio per illustrare il concetto della compilazione dinamica con configurazione. Quando approviamo i testi in formato .md li convertiamo in tutti i formati utili

**Comment by hmtechnology** [comment]
Perfect. Dovremmo secondo me assoldare esperti nel team (specialmente avvocati/legali), magari espandendo il progetto andando a proporlo nei gruppi FB o forum adatti.

**Comment by Gix075** [comment]
Per me va bene. Se tu hai dritte contatta chi credi possa aiutarci. Stiamo comunque aspettando alcuni pareri legali da amici avvocati esperti di questioni legate ad internet ma essendo dei favori che ci fanno i tempi ovviamente non sono brevi.

**Comment by hmtechnology** [comment]
Io sto spargendo la voce a user che hanno particolarmente a cuore il tema e l'open source;) Cerco di fare del mio meglio, il progetto (meraviglioso) lo sento anche un pò come il mio (spero senza offesa per nessuno). Anche se è una cosa lunga, no problem, la data del 2 giugno ci impone di essere a norma e chiunque non volesse aspettare ha un'opzione molto semplice per "tamponare":
- o autoscrivere le due policy (cookie e privacy) oppure iubenda pro a 19 euro all'anno (per generare cookie e privacy policy)
- usare sitebeam.net/cookieconsent/ per banner+blocco preventivo [risorsa free] oppure un plugin per WP (www.ulissepress.it/dynamic-cookie-blocker-ita/) che è a pagamento a 25 euro x sito una tantum.

Nel frattempo è doverso, in background, portare avanti questo progetto, che ne pensi?

**Comment by Gix075** [comment]
Puoi sentire il progetto come tuo perché lo è ;-) a me è questo che rende felice! Nel mio piccolo sto cercando di fare il possibile studiando ogni possibile soluzione ma ovviamente dei limiti li ho. Conto su tutti voi però!

**Comment by hmtechnology** [comment]
:)))

**Comment by hmtechnology** [comment]
Una domanda: Posto che sia la privacy che la cookie hanno una struttura base a cui poi bisogna aggiungere modularmente i servizi integrati...uno stesso servizio (tipo Mailchimp) potrà essere presente solo nella PRIVACY e non nella COOKIE (perchè di fatto non genera alcun cookie), ma altri servizi, quali credo ADSENSE, vanno sia nella privacy sia nella cookie, con due testi ovviamente differenti. Come ci organizziamo? Non è semplice aggiungere modularmente i servizi, bisognerebbe forse localizzare quali sono i servizi integrati e dividerli tra quelli che "interessano" sia la privacy che la cookie policy, quelli che interessano solo la privacy policy e quelli che interessano solo la cookie policy, non so se mi sn spiegato decentemente.

**Comment by Gix075** [comment]
Si infatti l'idea è quella di fare un json di config diviso in privacy e cookie e per i servizi inserire dei boolean tipo "mailcchimp": true/false e se true allora automaticamente lo script selezionerà la parte riguardante il servizio e l'aggiungerà alla policy.

**Comment by hmtechnology** [comment]
sarebbe l'ideale...se non erro ora siamo quasi esclusivamente sulla cookie policy giusto? quindi tutti i servizi aggiuntivi vanno descritti in ottica esclusivamente cookie e non privacy, esatto? i milestone sono riferiti alla cookie credo.

**Comment by Gix075** [comment]
@hmtechnology al momento siamo in fase di estrema confusione perché sto cercando di organizzare il tutto e di scrivere anche un po' di materiale e il lavoro è moltissimo. Sì al momento stiamo parlando di cookie, ma ovviamente dobbiamo prendere in considerazione anche il trattamento dei dati personali.

**Comment by hmtechnology** [comment]
Ok come immaginavo;)

**Comment by iusondemand** [comment]
@Gix075  e @hmtechnology  ho finalmente guardato il testo che avete inviato e mi piace molto l'idea del testo "configurabile" con impostazioni registrate in un .json.

Ovvio che ora non riusciamo a cambiare le privacy policy e integrarle completamente. Sara' opportuno pensare all'informativa estesa subito, e la integreremo subito con unlink dalle privacy policy, poi vedremo se ripetere alcune cose.

Una buona idea potrebbe essere vedere l'informativa estesa ocme quello che e'. non una nuova privacy policy, ma come qualcosa per la quale il Garante ha dato tantissimi elementi da tenere presente.

Ho fatto una checklist, ma e' ancora in divenire. Apriro' un issue per una checklist sugli elementi da mettere in una informativa estesa.

Poi controllero' quello scritto in questa.

**Comment by 2autunni** [comment]
@Gix075 ti chiedo un chiarimento:
se non ho capito male dentro l'idea sarebbe di pescare da dentro  l'informativa estesa i frammenti di "legalese" per ogni servizio (disqus, ShareThis, fb ecc ecc.) codificati dentro un json
È corretto?
alcune domande:
l'inclusione la pensavi fatta dal client via js oppure lato server? 
possiamo pensare invece di avere un unico json di avere una cartella che contenga un json per ogni servizio?
come posso aiutare? vorrei dare una mano più come sviluppatore che come scrittore di policy

**Comment by Gix075** [comment]
@2autunni si l'idea è fare come dici, ovvero json di configurazione e json di contenuti (così sono utilizzabili anche da chi non volesse usare i codici di inclusione che andremo a scrivere)  che fungano da "magazzino" per essere richiamati solo dove serve.

Io pensavo ad un'inclusione javascript (o meglio jQuery, facendo magari un plugin) che di fatto può essere integrato anche in applicazioni fatte con Phonegap o simili. Però per questioni legate all'accessibilità (di cui non sono esperto) non so se se è meglio pensare anche a qualcosa lato server.

**Comment by hmtechnology** [comment]
ho perso un pò il filo negli ultimi giorni che ero stra impegnato a terminare la "normatura" dei vari siti... @Gix075 dammi pure dei compiti specifici che fatico a districarmi vuoi per la stanchezza ma anche x la inesperienza su Git. Posso mettermi sui testi (sia privacy che cookie) con riferimento ai servizi aggiuntivi (non so se sono da terminare dei servizi o iniziarne di nuovi) o ad altro, a tua discrezione. Grazie ancora per tutto.

**Comment by Gix075** [comment]
@hmtechnology al momento ci sono ancora alcune milestone di servizi da completare e poi ne andrebbero inseriti anche altri. Poi dai pure un'occhiata ai testi già prodotti (in formato md) che trovi nella directory "docs" per vedere se noti problemi.
Principalmente ci sono da sistemare bene e ricontrollare: il testo dell'informativa estesa e quelli della breve (che devono poi essere suddivisi per le automazioni del tool).

**Comment by hmtechnology** [comment]
Perfetto, direi che partirei con l'informativa breve anche se noto che c'è un termine: "embed", che non mi torna. Dobbiam o dovremmo parlare solo in termini di cookie tecnici / profilazione e cookie proprietari / terze parti no?

**Comment by Gix075** [comment]
@hmtechnology su queste questioni più legali io non mi esprimo molto perché le mie competenze sono limitate, Però sembra che sia necessario specificare che la fonte di eventuali cookie di terze parti sono parti di codice inserite come embed, però ripeto, mi sto fidando di chi ha proposto e discusso sui testi in questione. Magari @iusondemand può darti maggiori delucidazioni in merito.

**Comment by hmtechnology** [comment]
Ho sistemato un pò le informative brevi, dateci un occhio. Appena la consideriamo chiusa, direi che restano vabbè sempre i vari servizi da "recensire" (ne ho aggiunti un pò tra i milestones) e ci si può concentrare esclusivamente sull'informativa estesa della cookie, che contiene uno scheletro comune + appunto i servizi aggiungibili modularmente.

In parallelo, se non erro, c'è la Privacy Policy, che nella struttura è nella versione definitiva e approvata, ma mancano i servizi da aggiungere...che andrebbero ancora recensiti "lato privacy"?...oppure basta la recensione lato cookie che stiamo facendo? Non so se mi sono spiegato bene nella richiesta...Dipende anche da come vogliamo elencare i cookie, se indipendenti dal servizio diciamo, oppure se all'interno di un servizio (come quando cito DoubliClick nella recensione di AdSense)

Infine i tools per gestire l'informativa estesa, il consenso etc

**Comment by iusondemand** [comment]
scusate, per stare dietro al progeto uso una app per ios e da linux (che uso su l portatile) sono riuscito solo ora a trovare giteye e installarlo. Anche io sto cercando di caricare le pile :)

Ho visto il tema dell'embed che non e' previsto dalla legge.

Beh, e' proprioc osi'. Non si parla di embed.

Ho scelto di usare embed perche' e' molto chiaro per tutti gli sviluppatori, e anche gli utenti di youtbe in questi anni hanno imparato a vedere gli embed in giro.

Potevamo usare script di terze parti, plugin di terze parti, servizi di terze parti, embed di terze parti. 

PEr me nessun problema a cambiare. Direi di scegliere qualsiasi cosa che faccia capire che e' una cosa fatta da altri, sulla quale non abbiamo potere. Il termine piu' giuridico e' servizio di terze parti, a questo punto nell'informativa estesa possiamo usare : elenco servizi di terze parti per raccordare.

Come preferite. Nella nozione di servizio di terze parti io nella mia informativa estesa finale ho fatto rientrare un elenco delle cdn, perche' poi non si sa mica perche' offrano traffico gratis a tutti per la gloria :)

**Comment by Gix075** [comment]
Chiudo alcune vecchie issue per fare un po' di pulizia e focalizzare sulle nuove. Se serve riaprite.
