### ISSUE TITLE
ramo gh-pages

### ISSUE THREAD

**Issue by 2autunni** [FattiDiCookies/italianPrivacyPolicy#72]
@Gix075 scusa i file nel ramo gh-pages andrebbero qui http://fattidicookies.github.io/ ? (vedi #36)
Li posso spostare/copiare nel repository corrispondente?

**Comment by Gix075** [comment]
No in realtà ho aperto un ramo gh-pages per il repo del progetto, in quanto mi sembrava più corretto. Lo raggiungi da github.

**Comment by 2autunni** [comment]
@Gix075 non ho capito...
 non sono i file della futura home page del progetto?

**Comment by Gix075** [comment]
@2autunni In pratica ce ne sono due, uno è quello dell'organization e uno è quello del progetto di cui il dominio è http://fattidicookies.github.io/italianPrivacyPolicy e questo è il ramo gh-pages del repository https://github.com/FattiDiCookies/italianPrivacyPolicy/tree/gh-pages

**Comment by Gix075** [comment]
L'ho aperto in quanto avevo letto che dai domini gh-pages si può distribuire i file come CDN (ho testato su un altro progetto e funziona) anche se poi @raynor85 ha proposto l'uso mi sembra di cloudfare o simili. Magari sentiamo lui che consiglia.

**Comment by iusondemand** [comment]
seguo, decidete.

**Comment by Gix075** [comment]
Chiudo per vecchiaia della issue, se serve riapriamo.
