### ISSUE TITLE
Cookie Policy : Integrazione testo per Windows Phone

### ISSUE THREAD

**Issue by lidialab** [FattiDiCookies/italianPrivacyPolicy#77]
Ciao,

innanzitutto chiedo se si può aggiungere la label "Integrazione" per le issue, intanto questa l'ho aperta come "correzione". Oppure posso usare "new"?

Premetto che non possiedo un Windows Phone quindi se qualcuno ce l'ha e può controllare meglio, comunque ho cercato le istruzioni necessarie nel sito della MS quindi dovrebbero essere giuste (altrimenti il primo martedì di un mese futuro faremo la patch ...).

Premetto anche che la sezione browser sta diventando un papiro , quindi per me si può anche pensare di mettere solo quelli che decidiamo (sto pensando per i miei siti di farlo a mo di "accordion"/a espansione).

Impostazioni dei cookie nel browser stock Internet Explorer per Windows Phone 8
    aprire il browser
    premere Altro
    premere Impostazioni
    premere Impostazioni Avanzate
    nella sezione Cookie da siti web scegliere tra: Accetta tutti, Blocca alcuni o Blocca tutti

n.d.r. : come specificato nella pagina(http://www.windowsphone.com/it-it/how-to/wp8/apps/change-privacy-and-other-browser-settings) del sito del browser "Blocca alcuni" significa che "consente di bloccare i cookie di terze parti che non hanno rigidi criteri sulla privacy e cookie di terze parti che tengono traccia di informazioni che potrebbero essere usate per contattarti senza il tuo consenso."

Per maggiori informazioni visita la pagina dedicata (http://www.windowsphone.com/it-it/how-to/wp8/apps/change-privacy-and-other-browser-settings)

Impostazioni dei cookie nel browser stock Internet Explorer Mobile per Windows Phone 7
    aprire il browser
    premere Altro
    premere Impostazioni
    impostare o togliere la spunta della voce Consenti cookie nel telefono per consentire o bloccare il salvataggio dei cookie sul dispositivo

Per maggiori informazioni visita la pagina dedicata (http://www.windowsphone.com/it-it/how-to/wp7/web/changing-privacy-and-other-browser-settings)

**Comment by Gix075** [comment]
@lidialab ottimo lavoro dal mio punto di vista. Quindi per me è già integrabile nel repository ufficiale. Se entro domani non ci sono pareri contrari o proposte di correzione al testo lo inserirò nella cookie policy. Per quanto riguarda il resto la label "integrazione" possiamo crearla, anzi lo faccio subito. Per la questione accordion possiamo sicuramente implementarla, pensavo di proporlo anche per i singoli servizi o quantomeno gruppi di servizi. L'unico ostacolo è che al momento la parte dei browser non è indipendente ma è parte del testo generale, quindi per renderla un accordion in modo dinamico partendo dai json dovremmo togliere le singole parti dei browser e farne dei file indipendenti. Forse è anche più gestibile il tutto. Aprirò una issue in merito e ne discutiamo.

**Comment by Gix075** [comment]
Il testo è stato inserito nella cookie policy.

**Comment by brunosaetta** [comment]
Per me la parte sulle istruzioni sul come disabilitare i cookie da browser è eccessiva, è sufficiente indicare la pagina web (link al sito del browser) dove sono già presente queste istruzioni. Tipo: 

X.X - Disabilitazione cookie
I cookie sono collegati al browser utilizzato e POSSONO ESSERE DISABILITATI DIRETTAMENTE DAL BROWSER, così rifiutando/revocando il consenso all'uso dei cookie. La disabilitazione dei cookie potrebbe impedire il corretto utilizzo di alcune funzioni del sito stesso, in particolare [elencare eventualmente]. 
Le istruzioni per la disabilitazione dei cookie, e per l'eventuale eliminazione di cookie già presenti sul dispositivo dell'Utente, si trovano alle seguenti pagine web: 

Mozilla Firefox http://support.mozilla.org/it/kb/Attivare%20e%20disattivare%20i%20cookie  
Windows Internet Explorer http://windows.microsoft.com/it-IT/windows7/Block-enable-or-allow-cookies  
Google Chrome http://support.google.com/chrome/bin/answer.py?hl=it&answer=95647  
Opera http://help.opera.com/Windows/10.00/it/cookies.html 
Apple Safari https://support.apple.com/it-it/HT201265 

È possibile trovare ulteriori informazioni sui cookie e su come gestirli consultando il sito www.aboutcookies.org.

**Comment by Gix075** [comment]
@brunosaetta si anche secondo me è meglio mettere i link verso i siti dei produttori anche perché così non dobbiamo star dietro ad eventuali cambiamenti.

**Comment by lidialab** [comment]
Sulla questione browser sono molto indecisa anch'io, sarebbe interessante sentire altri pareri.
Io tengo le istruzioni brevi perchè mi sembrano comode e preferisco non far allontanare troppo l'utente dal sito di partenza..

Comprendo anche i problemi di continuo aggiornamento che si dovrebbe attuare, ma la stessa cosa vale per i link. 
Bisognerebbe obbligare i produttori di browser ad avere un collegamento evidente nei propri menù e la stessa scorciatoia da tastiera...

**Comment by akybaud** [comment]
Concordo anche io su questa visione
Il 18/Lug/2015 21:45, "lidialab" notifications@github.com ha scritto:

**Comment by brunosaetta** [comment]
Sugli obblighi a carico dei produttori di browser vorrei ricordare che la maggior parte dei produttori sono piccole aziende, se non addirittura privati, per cui caricare su di loro oneri burocratici inevitabilmente porterebbe alla scomparsa di molti di questi browser. 
E' la motivazione ufficiale della Commissione europea quando ha respinto tale tipo di proposte.

**Comment by vannaccirere** [comment]
Grazie Bruno,

Io noto che nel marasma generale, quasi nessuno ha bloccato nulla, e più 
della metà delle aziende che hanno un sito web non sa ancora nulla...

**Comment by brunosaetta** [comment]
In effetti.... 
Il punto è capire se questa cosa al Garante interessa oppure no. In caso negativo torneremo tutti a fare come ci pare. Però c'è da notare che i siti delle istituzioni europee si sono adeguate alla norma, il ché fa pensare che alla lunga l'adeguamento sarà richiesto un po' a tutti. 
Per il momento direi che l'importante è essere informati (capire cosa chiede la norma), informare gli utenti correttamente (per creare una consapevolezza delle conseguenze della navigazione online) e poi iniziare a mettere in regola il sito. :-)

**Comment by Gix075** [comment]
L'informativa estesa è stata aggiornata (solo in dev) secondo le indicazioni di @brunosaetta che mi sembra siano state accolte. Quindi la policy è stata modificata togliendo tutte le istruzioni e inserendo solamente un preambolo e i link alle pagine dei produttori di browser.
I testi precedenti sono stati salvati nella directory "bozze" in quanto in un secondo momento si potrebbe optare per inserire entrambe le soluzioni e far scegliere l'utente quale testo inserire. Al momento però per mancanza di forze optiamo per la soluzione più breve.

Chiudo issue. Se ci sono errori o qualcuno ha altro da aggiungere riaprire pure.
