### ISSUE TITLE
cookiepedia

### ISSUE THREAD

**Issue by vannaccirere** [FattiDiCookies/italianPrivacyPolicy#8]
__utmt: cookie di sessione di Google Analytics  (vedi di più https://developers.google.com/analytics/resources/concepts/gaConceptsCookies)

__utma: Cookie persistente di Google Analytics: durata 730 giorni (vedi di più https://developers.google.com/analytics/resources/concepts/gaConceptsCookies)

__utmb: Cookie di sessione di google analytics (vedi di più https://developers.google.com/analytics/resources/concepts/gaConceptsCookies)

__utmc cookie di sessione di Google Analytics (vedi di più https://developers.google.com/analytics/resources/concepts/gaConceptsCookies)

__utmz cookie di Google Analytics: durata 182 giorni (vedi di più https://developers.google.com/analytics/resources/concepts/gaConceptsCookies)

wteid_245406294797569: cookie di terze parti persistente :durata 180 giorni

IMRID: cookie profilante di terze parti : durata 730 giorni
Nielsen Site Census tracking cookie vedi di più (http://www.nielsen-online.com/privacy.jsp?section=leg_scs)

**Comment by Gix075** [comment]
Il cookies **wteid_245406294797569** sai di che servizio è?

**Comment by vannaccirere** [comment]
Webtreck gmbh

**Comment by vannaccirere** [comment]
Webtreck gmbh tracci gli utenti, è un cookie generato spesso dall'embed de "il meteo.it"

**Comment by Gix075** [comment]
Chiudo per vecchiaia della issue, se serve riapriamo.
