### ISSUE TITLE
Vorrei entrare nel team

### ISSUE THREAD

**Issue by pezzeonline** [FattiDiCookies/italianPrivacyPolicy#9]
C'è inoltre un errore sul link di spiegazioni di Opera, punta a quelle di Microsoft.

**Comment by Gix075** [comment]
Grazie della segnalazione. Ti sto aggiungendo al team. Se vuoi modifica direttamente il file .md oppure segnala il bug con una nuova issue e provvederemo a correggerlo.

**Comment by Gix075** [comment]
Ho sostituito il link, per il momento chiudo la issue. Se però credi ci sia una pagina migliore da linkare riapri la issue e segnalala.
